/**
 * lib/course-builder/compliance-profiles.ts
 * Regulatory compliance profiles. Change rules by profile, not by rewriting logic.
 */

import type { ComplianceRuleSet } from './schema';

export const COMPLIANCE_PROFILES: Record<string, ComplianceRuleSet> = {
  internal_basic: {
    profileKey: 'internal_basic',
    profileLabel: 'Internal Basic',
    credentialTarget: 'INTERNAL',
    minimumProgramHours: 1,
    requiresFinalExam: false,
    requirePassingScoresForAssessments: true,
    requireInstructorSignoffForPracticals: false,
    requireEvidenceForPracticals: false,
    requireDomainMapping: false,
    requireCompetencyMapping: false,
    requireCertificateVerification: false,
    requireHourCategory: false,
    requireDeliveryMethod: false,
    requireInstructorRequirements: false,
    requireFieldworkTracking: false,
    requireArtifactRules: false,
    requireRetentionPolicy: false,
    requiredDomains: [],
  },

  state_board_strict: {
    profileKey: 'state_board_strict',
    profileLabel: 'State Board Strict',
    credentialTarget: 'STATE_BOARD',
    minimumProgramHours: 100,
    requiresFinalExam: true,
    requirePassingScoresForAssessments: true,
    requireInstructorSignoffForPracticals: true,
    requireEvidenceForPracticals: true,
    requireDomainMapping: true,
    requireCompetencyMapping: true,
    requireCertificateVerification: true,
    requireHourCategory: true,
    requireDeliveryMethod: true,
    requireInstructorRequirements: true,
    requireFieldworkTracking: true,
    requireArtifactRules: true,
    requireRetentionPolicy: true,
    requiredDomains: [],
  },

  dol_apprenticeship: {
    profileKey: 'dol_apprenticeship',
    profileLabel: 'DOL Apprenticeship',
    credentialTarget: 'DOL_APPRENTICESHIP',
    minimumProgramHours: 144,
    requiresFinalExam: true,
    requirePassingScoresForAssessments: true,
    requireInstructorSignoffForPracticals: true,
    requireEvidenceForPracticals: true,
    requireDomainMapping: true,
    requireCompetencyMapping: true,
    requireCertificateVerification: true,
    requireHourCategory: true,
    requireDeliveryMethod: true,
    requireInstructorRequirements: true,
    requireFieldworkTracking: true,
    requireArtifactRules: true,
    requireRetentionPolicy: true,
    requiredDomains: [],
  },

  naadac_peer_support: {
    profileKey: 'naadac_peer_support',
    profileLabel: 'NAADAC Peer Support',
    credentialTarget: 'NAADAC',
    minimumProgramHours: 50,
    requiresFinalExam: true,
    requirePassingScoresForAssessments: true,
    requireInstructorSignoffForPracticals: true,
    requireEvidenceForPracticals: true,
    requireDomainMapping: true,
    requireCompetencyMapping: true,
    requireCertificateVerification: true,
    requireHourCategory: true,
    requireDeliveryMethod: true,
    requireInstructorRequirements: true,
    requireFieldworkTracking: true,
    requireArtifactRules: true,
    requireRetentionPolicy: true,
    requiredDomains: [],
  },

  custom_regulated: {
    profileKey: 'custom_regulated',
    profileLabel: 'Custom Regulated',
    credentialTarget: 'CUSTOM',
    minimumProgramHours: 1,
    requiresFinalExam: false,
    requirePassingScoresForAssessments: true,
    requireInstructorSignoffForPracticals: true,
    requireEvidenceForPracticals: true,
    requireDomainMapping: true,
    requireCompetencyMapping: true,
    requireCertificateVerification: true,
    requireHourCategory: true,
    requireDeliveryMethod: true,
    requireInstructorRequirements: true,
    requireFieldworkTracking: true,
    requireArtifactRules: true,
    requireRetentionPolicy: true,
    requiredDomains: [],
  },
};

export function getComplianceProfile(profileKey: string): ComplianceRuleSet {
  return COMPLIANCE_PROFILES[profileKey] ?? COMPLIANCE_PROFILES.internal_basic;
}
