import { Metadata } from 'next';
import { requireRole } from '@/lib/auth/require-role';
import { createClient } from '@/lib/supabase/server';
import { requireAdminClient } from '@/lib/supabase/admin';
import Link from 'next/link';
import Image from 'next/image';
import { Breadcrumbs } from '@/components/ui/Breadcrumbs';
import { PLATFORM_DEFAULTS } from '@/lib/config/platform-config';
import WIOAComplianceDashboard, {
  type WIOADashboardProps,
} from '@/components/admin/WIOAComplianceDashboard';
import { CoiValidator } from '@/components/admin/CoiValidator';
import {
  getAllGuardrails,
  shouldAutoEnforce,
  type GuardrailPolicy,
} from '@/lib/compliance/guardrails';
import ComplianceItemsPanel from './ComplianceItemsPanel';
import { getPlatformConfig } from '@/lib/config/platform-config';
export const dynamic = 'force-dynamic';
export const revalidate = 60;

export const metadata: Metadata = {
  title: `Compliance Dashboard | Admin | ${process.env.NEXT_PUBLIC_ORG_NAME ?? PLATFORM_DEFAULTS.orgName}`,
  description:
    'Monitor and manage GDPR, CCPA, and regulatory compliance. Track data requests, audit logs, and privacy compliance metrics.',
};

export default async function CompliancePage() {
  await requireRole(['admin']);
  const cfg = await getPlatformConfig();
  // Use service-role client for compliance_items — RLS may block user-session reads
  const db = await requireAdminClient();
  // Keep user-session client for WIOA/other tables that need RLS context
  const supabase = await createClient();

  const [
    { count: totalItems },
    { count: compliantItems },
    { count: nonCompliantItems },
  ] = await Promise.all([
    db.from('compliance_items').select('*', { count: 'exact', head: true }),
    db.from('compliance_items').select('*', { count: 'exact', head: true }).eq('status', 'compliant'),
    db.from('compliance_items').select('*', { count: 'exact', head: true }).eq('status', 'non_compliant'),
  ]);

  // WIOA data — tables may not exist yet; all queries are safe-fallback
  const [wioaParticipants, wioaReports, wioaAlerts] = await Promise.all([
    supabase
      .from('wioa_participants')
      .select(
        'is_veteran, is_dislocated_worker, is_low_income, age_group, job_placements(id), enrollments(status)',
      )
      .limit(500)
      .then((r) => r.data ?? []),
    supabase
      .from('wioa_compliance_reports')
      .select('report_type, due_date, status, auto_generated, submission_method')
      .order('due_date', { ascending: true })
      .limit(20)
      .then((r) => r.data ?? []),
    supabase
      .from('compliance_alerts')
      .select('id, alert_type, severity, message, action_required, deadline')
      .eq('resolved', false)
      .order('severity', { ascending: false })
      .limit(20)
      .then((r) => r.data ?? []),
  ]);

  const wioaData: WIOADashboardProps = {
    participants: {
      total: wioaParticipants.length,
      veterans: wioaParticipants.filter((p: any) => p.is_veteran).length,
      dislocatedWorkers: wioaParticipants.filter((p: any) => p.is_dislocated_worker).length,
      lowIncome: wioaParticipants.filter((p: any) => p.is_low_income).length,
      youth: wioaParticipants.filter((p: any) => p.age_group === 'youth').length,
      placements: wioaParticipants.filter((p: any) => (p.job_placements as any[])?.length > 0)
        .length,
      completions: wioaParticipants.filter(
        (p: any) => (p.enrollments as any)?.status === 'completed',
      ).length,
    },
    reports: (wioaReports as any[]).map((r) => ({
      reportType: r.report_type,
      dueDate: r.due_date,
      status: r.status,
      autoGenerated: r.auto_generated ?? false,
      submissionMethod: r.submission_method ?? 'electronic',
    })),
    alerts: (wioaAlerts as any[]).map((a) => ({
      id: a.id,
      type: a.alert_type,
      severity: a.severity,
      message: a.message,
      actionRequired: a.action_required,
      deadline: a.deadline,
    })),
  };

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Image */}
      {/* Breadcrumbs */}
      <div className="bg-slate-50 border-b">
        <div className="max-w-7xl mx-auto px-4 py-3">
          <Breadcrumbs items={[{ label: 'Admin', href: '/admin' }, { label: 'Compliance' }]} />
        </div>
      </div>

      {/* Hero Section */}
      <section className="relative h-48 md:h-64 overflow-hidden">
        <Image
          src="/images/pages/admin-compliance-detail.webp"
          alt="Compliance dashboard overview"
          fill
          className="object-cover"
          quality={90}
          priority
          sizes="100vw"
        />
      </section>

      {/* Content Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-7xl mx-auto">
            {/* Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="bg-white rounded-lg shadow-sm border p-6">
                <h3 className="text-sm font-medium text-slate-600 mb-2">Total Items</h3>
                <p className="text-3xl font-bold text-brand-blue-600">{totalItems || 0}</p>
              </div>
              <div className="bg-white rounded-lg shadow-sm border p-6">
                <h3 className="text-sm font-medium text-slate-600 mb-2">Compliant</h3>
                <p className="text-3xl font-bold text-brand-green-600">{compliantItems || 0}</p>
              </div>
              <div className="bg-white rounded-lg shadow-sm border p-6">
                <h3 className="text-sm font-medium text-slate-600 mb-2">Non-Compliant</h3>
                <p className="text-3xl font-bold text-brand-red-600">{nonCompliantItems || 0}</p>
              </div>
            </div>

            <div className="bg-white rounded-lg shadow-sm border p-6 mb-6">
              <h2 className="text-lg font-bold text-slate-900 mb-2">WIOA / INTraining ETPL forms</h2>
              <p className="text-sm text-slate-600 mb-4">
                Initial Eligibility Aggregate Performance (new programs) and Section 188 Equal
                Opportunity checklist — one set per program.
              </p>
              <Link
                href="/admin/compliance/wioa-etpl"
                className="inline-flex items-center text-sm font-semibold text-brand-blue-600 hover:underline"
              >
                Open WIOA / ETPL compliance forms →
              </Link>
            </div>

            {/* Compliance checklist — reads compliance_items via /api/compliance/items */}
            <div className="bg-white rounded-lg shadow-sm border p-6">
              <ComplianceItemsPanel />
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-brand-blue-700">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">Compliance Dashboard</h2>
            <p className="text-base md:text-lg text-brand-blue-100 mb-8">
              Monitor FERPA, WIOA, and DOL compliance across all programs.
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <Link
                href="/admin/compliance"
                className="bg-white text-brand-blue-700 px-8 py-4 rounded-lg font-semibold hover:bg-slate-50 text-lg"
              >
                Run Audit
              </Link>
              <Link
                href="/admin/ferpa"
                className="bg-brand-blue-800 text-white px-8 py-4 rounded-lg font-semibold hover:bg-brand-blue-600 border-2 border-white text-lg"
              >
                View FERPA Log
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Automated Guardrails */}
      <section className="py-8 px-6">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">
            Automated Compliance Guardrails
          </h2>
          <div className="grid md:grid-cols-3 gap-6 mb-8">
            {(['critical', 'major', 'minor'] as const).map((severity) => {
              const all = getAllGuardrails();
              const filtered = all.filter((g) => g.severity === severity);
              const autoCount = filtered.filter(shouldAutoEnforce).length;
              const colors = {
                critical: 'border-brand-red-500 bg-brand-red-50',
                major: 'border-amber-500 bg-amber-50',
                minor: 'border-brand-blue-500 bg-brand-blue-50',
              };
              return (
                <div key={severity} className={`rounded-xl border-l-4 p-5 ${colors[severity]}`}>
                  <h3 className="font-bold capitalize text-slate-900">{severity} Guardrails</h3>
                  <p className="text-3xl font-bold mt-2">{filtered.length}</p>
                  <p className="text-sm text-slate-700 mt-1">{autoCount} auto-enforced</p>
                </div>
              );
            })}
          </div>

          <div className="bg-white rounded-xl border overflow-hidden">
            <div className="px-6 py-4 border-b">
              <h3 className="font-semibold">Active Policies</h3>
            </div>
            <table className="w-full">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-3 text-left text-sm font-semibold">Policy</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold">Type</th>
                  <th className="px-6 py-3 text-center text-sm font-semibold">Severity</th>
                  <th className="px-6 py-3 text-center text-sm font-semibold">Auto-Enforce</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold">Action</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold">MOU Ref</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {getAllGuardrails().map((g: GuardrailPolicy) => (
                  <tr key={g.id} className="hover:bg-slate-50">
                    <td className="px-6 py-3">
                      <p className="font-medium text-sm">{g.name}</p>
                      <p className="text-xs text-slate-700 mt-0.5">{g.description}</p>
                    </td>
                    <td className="px-6 py-3 text-sm text-slate-900 capitalize">
                      {g.violationType.replace(/_/g, ' ')}
                    </td>
                    <td className="px-6 py-3 text-center">
                      <span
                        className={`px-2 py-1 rounded text-xs font-medium ${
                          g.severity === 'critical'
                            ? 'bg-brand-red-100 text-brand-red-700'
                            : g.severity === 'major'
                              ? 'bg-amber-100 text-amber-700'
                              : 'bg-brand-blue-100 text-brand-blue-700'
                        }`}
                      >
                        {g.severity}
                      </span>
                    </td>
                    <td className="px-6 py-3 text-center">
                      {shouldAutoEnforce(g) ? (
                        <span className="text-brand-green-600 text-sm font-medium">Yes</span>
                      ) : (
                        <span className="text-slate-700 text-sm">Manual</span>
                      )}
                    </td>
                    <td className="px-6 py-3 text-sm text-slate-900 capitalize">
                      {g.enforcementAction.replace(/_/g, ' ')}
                    </td>
                    <td className="px-6 py-3 text-xs text-slate-700">{g.mouSection}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* WIOA Compliance Dashboard */}
      <section className="py-8 px-6">
        <div className="max-w-7xl mx-auto">
          <WIOAComplianceDashboard {...wioaData} />
        </div>
      </section>

      {/* COI Validator — Certificate of Insurance review for partner/employer onboarding */}
      <section className="py-8 px-6">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-xl font-bold text-slate-900 mb-4">
            Certificate of Insurance Validator
          </h2>
          <p className="text-slate-600 mb-6 text-sm">
            Upload and validate COI documents for employer and program holder onboarding.
          </p>
          <CoiValidator expectedCertificateHolder={cfg.certificateHolder} />
        </div>
      </section>
    </div>
  );
}
