/**
 * heroBanners - type definitions and runtime loader.
 *
 * Data lives in public/data/hero-banners.json (generated by scripts/export-hero-banners.ts).
 * Loading from JSON keeps 124 KB of string data out of the webpack module graph.
 *
 * Video heroes: home, active program pages, core product pages.
 * Image-only heroes: informational pages (contact, donate, press, etc.)
 */

import { loadJsonOnce } from '@/lib/data/json-cache';

export interface HeroBannerCta {
  label: string;
  href: string;
  variant?: 'primary' | 'secondary';
}

export interface HeroBannerConfig {
  pageKey: string;
  videoSrcDesktop?: string;
  videoSrcMobile?: string;
  posterImage?: string;
  voiceoverSrc?: string;
  microLabel?: string;
  belowHeroHeadline: string;
  belowHeroSubheadline: string;
  primaryCta: HeroBannerCta;
  secondaryCta?: HeroBannerCta;
  trustIndicators?: string[];
  transcript?: string;
  analyticsName: string;
}

export type ProgramHeroBannerConfig = HeroBannerConfig & {
  microLabel: string;
  credentialLabel: string;
  durationLabel: string;
  secondaryCta: HeroBannerCta;
  trustIndicators: string[];
  transcript: string;
} & (
    | { salaryExempt?: false; salaryRangeLabel: string }
    | { salaryExempt: true; salaryNote: string; salaryRangeLabel?: string }
  );

let normalizedData: Record<string, HeroBannerConfig> | null = null;

function getData(): Record<string, HeroBannerConfig> {
  if (normalizedData) return normalizedData;

  const raw = loadJsonOnce<Record<string, HeroBannerConfig>>('hero-banners.json');
  normalizedData = Object.fromEntries(
    Object.entries(raw).map(([key, banner]) => [
      key,
      banner.videoSrcDesktop
        ? { ...banner, videoSrcMobile: banner.videoSrcDesktop }
        : banner,
    ]),
  );

  return normalizedData;
}

const heroBanners: Record<string, HeroBannerConfig> = new Proxy(
  {} as Record<string, HeroBannerConfig>,
  {
    get(_t, key: string) {
      return getData()[key];
    },
    ownKeys() {
      return Object.keys(getData());
    },
    has(_t, key: string) {
      return key in getData();
    },
    getOwnPropertyDescriptor(_t, key: string) {
      const d = getData();
      if (key in d) return { configurable: true, enumerable: true, value: d[key] };
      return undefined;
    },
  },
);

export default heroBanners;

export const internalProgramHeroBanners: Record<string, ProgramHeroBannerConfig> = new Proxy(
  {} as Record<string, ProgramHeroBannerConfig>,
  {
    get(_t, key: string) {
      const e = getData()[key] as any;
      return e?.credentialLabel ? e : undefined;
    },
    ownKeys() {
      return Object.keys(getData()).filter((k) => (getData()[k] as any)?.credentialLabel);
    },
    has(_t, key: string) {
      const e = getData()[key] as any;
      return !!e?.credentialLabel;
    },
    getOwnPropertyDescriptor(_t, key: string) {
      const e = getData()[key] as any;
      if (e?.credentialLabel) return { configurable: true, enumerable: true, value: e };
      return undefined;
    },
  },
);
