export const siteConfig = {
  name: 'Elevate for Humanity',
  url: 'https://www.elevateforhumanity.org',
  description:
    'Career training, workforce pathways, and community-centered education programs.',
  learnUrl: 'https://www.elevateforhumanity.org',
  phone: '(317) 314-3757',
  email: 'info@elevateforhumanity.org',
  address: 'Indianapolis, IN',
  hours: 'Mon–Fri 8am–6pm, Sat 9am–1pm EST',
  nav: [
    { label: 'Programs', href: '/programs' },
    { label: 'Career Training', href: '/career-training' },
    { label: 'Career Services', href: '/career-services' },
    { label: 'Funding', href: '/funding' },
    { label: 'Community Services', href: '/community-services' },
    { label: 'Support', href: '/support' },
    { label: 'Help', href: '/help' },
    { label: 'Legal', href: '/legal' },
    { label: 'Policies', href: '/policies' },
    { label: 'Docs', href: '/docs' },
    { label: 'License', href: '/license' },
    { label: 'FERPA', href: '/ferpa' },
    { label: 'Employer Portal', href: '/employer-portal' },
    { label: 'PWA', href: '/pwa' },
    { label: 'Preview', href: '/preview' },
    { label: 'About', href: '/about' },
    { label: 'Contact', href: '/contact' },
  ],
  handoff: {
    apply: 'https://learn.elevateforhumanity.org/apply',
    login: 'https://learn.elevateforhumanity.org/login',
    checkout: 'https://learn.elevateforhumanity.org/checkout',
    enrollment: 'https://learn.elevateforhumanity.org/enrollment',
    lms: 'https://learn.elevateforhumanity.org/lms/programs',
    studentPortal: 'https://learn.elevateforhumanity.org/learner/dashboard',
  },
};
