/**
 * Central System Registry
 *
 * Canonical per-program and per-system map. Single source of truth for:
 *   - program slugs → routes, APIs, DB tables, certificate templates
 *   - system → owned routes, APIs, tables, status
 *   - AI action → required permission tier
 *
 * Update this file when adding programs or systems.
 * The AI console reads this at runtime for structural reasoning.
 */

// ── Program Registry ─────────────────────────────────────────────────────────

export interface ProgramRegistryEntry {
  slug: string;
  title: string;
  category: 'healthcare' | 'trades' | 'apprenticeship' | 'business' | 'technology' | 'special' | 'hospitality' | 'beauty';
  canonical_route: string;
  apply_route: string;
  checkout_route: string;
  enrollment_api: string;
  certificate_template: string | null;
  db_program_id?: string; // populated from live DB — optional
  has_dedicated_page: boolean; // true = app/programs/[slug]/page.tsx exists
  has_lms_course: boolean;
  status: 'active' | 'draft' | 'archived';
  funding: ('wioa' | 'ita' | 'self_pay' | 'employer' | 'jri' | 'grant')[];
}

export const PROGRAM_REGISTRY: ProgramRegistryEntry[] = [
  // ── Healthcare ──────────────────────────────────────────────────────────
  {
    slug: 'cna',
    title: 'CNA / Nursing Assistant',
    category: 'healthcare',
    canonical_route: '/programs/cna',
    apply_route: '/apply?program=cna',
    checkout_route: '/checkout/cna',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'cna-completion-v1',
    has_dedicated_page: true,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'home-health-aide',
    title: 'Home Health Aide',
    category: 'healthcare',
    canonical_route: '/programs/home-health-aide',
    apply_route: '/programs/home-health-aide/apply',
    checkout_route: '/checkout/home-health-aide',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'dental-assistant',
    title: 'Dental Assistant',
    category: 'healthcare',
    canonical_route: '/programs/dental-assistant',
    apply_route: '/programs/dental-assistant/apply',
    checkout_route: '/checkout/dental-assistant',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'sanitation-infection-control',
    title: 'Sanitation & Infection Control',
    category: 'healthcare',
    canonical_route: '/programs/sanitation-infection-control',
    apply_route: '/programs/sanitation-infection-control/apply',
    checkout_route: '/checkout/sanitation-infection-control',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'self_pay'],
  },
  {
    slug: 'chw-cert',
    title: 'Community Healthcare Worker',
    category: 'healthcare',
    canonical_route: '/programs/chw-cert',
    apply_route: '/programs/chw-cert/apply',
    checkout_route: '/checkout/chw-cert',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  // NHA Suite
  {
    slug: 'nha-pharmacy-technician',
    title: 'Pharmacy Technician (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-pharmacy-technician',
    apply_route: '/programs/nha-pharmacy-technician/apply',
    checkout_route: '/checkout/nha-pharmacy-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cpht',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-ehr',
    title: 'Electronic Health Records (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-ehr',
    apply_route: '/programs/nha-ehr/apply',
    checkout_route: '/checkout/nha-ehr',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cehrs',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-patient-care-technician',
    title: 'Patient Care Technician (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-patient-care-technician',
    apply_route: '/programs/nha-patient-care-technician/apply',
    checkout_route: '/checkout/nha-patient-care-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cpct',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-medical-admin-assistant',
    title: 'Medical Administrative Assistant (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-medical-admin-assistant',
    apply_route: '/programs/nha-medical-admin-assistant/apply',
    checkout_route: '/checkout/nha-medical-admin-assistant',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cmaa',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-medical-assistant',
    title: 'Medical Assistant (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-medical-assistant',
    apply_route: '/programs/nha-medical-assistant/apply',
    checkout_route: '/checkout/nha-medical-assistant',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-ccma',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-billing-coding',
    title: 'Medical Billing & Coding (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-billing-coding',
    apply_route: '/programs/nha-billing-coding/apply',
    checkout_route: '/checkout/nha-billing-coding',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cbc',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-phlebotomy',
    title: 'Phlebotomy Technician (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-phlebotomy',
    apply_route: '/programs/nha-phlebotomy/apply',
    checkout_route: '/checkout/nha-phlebotomy',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cppt',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'nha-ekg-technician',
    title: 'EKG Technician (NHA)',
    category: 'healthcare',
    canonical_route: '/programs/nha-ekg-technician',
    apply_route: '/programs/nha-ekg-technician/apply',
    checkout_route: '/checkout/nha-ekg-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nha-cet',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'qma',
    title: 'QMA / Medication Aide',
    category: 'healthcare',
    canonical_route: '/programs/qma',
    apply_route: '/apply?program=qma',
    checkout_route: '/checkout/qma',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'qma-completion-v1',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'medical-assistant',
    title: 'Medical Assistant',
    category: 'healthcare',
    canonical_route: '/programs/medical-assistant',
    apply_route: '/programs/medical-assistant/apply',
    checkout_route: '/checkout/medical-assistant',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'ma-completion-v1',
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'peer-recovery-specialist',
    title: 'Peer Recovery Specialist',
    category: 'healthcare',
    canonical_route: '/programs/peer-recovery-specialist',
    apply_route: '/programs/peer-recovery-specialist/apply',
    checkout_route: '/checkout/peer-recovery-specialist',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'jri', 'self_pay'],
  },
  {
    slug: 'direct-support-professional',
    title: 'Direct Support Professional',
    category: 'healthcare',
    canonical_route: '/programs/direct-support-professional',
    apply_route: '/programs/direct-support-professional/apply',
    checkout_route: '/checkout/direct-support-professional',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'self_pay'],
  },
  {
    slug: 'drug-alcohol-specimen-collector',
    title: 'Drug & Alcohol Specimen Collector',
    category: 'healthcare',
    canonical_route: '/programs/drug-alcohol-specimen-collector',
    apply_route: '/programs/drug-alcohol-specimen-collector/apply',
    checkout_route: '/checkout/drug-alcohol-specimen-collector',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['self_pay', 'employer'],
  },
  {
    slug: 'cpr-first-aid',
    title: 'CPR / First Aid',
    category: 'healthcare',
    canonical_route: '/programs/cpr-first-aid',
    apply_route: '/programs/cpr-first-aid/apply',
    checkout_route: '/checkout/cpr-first-aid',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['self_pay', 'employer'],
  },
  {
    slug: 'pharmacy-technician',
    title: 'Pharmacy Technician',
    category: 'healthcare',
    canonical_route: '/programs/pharmacy-technician',
    apply_route: '/programs/pharmacy-technician/apply',
    checkout_route: '/checkout/pharmacy-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'phlebotomy',
    title: 'Phlebotomy',
    category: 'healthcare',
    canonical_route: '/programs/phlebotomy',
    apply_route: '/programs/phlebotomy/apply',
    checkout_route: '/checkout/phlebotomy',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  // ── Skilled Trades ──────────────────────────────────────────────────────
  {
    slug: 'hvac-technician',
    title: 'HVAC Technician',
    category: 'trades',
    canonical_route: '/programs/hvac-technician',
    apply_route: '/programs/hvac-technician/apply',
    checkout_route: '/checkout/hvac-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'hvac-epa608-v1',
    has_dedicated_page: true,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay', 'employer'],
  },
  {
    slug: 'building-services-technician',
    title: 'Building Services Technician',
    category: 'trades',
    canonical_route: '/programs/building-services-technician',
    apply_route: '/programs/building-services-technician/apply',
    checkout_route: '/checkout/building-services-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'self_pay'],
  },
  {
    slug: 'electrical',
    title: 'Electrical',
    category: 'trades',
    canonical_route: '/programs/electrical',
    apply_route: '/programs/electrical/apply',
    checkout_route: '/checkout/electrical',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'plumbing',
    title: 'Plumbing',
    category: 'trades',
    canonical_route: '/programs/plumbing',
    apply_route: '/programs/plumbing/apply',
    checkout_route: '/checkout/plumbing',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'cdl-training',
    title: 'CDL Training',
    category: 'trades',
    canonical_route: '/programs/cdl-training',
    apply_route: '/programs/cdl-training/apply',
    checkout_route: '/checkout/cdl-training',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay', 'employer'],
  },
  // ── Apprenticeships ─────────────────────────────────────────────────────
  {
    slug: 'barber-apprenticeship',
    title: 'Barber Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/barber-apprenticeship',
    apply_route: '/programs/barber-apprenticeship/apply',
    checkout_route: '/checkout/barber-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'barber-apprenticeship-v1',
    has_dedicated_page: true,
    has_lms_course: true,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'cosmetology-apprenticeship',
    title: 'Cosmetology Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/cosmetology-apprenticeship',
    apply_route: '/programs/cosmetology-apprenticeship/apply',
    checkout_route: '/checkout/cosmetology-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'cosmetology-apprenticeship-v1',
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'esthetician-apprenticeship',
    title: 'Esthetician Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/esthetician-apprenticeship',
    apply_route: '/programs/esthetician-apprenticeship/apply',
    checkout_route: '/checkout/esthetician-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'nail-technician-apprenticeship',
    title: 'Nail Technician Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/nail-technician-apprenticeship',
    apply_route: '/apply?program=nail-technician-apprenticeship',
    checkout_route: '/checkout/nail-technician-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  // ── Business & Finance ──────────────────────────────────────────────────
  {
    slug: 'finance-bookkeeping-accounting',
    title: 'Finance, Bookkeeping & Accounting',
    category: 'business',
    canonical_route: '/programs/finance-bookkeeping-accounting',
    apply_route: '/programs/finance-bookkeeping-accounting/apply',
    checkout_route: '/checkout/finance-bookkeeping-accounting',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: true,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  // ── Trades (additional) ─────────────────────────────────────────────────
  {
    slug: 'welding',
    title: 'Welding',
    category: 'trades',
    canonical_route: '/programs/welding',
    apply_route: '/programs/welding/apply',
    checkout_route: '/checkout/welding',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'building-maintenance-wrg',
    title: 'Building Maintenance (WRG)',
    category: 'trades',
    canonical_route: '/programs/building-maintenance-wrg',
    apply_route: '/programs/building-maintenance-wrg/apply',
    checkout_route: '/checkout/building-maintenance-wrg',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'grant', 'self_pay'],
  },
  {
    slug: 'solar-panel-installation',
    title: 'Solar Panel Installation',
    category: 'trades',
    canonical_route: '/programs/solar-panel-installation',
    apply_route: '/programs/solar-panel-installation/apply',
    checkout_route: '/checkout/solar-panel-installation',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'manufacturing-technician',
    title: 'Manufacturing Technician',
    category: 'trades',
    canonical_route: '/programs/manufacturing-technician',
    apply_route: '/programs/manufacturing-technician/apply',
    checkout_route: '/checkout/manufacturing-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'diesel-mechanic',
    title: 'Diesel Mechanic',
    category: 'trades',
    canonical_route: '/programs/diesel-mechanic',
    apply_route: '/programs/diesel-mechanic/apply',
    checkout_route: '/checkout/diesel-mechanic',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'automotive-technician',
    title: 'Automotive Technician',
    category: 'trades',
    canonical_route: '/programs/automotive-technician',
    apply_route: '/programs/automotive-technician/apply',
    checkout_route: '/checkout/automotive-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'construction-trades-certification',
    title: 'Construction Trades Certification',
    category: 'trades',
    canonical_route: '/programs/construction-trades-certification',
    apply_route: '/programs/construction-trades-certification/apply',
    checkout_route: '/checkout/construction-trades-certification',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'forklift',
    title: 'Forklift Operator Certification',
    category: 'trades',
    canonical_route: '/programs/forklift',
    apply_route: '/programs/forklift/apply',
    checkout_route: '/checkout/forklift',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  // ── Apprenticeships ─────────────────────────────────────────────────────
  {
    slug: 'culinary-apprenticeship',
    title: 'Culinary Arts Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/culinary-apprenticeship',
    apply_route: '/programs/culinary-apprenticeship/apply',
    checkout_route: '/checkout/culinary-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'grant', 'self_pay'],
  },
  {
    slug: 'youth-culinary-apprenticeship',
    title: 'Youth Culinary Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/youth-culinary-apprenticeship',
    apply_route: '/programs/youth-culinary-apprenticeship/apply',
    checkout_route: '/checkout/youth-culinary-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'grant'],
  },
  {
    slug: 'emt-apprenticeship',
    title: 'EMT Apprenticeship',
    category: 'apprenticeship',
    canonical_route: '/programs/emt-apprenticeship',
    apply_route: '/programs/emt-apprenticeship/apply',
    checkout_route: '/checkout/emt-apprenticeship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  // ── Business & Finance (additional) ────────────────────────────────────
  {
    slug: 'bookkeeping',
    title: 'Bookkeeping',
    category: 'business',
    canonical_route: '/programs/bookkeeping',
    apply_route: '/programs/bookkeeping/apply',
    checkout_route: '/checkout/bookkeeping',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'tax-preparation',
    title: 'Tax Preparation',
    category: 'business',
    canonical_route: '/programs/tax-preparation',
    apply_route: '/programs/tax-preparation/apply',
    checkout_route: '/checkout/tax-preparation',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'entrepreneurship',
    title: 'Entrepreneurship',
    category: 'business',
    canonical_route: '/programs/entrepreneurship',
    apply_route: '/programs/entrepreneurship/apply',
    checkout_route: '/checkout/entrepreneurship',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'grant', 'self_pay'],
  },
  {
    slug: 'business-startup',
    title: 'Business Startup',
    category: 'business',
    canonical_route: '/programs/business-startup',
    apply_route: '/programs/business-startup/apply',
    checkout_route: '/checkout/business-startup',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'grant', 'self_pay'],
  },
  {
    slug: 'business-administration',
    title: 'Business Administration',
    category: 'business',
    canonical_route: '/programs/business-administration',
    apply_route: '/programs/business-administration/apply',
    checkout_route: '/checkout/business-administration',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'real-estate-agent',
    title: 'Real Estate Agent',
    category: 'business',
    canonical_route: '/programs/real-estate-agent',
    apply_route: '/programs/real-estate-agent/apply',
    checkout_route: '/checkout/real-estate-agent',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'insurance-agent',
    title: 'Insurance Agent',
    category: 'business',
    canonical_route: '/programs/insurance-agent',
    apply_route: '/programs/insurance-agent/apply',
    checkout_route: '/checkout/insurance-agent',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'administrative-assistant',
    title: 'Administrative Assistant',
    category: 'business',
    canonical_route: '/programs/administrative-assistant',
    apply_route: '/programs/administrative-assistant/apply',
    checkout_route: '/checkout/administrative-assistant',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'customer-service-representative',
    title: 'Customer Service Representative',
    category: 'business',
    canonical_route: '/programs/customer-service-representative',
    apply_route: '/programs/customer-service-representative/apply',
    checkout_route: '/checkout/customer-service-representative',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'office-administration',
    title: 'Office Administration',
    category: 'business',
    canonical_route: '/programs/office-administration',
    apply_route: '/programs/office-administration/apply',
    checkout_route: '/checkout/office-administration',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'project-management',
    title: 'Project Management',
    category: 'business',
    canonical_route: '/programs/project-management',
    apply_route: '/programs/project-management/apply',
    checkout_route: '/checkout/project-management',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  // ── Technology ──────────────────────────────────────────────────────────
  {
    slug: 'it-help-desk',
    title: 'IT Help Desk',
    category: 'technology',
    canonical_route: '/programs/it-help-desk',
    apply_route: '/programs/it-help-desk/apply',
    checkout_route: '/checkout/it-help-desk',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'software-development',
    title: 'Software Development',
    category: 'technology',
    canonical_route: '/programs/software-development',
    apply_route: '/programs/software-development/apply',
    checkout_route: '/checkout/software-development',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    category: 'technology',
    canonical_route: '/programs/web-development',
    apply_route: '/programs/web-development/apply',
    checkout_route: '/checkout/web-development',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'data-analytics',
    title: 'Data Analytics',
    category: 'technology',
    canonical_route: '/programs/data-analytics',
    apply_route: '/programs/data-analytics/apply',
    checkout_route: '/checkout/data-analytics',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    category: 'technology',
    canonical_route: '/programs/cybersecurity-analyst',
    apply_route: '/programs/cybersecurity-analyst/apply',
    checkout_route: '/checkout/cybersecurity-analyst',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'network-administration',
    title: 'Network Administration',
    category: 'technology',
    canonical_route: '/programs/network-administration',
    apply_route: '/programs/network-administration/apply',
    checkout_route: '/checkout/network-administration',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'network-support-technician',
    title: 'Network Support Technician',
    category: 'technology',
    canonical_route: '/programs/network-support-technician',
    apply_route: '/programs/network-support-technician/apply',
    checkout_route: '/checkout/network-support-technician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'cad-drafting',
    title: 'CAD Drafting',
    category: 'technology',
    canonical_route: '/programs/cad-drafting',
    apply_route: '/programs/cad-drafting/apply',
    checkout_route: '/checkout/cad-drafting',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  {
    slug: 'graphic-design',
    title: 'Graphic Design',
    category: 'technology',
    canonical_route: '/programs/graphic-design',
    apply_route: '/programs/graphic-design/apply',
    checkout_route: '/checkout/graphic-design',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
  // ── Special Programs ────────────────────────────────────────────────────
  {
    slug: 'jri',
    title: 'Justice-Involved Reentry Initiative',
    category: 'special',
    canonical_route: '/programs/jri',
    apply_route: '/programs/jri/apply',
    checkout_route: '/checkout/jri',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['jri', 'grant', 'wioa'],
  },
  {
    slug: 'jri-introduction',
    title: 'JRI Introduction',
    category: 'special',
    canonical_route: '/programs/jri-introduction',
    apply_route: '/programs/jri-introduction/apply',
    checkout_route: '/checkout/jri-introduction',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'jri-badge-1-mindsets',
    title: 'JRI Badge 1: Mindsets',
    category: 'special',
    canonical_route: '/programs/jri-badge-1-mindsets',
    apply_route: '/programs/jri-badge-1-mindsets/apply',
    checkout_route: '/checkout/jri-badge-1-mindsets',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'jri-badge-1',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'jri-badge-2-self-management',
    title: 'JRI Badge 2: Self-Management',
    category: 'special',
    canonical_route: '/programs/jri-badge-2-self-management',
    apply_route: '/programs/jri-badge-2-self-management/apply',
    checkout_route: '/checkout/jri-badge-2-self-management',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'jri-badge-2',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'jri-badge-3-learning-strategies',
    title: 'JRI Badge 3: Learning Strategies',
    category: 'special',
    canonical_route: '/programs/jri-badge-3-learning-strategies',
    apply_route: '/programs/jri-badge-3-learning-strategies/apply',
    checkout_route: '/checkout/jri-badge-3-learning-strategies',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'jri-badge-3',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'jri-badge-4-social-skills',
    title: 'JRI Badge 4: Social Skills',
    category: 'special',
    canonical_route: '/programs/jri-badge-4-social-skills',
    apply_route: '/programs/jri-badge-4-social-skills/apply',
    checkout_route: '/checkout/jri-badge-4-social-skills',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'jri-badge-4',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'jri-badge-5-workplace-skills',
    title: 'JRI Badge 5: Workplace Skills',
    category: 'special',
    canonical_route: '/programs/jri-badge-5-workplace-skills',
    apply_route: '/programs/jri-badge-5-workplace-skills/apply',
    checkout_route: '/checkout/jri-badge-5-workplace-skills',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'jri-badge-5',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'jri-badge-6-launch-a-career',
    title: 'JRI Badge 6: Launch a Career',
    category: 'special',
    canonical_route: '/programs/jri-badge-6-launch-a-career',
    apply_route: '/programs/jri-badge-6-launch-a-career/apply',
    checkout_route: '/checkout/jri-badge-6-launch-a-career',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'jri-badge-6',
    has_dedicated_page: false,
    has_lms_course: true,
    status: 'active',
    funding: ['jri', 'grant'],
  },
  {
    slug: 'reentry-specialist',
    title: 'Reentry Specialist',
    category: 'special',
    canonical_route: '/programs/reentry-specialist',
    apply_route: '/programs/reentry-specialist/apply',
    checkout_route: '/checkout/reentry-specialist',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['jri', 'grant', 'wioa'],
  },
  {
    slug: 'life-coach-certification-wioa',
    title: 'Life Coach Certification (WIOA)',
    category: 'special',
    canonical_route: '/programs/life-coach-certification-wioa',
    apply_route: '/programs/life-coach-certification-wioa/apply',
    checkout_route: '/checkout/life-coach-certification-wioa',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'grant'],
  },
  {
    slug: 'nrf-riseup',
    title: 'NRF Rise Up',
    category: 'special',
    canonical_route: '/programs/nrf-riseup',
    apply_route: '/programs/nrf-riseup/apply',
    checkout_route: '/checkout/nrf-riseup',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'nrf-riseup',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  // ── Hospitality ─────────────────────────────────────────────────────────
  {
    slug: 'start-hospitality',
    title: 'START Hospitality',
    category: 'hospitality',
    canonical_route: '/programs/start-hospitality',
    apply_route: '/programs/start-hospitality/apply',
    checkout_route: '/checkout/start-hospitality',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'start-hospitality',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'guest-service-gold',
    title: 'Guest Service Gold',
    category: 'hospitality',
    canonical_route: '/programs/guest-service-gold',
    apply_route: '/programs/guest-service-gold/apply',
    checkout_route: '/checkout/guest-service-gold',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'guest-service-gold',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'servsuccess',
    title: 'ServSuccess',
    category: 'hospitality',
    canonical_route: '/programs/servsuccess',
    apply_route: '/programs/servsuccess/apply',
    checkout_route: '/checkout/servsuccess',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'servsuccess',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'servsafe-food-handler',
    title: 'ServSafe Food Handler',
    category: 'hospitality',
    canonical_route: '/programs/servsafe-food-handler',
    apply_route: '/programs/servsafe-food-handler/apply',
    checkout_route: '/checkout/servsafe-food-handler',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'servsafe-food-handler',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  {
    slug: 'servsafe-manager',
    title: 'ServSafe Manager',
    category: 'hospitality',
    canonical_route: '/programs/servsafe-manager',
    apply_route: '/programs/servsafe-manager/apply',
    checkout_route: '/checkout/servsafe-manager',
    enrollment_api: '/api/enrollment/create',
    certificate_template: 'servsafe-manager',
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'employer', 'self_pay'],
  },
  // ── Beauty ──────────────────────────────────────────────────────────────
  {
    slug: 'esthetician',
    title: 'Esthetician (Professional)',
    category: 'beauty',
    canonical_route: '/programs/esthetician',
    apply_route: '/programs/esthetician/apply',
    checkout_route: '/checkout/esthetician',
    enrollment_api: '/api/enrollment/create',
    certificate_template: null,
    has_dedicated_page: false,
    has_lms_course: false,
    status: 'active',
    funding: ['wioa', 'ita', 'self_pay'],
  },
];

// ── Lookup helpers ───────────────────────────────────────────────────────────

export function getProgramBySlug(slug: string): ProgramRegistryEntry | undefined {
  return PROGRAM_REGISTRY.find(p => p.slug === slug);
}

export function getProgramsByCategory(category: ProgramRegistryEntry['category']): ProgramRegistryEntry[] {
  return PROGRAM_REGISTRY.filter(p => p.category === category);
}

export function getActivePrograms(): ProgramRegistryEntry[] {
  return PROGRAM_REGISTRY.filter(p => p.status === 'active');
}

// ── AI Permission Tiers ──────────────────────────────────────────────────────
// Controls what the AI operator is allowed to do without human approval.

export type AiPermissionTier =
  | 'read'        // read-only queries, no side effects
  | 'operator'    // operational actions: send emails, flag at-risk, run reports
  | 'developer'   // code/data actions: scan routes, query DB, inspect links
  | 'deployer'    // deployment actions: trigger builds, apply migrations
  | 'super';      // destructive actions: delete data, force-rollback

export interface AiToolPermission {
  tool: string;
  tier: AiPermissionTier;
  requires_confirmation: boolean;
  affects_production: boolean;
  description: string;
}

export const AI_TOOL_PERMISSIONS: AiToolPermission[] = [
  // Read tier — no side effects
  { tool: 'get_analytics',           tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Read analytics data' },
  { tool: 'list_applications',       tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List applications' },
  { tool: 'list_students',           tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List students' },
  { tool: 'list_enrollments',        tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List enrollments' },
  { tool: 'list_programs',           tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List programs' },
  { tool: 'list_cohorts',            tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List cohorts' },
  { tool: 'list_wioa',               tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List WIOA cases' },
  { tool: 'list_at_risk',            tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List at-risk learners' },
  { tool: 'list_completions',        tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List completions' },
  { tool: 'list_users',              tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List users' },
  { tool: 'list_payout_queue',       tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List payout queue' },
  { tool: 'list_shops',              tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List partner shops' },
  { tool: 'run_report',              tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Run operational report' },
  { tool: 'check_system_health',     tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Check system health' },
  { tool: 'check_monitoring',        tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Check monitoring status' },
  { tool: 'get_platform_state',      tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Get live platform state' },
  { tool: 'lookup_knowledge_graph',  tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Look up knowledge graph' },
  { tool: 'recall_memory',           tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Recall operational memory' },
  { tool: 'list_pending_migrations', tier: 'read',     requires_confirmation: false, affects_production: false, description: 'List migration files' },
  { tool: 'ask_question',            tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Answer a question' },
  { tool: 'repo_commits',            tier: 'read',     requires_confirmation: false, affects_production: false, description: 'View git commits' },
  { tool: 'export_catalog',          tier: 'read',     requires_confirmation: false, affects_production: false, description: 'Export program catalog' },
  // Developer tier — code/data inspection
  { tool: 'scan_routes',             tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Scan Next.js routes' },
  { tool: 'query_database',          tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Query Supabase DB (read-only)' },
  { tool: 'audit_system',            tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Run system audit' },
  { tool: 'inspect_links',           tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Inspect broken links' },
  { tool: 'audit_enrollment_pipeline', tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Audit enrollment pipeline' },
  { tool: 'verify_program_integrity', tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Verify program data integrity' },
  { tool: 'inspect_student_access',  tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Inspect student access' },
  { tool: 'smoke_test',              tier: 'developer', requires_confirmation: false, affects_production: false, description: 'Run smoke tests' },
  // Operator tier — side effects but non-destructive
  { tool: 'send_reminder',           tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Send reminder email' },
  { tool: 'send_email',              tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Send email' },
  { tool: 'send_bulk_email',         tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Send bulk email' },
  { tool: 'send_test_email',         tier: 'operator', requires_confirmation: false, affects_production: false, description: 'Send test email' },
  { tool: 'flag_at_risk',            tier: 'operator', requires_confirmation: false, affects_production: true,  description: 'Flag student at-risk' },
  { tool: 'approve_application',     tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Approve application' },
  { tool: 'enroll_student',          tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Enroll student' },
  { tool: 'save_memory',             tier: 'operator', requires_confirmation: false, affects_production: false, description: 'Save operational memory' },
  { tool: 'send_document_for_sign',  tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Send document for signature' },
  { tool: 'mark_payout_paid',        tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Mark payout paid' },
  { tool: 'update_user_role',        tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Update user role' },
  { tool: 'issue_certificate',       tier: 'operator', requires_confirmation: true,  affects_production: true,  description: 'Issue certificate' },
  // Deployer tier — affects production systems
  { tool: 'run_migration',                tier: 'deployer', requires_confirmation: true,  affects_production: true,  description: 'Apply a single DB migration' },
  { tool: 'apply_all_pending_migrations', tier: 'deployer', requires_confirmation: true,  affects_production: true,  description: 'Apply all pending DB migrations' },
  { tool: 'deploy_autopilot',        tier: 'deployer', requires_confirmation: true,  affects_production: true,  description: 'Trigger deployment' },
  { tool: 'build_courses',           tier: 'deployer', requires_confirmation: true,  affects_production: true,  description: 'Build course content' },
  { tool: 'run_tests',               tier: 'deployer', requires_confirmation: false, affects_production: false, description: 'Run test suite' },
  { tool: 'run_backup',              tier: 'deployer', requires_confirmation: false, affects_production: false, description: 'Trigger backup' },
  { tool: 'run_automation',          tier: 'deployer', requires_confirmation: true,  affects_production: true,  description: 'Run automation workflow' },
  { tool: 'generate_course',         tier: 'deployer', requires_confirmation: true,  affects_production: true,  description: 'Generate course content' },
];

export function getToolPermission(tool: string): AiToolPermission | undefined {
  return AI_TOOL_PERMISSIONS.find(p => p.tool === tool);
}

export function getToolsByTier(tier: AiPermissionTier): AiToolPermission[] {
  return AI_TOOL_PERMISSIONS.filter(p => p.tier === tier);
}

export function requiresConfirmation(tool: string): boolean {
  return getToolPermission(tool)?.requires_confirmation ?? false;
}

// ── System Registry summary for AI context ───────────────────────────────────

export function getSystemRegistryContext(): string {
  const active = getActivePrograms();
  const byCategory = {
    healthcare: active.filter(p => p.category === 'healthcare'),
    trades: active.filter(p => p.category === 'trades'),
    apprenticeship: active.filter(p => p.category === 'apprenticeship'),
    business: active.filter(p => p.category === 'business'),
    technology: active.filter(p => p.category === 'technology'),
    special: active.filter(p => p.category === 'special'),
    hospitality: active.filter(p => p.category === 'hospitality'),
    beauty: active.filter(p => p.category === 'beauty'),
  };

  const lines = [
    '=== PROGRAM REGISTRY ===',
    `Total active programs: ${active.length}`,
    '',
    ...Object.entries(byCategory).map(([cat, progs]) =>
      `${cat.toUpperCase()} (${progs.length}):\n${progs.map(p =>
        `  ${p.slug} → ${p.canonical_route} | apply: ${p.apply_route} | funding: ${p.funding.join(', ')}`
      ).join('\n')}`
    ),
    '',
    '=== AI PERMISSION TIERS ===',
    'read: query-only, no side effects',
    'developer: code/data inspection, no writes',
    'operator: emails, flags, approvals (requires confirmation for production writes)',
    'deployer: migrations, deployments, builds (always requires confirmation)',
    'super: destructive operations (not available via AI console)',
  ];

  return lines.join('\n');
}
