/**
 * COMPLETE Program Data - All 15 ETPL Programs
 * Extracted from supabase/migrations/20241115_add_all_etpl_programs.sql
 * This is the authoritative source for all program information
 */

export interface ProgramData {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  summary: string;
  bullets: string[];
  funding: string[];
  duration: string;
  image: string;
  etplApproved: boolean;
  partnerName?: string;
  partnerUrl?: string;
  partnerLoginUrl?: string;
  certificateUploadEnabled?: boolean;
  cipCode?: string;
  socCode?: string;
}

export const COMPLETE_PROGRAMS: ProgramData[] = [
  {
    slug: 'business-startup-marketing',
    name: 'Business Start-Up & Marketing Program',
    tagline: 'Launch your own business with Rise Forward',
    description: 'The Business Start-Up & Marketing Program with Rise Forward equips participants with hands-on skills to launch their own business ventures. Students will learn the fundamentals of entrepreneurship, digital marketing, LLC formation, business planning, customer service, and resume development. The program includes guided startup support, mentorship, and ends with a business match stipend and laptop kit to empower real-world implementation. Ideal for youth ready to explore self-employment and leadership pathways in today\'s economy.',
    summary: 'Learn entrepreneurship, digital marketing, LLC formation, and business planning with mentorship and startup support.',
    bullets: [
      '5-week accelerated program',
      '32 instructional hours (8 hours/week)',
      'LLC formation and business planning',
      'Digital marketing and customer service',
      'Business match stipend + laptop kit',
      'Resume development and professional branding',
      '100% online, flexible schedule',
      'Open to youth ages 16+'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '5 Weeks • 32 Hours',
    image: '/images/pages/training-classroom.jpg',
    etplApproved: true,
  },
  {
    slug: 'emergency-health-safety-tech',
    name: 'Emergency Health & Safety Technician',
    tagline: 'Life-saving skills through DOL Federally Registered Apprenticeship',
    description: 'The Emergency Health & Safety Technician is a DOL Federally Registered Apprenticeship that prepares individuals for life-saving response roles in schools, workplaces and emergency settings. This hybrid (time-based and competency-based) apprenticeship includes CPR, OSHA 10, and Emergency Medical Responder (EMR) training. Students graduate with nationally recognized certifications and are equipped for careers in healthcare, public safety, community response, and entry-level emergency technician pathways.',
    summary: 'Earn OSHA 10, CPR, and EMR certifications in 4-week DOL Registered Apprenticeship.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      'Hybrid: Time-based and Competency-based',
      '4-week program (4 weeks RTI)',
      '80 instructional hours (20 hours/week)',
      'Earn OSHA 10 - Career Safe certification',
      'Earn CPR certification',
      'Earn Emergency Medical Responder (EMR) certification',
      'Public health emergency awareness',
      'High school diploma or GED required',
      'Day, evening, weekend, and online options'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '4 Weeks • 80 Hours',
    image: '/images/pages/comp-pathway-healthcare.jpg',
    etplApproved: true,
  },
  {
    slug: 'hvac-technician',
    name: 'HVAC Technician',
    tagline: 'DOL Federally Registered Apprenticeship in HVAC',
    description: 'The HVAC Technician program is a DOL Federally Registered Apprenticeship that provides comprehensive training in heating, ventilation, air conditioning, and refrigeration systems. This hybrid (time-based and competency-based) apprenticeship includes 50 weeks of Related Technical Instruction combined with on-the-job training. Students earn multiple industry-recognized certifications including CPR, Rise Up Credential, OSHA 30, and two Residential HVAC Certifications.',
    summary: 'Earn 5 certifications in DOL Registered HVAC Apprenticeship with 10 active apprentices.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      '50 weeks of Related Technical Instruction (RTI)',
      '125 instructional hours (12 hours/week)',
      'Currently 10 active apprentices',
      'Earn CPR certification',
      'Earn Rise Up Credential',
      'Earn OSHA 30 certification',
      'Earn Residential HVAC Certification 1',
      'Earn Residential HVAC Certification 2 - Refrigeration Diagnostics',
      'No prerequisites'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '50 Weeks • 125 Hours RTI',
    image: '/images/pages/hvac-technician.jpg',
    etplApproved: true,
  },
  {
    slug: 'direct-support-professional',
    name: 'Direct Support Professional (DSP)',
    tagline: 'Compassionate care for individuals with developmental needs',
    description: 'Our Direct Support Professional (DSP) training program is built to prepare compassionate individuals for meaningful work in the care and support field. This program offers hands-on instruction, real-world scenarios, and practical skills that help students feel confident working with individuals who have developmental, physical, or emotional needs.',
    summary: 'Prepare for a rewarding career supporting individuals with developmental, physical, or emotional needs.',
    bullets: [
      'Rolling enrollment - start anytime',
      'Cohorts begin 1st and 15th of each month',
      'Hands-on instruction and real-world scenarios',
      'No prior healthcare experience required',
      'Must be 18+ with high school diploma or GED',
      'Background check required',
      'Job placement assistance included',
      'CDSP, CNA, or QIDP pathway'
    ],
    funding: ['WIOA', 'WRG'],
    duration: 'Rolling Enrollment',
    image: '/images/pages/admin-counseling-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'professional-esthetician',
    name: 'Professional Esthetician & Client Services',
    tagline: 'Job-ready skincare and spa skills through DOL Federally Registered Apprenticeship',
    description: 'The Esthetics and Skincare Specialist Certificate Program is a DOL Federally Registered Apprenticeship that prepares individuals to enter the high-demand personal care industry with job-ready skills in skin analysis, facial treatments, hair removal, sanitation, customer service, and product knowledge. This RAPIDS-verified program offers traditional wrap around support including career readiness, business startup training, wellness coaching and access to employer networks.',
    summary: 'Master skincare, facial treatments, and client services in 5 weeks through DOL Registered Apprenticeship.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      '5-week program (4 weeks RTI)',
      '60 instructional hours (15 hours/week)',
      'Currently 3 active apprentices',
      'Earn OSHA 10 - Career Safe certification',
      'Customer Service and Sales Certified Specialist',
      'Business of Retail Certified Specialist',
      'Skin analysis and facial treatments',
      'Career readiness and business startup training',
      'No prerequisites - all ages welcome'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '5 Weeks • 60 Hours',
    image: '/images/pages/barber-gallery-2.jpg',
    etplApproved: true,
  },
  {
    slug: 'tax-prep-financial-services',
    name: 'Tax Preparation & Financial Services Certificate',
    tagline: 'State-Approved Earn and Learn Program with IRS VITA/TCE certification',
    description: 'The Tax Preparation & Financial Services Certificate is a State-Approved Earn and Learn Program (approved 2025-10-01) that prepares individuals to understand federal and state taxation concepts and apply them in real-world settings. Students earn QuickBooks Pro Advisor and Microsoft 365 Fundamentals certifications, plus the Rise Up Credential. Graduates gain the skills required for employment as Tax Preparers, Bookkeeping Assistants, and Financial Service Specialists.',
    summary: 'Earn IRS VITA/TCE, QuickBooks, Microsoft 365, and Rise Up certifications in State-Approved Earn and Learn Program.',
    bullets: [
      'State-Approved Earn and Learn Program (approved 2025-10-01)',
      '10-week comprehensive program',
      '150 instructional hours (15 hours/week)',
      'Earn QuickBooks Pro Advisor certification',
      'Earn Microsoft 365 Fundamentals certification',
      'Earn Rise Up Credential',
      'IRS VITA/TCE certification included',
      'Federal and state tax law training',
      'Supervised practicum at IRS-approved VITA site',
      'High school diploma or GED required'
    ],
    funding: ['WIOA', 'WRG', 'Earn and Learn'],
    duration: '10 Weeks • 150 Hours',
    image: '/images/pages/supersonic-tax-prep.jpg',
    etplApproved: true,
  },
  {
    slug: 'public-safety-reentry-specialist',
    name: 'Public Safety Reentry Specialist Program',
    tagline: 'Career pathways for justice-involved individuals',
    description: 'This program directly supports the critical shortage in Indiana\'s behavioral health, reentry, and public safety workforce by training Peer Recovery Specialists with a trauma-informed lens. Aligned with O*NET Code 21-1093.00 (Social and Human Service Assistants), this certification-based program prepares justice-impacted individuals and others to provide frontline recovery, crisis response, and peer coaching services.',
    summary: 'Trauma-informed Peer Recovery Specialist training for justice-impacted individuals and reentry professionals.',
    bullets: [
      '45-day intensive program',
      '180 instructional hours (15 hours/week)',
      'O*NET 21-1093.00 - Social and Human Service Assistants',
      'Certified Peer Recovery Specialist (CPRS) pathway',
      'Trauma-informed coaching and mentorship',
      'Crisis response and peer navigation',
      'No prior credential required',
      '100% online with tutoring support',
      '100% acceptance rate for eligible applicants'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '45 Days • 180 Hours',
    image: '/images/pages/career-counseling.jpg',
    etplApproved: true,
  },
  {
    slug: 'barber-apprenticeship',
    name: 'Barber Apprenticeship Program',
    tagline: 'Master barbering through DOL Federally Registered Apprenticeship',
    description: 'The Barber Apprenticeship Program is a comprehensive 2,000-hour DOL Federally Registered Apprenticeship that combines 12 weeks of instructional training with extensive on-the-job training. Students learn cutting, styling, shaving, sanitation, and business skills in a real barbershop environment. This RAPIDS-verified apprenticeship prepares participants for Indiana Registered Barber License.',
    summary: 'Earn while you learn in a 2,000-hour DOL Federally Registered Apprenticeship.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      '2,000-hour comprehensive program',
      '12 weeks instructional training',
      'On-the-job training in real barbershops',
      'Learn cutting, styling, shaving, sanitation',
      'Business skills and shop management',
      'RAPIDS-verified apprenticeship',
      'Pathway to Indiana Registered Barber License',
      'Earn while you learn',
      'Shop ownership pathway'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '2,000 Hours • 12 Weeks + OJT',
    image: '/images/pages/barber-gallery-1.jpg',
    etplApproved: true,
  },
  {
    slug: 'beauty-career-educator',
    name: 'Beauty & Career Educator Training Program',
    tagline: 'Develop career-ready, technical, and leadership skills in beauty education',
    description: 'The Beauty & Career Educator Training Program is a 12-week hybrid training experience designed to help aspiring beauty professionals and peer educators develop career-ready, technical, and leadership skills. Participants earn a nationally recognized Rise Up Credential, a Career Readiness Certificate, and a custom Certificate of Completion. Designed for youth and adults ages 16+.',
    summary: 'Earn Rise Up Credential + Career Readiness Certificate in 12 weeks.',
    bullets: [
      '12-week hybrid training program',
      'Practical salon service education',
      'Manicuring techniques and customer service',
      'Sanitation and infection control',
      'Peer teaching and community workshops',
      'Entrepreneurship and workforce readiness',
      'Rise Up Credential (nationally recognized)',
      'Career Readiness Certificate',
      'Ages 16+ welcome',
      'CIP Code 13.1326 eligible'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '12 Weeks',
    image: '/images/pages/training-classroom.jpg',
    etplApproved: true,
  },
  {
    slug: 'certified-peer-support-professional',
    name: 'Certified Peer Support Professional',
    tagline: 'Support others through lived experience',
    description: 'The Certified Peer Support Professional program trains individuals with lived experience in mental health or substance use recovery to provide peer support services. This certification is recognized by behavioral health agencies, hospitals, and community organizations. Participants learn recovery principles, ethical boundaries, trauma-informed care, and advocacy skills.',
    summary: 'Become a certified peer support professional and help others in recovery.',
    bullets: [
      'Certification for lived experience professionals',
      'Mental health and substance use recovery focus',
      'Recognized by behavioral health agencies',
      'Recovery principles and ethical boundaries',
      'Trauma-informed care training',
      'Advocacy skills development',
      'Hospital and community organization placement',
      'No prior healthcare degree required',
      'Lived experience valued',
      'Career pathway in behavioral health'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '6-8 Weeks',
    image: '/images/pages/admin-counseling-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'certified-peer-recovery-coach',
    name: 'Certified Peer Recovery Coach (CPRC)',
    tagline: 'Guide others on their recovery journey',
    description: 'The Certified Peer Recovery Coach (CPRC) credential prepares individuals to provide recovery coaching services in substance use and mental health settings. This certification is recognized nationally and qualifies graduates to work in treatment centers, recovery housing, hospitals, and community programs. Training covers motivational interviewing, recovery capital, relapse prevention, and ethical practice.',
    summary: 'Earn your CPRC credential and make a difference in recovery services.',
    bullets: [
      'Nationally recognized CPRC credential',
      'Recovery coaching for substance use and mental health',
      'Motivational interviewing techniques',
      'Recovery capital assessment',
      'Relapse prevention strategies',
      'Ethical practice and boundaries',
      'Treatment center placement',
      'Recovery housing opportunities',
      'Hospital and community program roles',
      'Justice-involved individuals welcome'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '45 Days • 180 Hours',
    image: '/images/pages/comp-home-pathways-support.jpg',
    etplApproved: true,
  },
  {
    slug: 'cpr-certification',
    name: 'CPR Certification',
    tagline: 'Life-saving skills in one day',
    description: 'CPR Certification provides essential life-saving skills through American Heart Association or Red Cross training. This standalone certification is required for many healthcare, childcare, fitness, and public safety positions. Participants learn adult, child, and infant CPR, AED use, and choking relief. Certification is valid for 2 years.',
    summary: 'Get CPR/AED certified in one day.',
    bullets: [
      'American Heart Association or Red Cross certified',
      'Adult, child, and infant CPR',
      'AED (Automated External Defibrillator) use',
      'Choking relief techniques',
      'Required for healthcare positions',
      'Childcare and fitness industry requirement',
      'Public safety certification',
      '2-year certification validity',
      'One-day training',
      'Recertification available'
    ],
    funding: ['Self-Pay', 'Employer Sponsored'],
    duration: '1 Day • 4-8 Hours',
    image: '/images/pages/comp-pathway-healthcare.jpg',
    etplApproved: false,
  },
  {
    slug: 'certified-community-healthcare-worker',
    name: 'Certified Community Healthcare Worker (CCHW)',
    tagline: 'Bridge healthcare gaps in your community',
    description: 'The Certified Community Healthcare Worker (CCHW) program trains individuals to serve as liaisons between healthcare providers and communities. CHWs help patients navigate the healthcare system, provide health education, connect people to resources, and advocate for community health needs. This certification is increasingly recognized by hospitals, clinics, and public health departments.',
    summary: 'Become a certified community healthcare worker and improve health outcomes.',
    bullets: [
      'Liaison between healthcare providers and communities',
      'Healthcare system navigation support',
      'Health education and outreach',
      'Resource connection and referrals',
      'Community health advocacy',
      'Hospital and clinic placement',
      'Public health department opportunities',
      'Cultural competency training',
      'No prior healthcare degree required',
      'Community-focused career pathway'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '8-12 Weeks',
    image: '/images/pages/admin-health-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'rise-up-certificate',
    name: 'Rise Up Certificate',
    tagline: 'Foundational skills for career success with Job Ready Indy',
    description: 'The Rise Up Certificate program provides foundational skills for individuals entering or re-entering the workforce. This program covers digital literacy, professional communication, workplace readiness, financial literacy, and personal wellness. Students also complete the Job Ready Indy (JRI) 6-badge series through EmployIndy, earning a nationally recognized workforce readiness credential.',
    summary: 'Build foundational skills and earn Job Ready Indy credential.',
    bullets: [
      'Foundational workforce readiness skills',
      'Digital literacy training',
      'Professional communication',
      'Workplace readiness preparation',
      'Financial literacy education',
      'Personal wellness and self-care',
      'Includes Job Ready Indy (JRI) 6-badge series',
      'Nationally recognized credential',
      'EmployIndy JRI Facilitator: Elevate for Humanity',
      'Pathway to further training or employment'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '4-6 Weeks',
    image: '/images/pages/healthcare-grad.jpg',
    etplApproved: true,
  },
  {
    slug: 'osha-10-certification',
    name: 'OSHA 10 Certification',
    tagline: 'Essential workplace safety training',
    description: 'OSHA 10-Hour General Industry certification provides foundational knowledge of workplace safety and health hazards. This certification is required or preferred for many construction, manufacturing, healthcare, and service industry positions. Participants learn hazard recognition, fall protection, electrical safety, personal protective equipment (PPE), and emergency response. The certification is valid and recognized nationwide.',
    summary: 'Get OSHA 10 certified and meet employer safety requirements.',
    bullets: [
      'OSHA 10-Hour General Industry certification',
      'Workplace safety and health hazards',
      'Hazard recognition and prevention',
      'Fall protection and electrical safety',
      'Personal protective equipment (PPE)',
      'Emergency response procedures',
      'Required for many industry positions',
      'Nationally recognized certification',
      'Valid for career advancement',
      'Included in Beauty & Career Educator program'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '10 Hours • 2 Days',
    image: '/images/pages/hvac-technician.jpg',
    etplApproved: true,
  },
  {
    slug: 'cna-certification',
    name: 'Certified Nursing Assistant (CNA)',
    tagline: 'Start your healthcare career in 4-6 weeks',
    description: 'The Certified Nursing Assistant (CNA) program prepares students for entry-level positions in healthcare facilities. This comprehensive training includes classroom instruction, hands-on lab practice, and clinical experience in real healthcare settings. Students learn patient care, vital signs, infection control, and communication skills. Upon completion, graduates are eligible to take the state certification exam.',
    summary: 'Become a Certified Nursing Assistant with hands-on training and clinical experience in 4-6 weeks.',
    bullets: [
      '4-6 week accelerated program',
      '120+ hours of instruction',
      'Hands-on lab practice',
      'Clinical experience in healthcare facilities',
      'State certification exam preparation',
      'Patient care and vital signs training',
      'Infection control and safety protocols',
      'High school diploma or GED required',
      'Background check and drug screening required',
      'Day and evening classes available'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '4-6 Weeks • 120+ Hours',
    image: '/images/pages/comp-pathway-healthcare.jpg',
    etplApproved: true,
  },
  {
    slug: 'building-maintenance-tech',
    name: 'Building Maintenance Technician',
    tagline: 'Essential skills for property maintenance careers',
    description: 'The Building Maintenance Technician program provides comprehensive training in property maintenance, repair, and facility operations. Students learn electrical basics, plumbing, HVAC fundamentals, carpentry, painting, and general building systems. This program prepares graduates for positions in apartment complexes, commercial buildings, schools, and property management companies.',
    summary: 'Learn essential maintenance skills for careers in property management and facility operations.',
    bullets: [
      '6-8 week comprehensive program',
      'Electrical and plumbing basics',
      'HVAC fundamentals',
      'Carpentry and painting skills',
      'Building systems and safety',
      'Preventive maintenance procedures',
      'Tool safety and usage',
      'OSHA 10 certification included',
      'Hands-on training in real facilities',
      'Job placement assistance'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '6-8 Weeks • 160 Hours',
    image: '/images/pages/comp-highlights-electrical.jpg',
    etplApproved: true,
  },
  {
    slug: 'cdl-training',
    name: 'Commercial Driver\'s License (CDL) Training',
    tagline: 'Launch your trucking career with Class A CDL',
    description: 'Our CDL Training program prepares students for careers in commercial trucking. This comprehensive program includes classroom instruction on DOT regulations, vehicle inspection, and safety, plus extensive behind-the-wheel training. Students learn to operate tractor-trailers, perform pre-trip inspections, and master backing maneuvers. Graduates are prepared to pass the CDL Class A exam and begin earning immediately.',
    summary: 'Get your Class A CDL and start a high-paying trucking career in 4-6 weeks.',
    bullets: [
      '4-6 week intensive program',
      'Class A CDL training',
      'DOT regulations and safety',
      'Pre-trip inspection training',
      'Behind-the-wheel instruction',
      'Backing and maneuvering practice',
      'Road test preparation',
      'Valid driver\'s license required',
      'Must pass DOT physical',
      'Job placement assistance with carriers'
    ],
    funding: ['WIOA', 'WRG', 'Carrier Sponsorship'],
    duration: '4-6 Weeks • 160+ Hours',
    image: '/images/pages/training-classroom.jpg',
    etplApproved: true,
  },
  {
    slug: 'customer-service-retail-nrf',
    name: 'Customer Service & Retail (NRF RISE Up)',
    tagline: 'Build essential retail and customer service skills',
    description: 'The NRF RISE Up Customer Service & Retail program provides foundational training for careers in retail, hospitality, and customer-facing roles. Developed by the National Retail Federation, this program covers customer engagement, sales techniques, inventory management, point-of-sale systems, and workplace professionalism. Students earn a nationally recognized credential valued by employers across industries.',
    summary: 'Earn NRF RISE Up credential with essential skills for retail and customer service careers.',
    bullets: [
      '40-60 hours of online training',
      'Self-paced learning modules',
      'Customer engagement skills',
      'Sales and service techniques',
      'Inventory and merchandising',
      'Point-of-sale operations',
      'Workplace professionalism',
      'NRF RISE Up credential',
      'Nationally recognized certification',
      'No prerequisites required'
    ],
    funding: ['WIOA', 'WRG', 'Free through partnership'],
    duration: '4-6 Weeks • 40-60 Hours',
    image: '/images/pages/healthcare-grad.jpg',
    etplApproved: true,
    partnerName: 'NRF Foundation',
    partnerUrl: 'https://riseup.nrf.com',
    partnerLoginUrl: 'https://riseup.kaleidolearning.com',
    certificateUploadEnabled: true,
    cipCode: '52.1801',
    socCode: '41-2031.00',
  },
  {
    slug: 'microsoft-office-mos',
    name: 'Microsoft Office Specialist (MOS)',
    tagline: 'Master Microsoft Office and earn industry certification',
    description: 'The Microsoft Office Specialist (MOS) program provides comprehensive training in Microsoft Word, Excel, PowerPoint, and Outlook. Students learn essential business software skills through hands-on practice and real-world projects. Upon completion, students are prepared to take MOS certification exams, earning credentials recognized by employers worldwide. This program is essential for administrative, office, and business support roles.',
    summary: 'Earn Microsoft Office Specialist certifications in Word, Excel, PowerPoint, and Outlook.',
    bullets: [
      '6-8 week program',
      'Microsoft Word certification prep',
      'Microsoft Excel certification prep',
      'Microsoft PowerPoint training',
      'Microsoft Outlook essentials',
      'Hands-on projects and practice',
      'MOS certification exams included',
      'Globally recognized credentials',
      'Essential for office careers',
      'Online and in-person options'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '6-8 Weeks • 80 Hours',
    image: '/images/pages/admin-business-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'cpr-first-aid-hsi',
    name: 'CPR & First Aid (HSI)',
    tagline: 'Life-saving skills for healthcare and safety careers',
    description: 'The CPR & First Aid program through Health & Safety Institute (HSI) provides essential emergency response training. Students learn CPR for adults, children, and infants, AED operation, choking relief, and basic first aid. This certification is required for many healthcare, childcare, and safety positions. The course includes hands-on practice with manikins and AED trainers.',
    summary: 'Earn HSI CPR and First Aid certifications required for healthcare and safety careers.',
    bullets: [
      '1-day intensive training',
      '4-8 hours of instruction',
      'Adult, child, and infant CPR',
      'AED operation and training',
      'Choking relief techniques',
      'Basic first aid skills',
      'Hands-on practice with equipment',
      'HSI certification cards',
      'Valid for 2 years',
      'Required for many healthcare jobs'
    ],
    funding: ['WIOA', 'WRG', 'Employer Sponsored'],
    duration: '1 Day • 4-8 Hours',
    image: '/images/pages/comp-pathway-healthcare.jpg',
    etplApproved: true,
    partnerName: 'Health & Safety Institute (HSI)',
    partnerUrl: 'https://hsi.com',
    partnerLoginUrl: 'https://hsi.com/solutions/cpr-aed-first-aid-training/elevate-for-humanity-career-training-org-nts-class-sign-up',
    certificateUploadEnabled: true,
    cipCode: '51.0904',
    socCode: '29-2099.00',
  },
  {
    slug: 'osha-30-careersafe',
    name: 'OSHA 30-Hour (CareerSafe)',
    tagline: 'Advanced workplace safety certification',
    description: 'The OSHA 30-Hour Safety Training through CareerSafe provides comprehensive workplace safety education for supervisors and workers in construction or general industry. This DOL-authorized program covers hazard recognition, accident prevention, safety regulations, and emergency response. Students earn an OSHA 30-Hour card upon completion, demonstrating advanced safety knowledge valued by employers.',
    summary: 'Earn OSHA 30-Hour certification for advanced workplace safety and supervisory roles.',
    bullets: [
      '30 hours of online training',
      'Self-paced learning',
      'Construction or General Industry track',
      'Hazard recognition and prevention',
      'OSHA regulations and compliance',
      'Emergency response procedures',
      'Safety management principles',
      'DOL-authorized CareerSafe training',
      'OSHA 30-Hour card upon completion',
      'Required for many supervisory positions'
    ],
    funding: ['WIOA', 'WRG', 'Employer Sponsored'],
    duration: '30 Hours • 1-2 Weeks',
    image: '/images/pages/hvac-technician.jpg',
    etplApproved: true,
    partnerName: 'CareerSafe',
    partnerUrl: 'https://careersafeonline.com',
    certificateUploadEnabled: true,
    cipCode: '46.0408',
    socCode: '29-9011.00',
  },
  {
    slug: 'cybersecurity-analyst',
    name: 'Cybersecurity Analyst',
    tagline: 'Launch your career in cybersecurity',
    description: 'The Cybersecurity Fundamentals program provides entry-level training in information security, network defense, and cyber threat awareness. Students learn security principles, risk management, encryption, firewalls, and incident response. This program prepares graduates for entry-level cybersecurity positions and provides a foundation for advanced certifications like Certiport IT Specialist — Cybersecurity.',
    summary: 'Build foundational cybersecurity skills for entry-level IT security careers.',
    bullets: [
      '8-12 week program',
      'Information security principles',
      'Network security fundamentals',
      'Threat detection and response',
      'Encryption and cryptography basics',
      'Firewall and VPN configuration',
      'Security policies and compliance',
      'Hands-on lab exercises',
      'Certiport IT Specialist — Cybersecurity exam prep',
      'Career coaching and job placement'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '8-12 Weeks • 120 Hours',
    image: '/images/pages/admin-network-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'it-help-desk',
    name: 'IT Help Desk Technician',
    tagline: 'Start your IT career with hands-on training',
    description: 'The IT Support Specialist program prepares students for entry-level positions in technical support and help desk roles. Training covers computer hardware, operating systems, networking basics, troubleshooting, and customer service. Students gain hands-on experience with real equipment and scenarios. Graduates are prepared for Certiport IT Specialist certification and immediate employment in IT support.',
    summary: 'Become an IT Support Specialist with Certiport IT Specialist certification preparation.',
    bullets: [
      '8-12 week comprehensive program',
      'Computer hardware and software',
      'Windows and operating systems',
      'Networking fundamentals',
      'Troubleshooting techniques',
      'Help desk and customer service',
      'Mobile device support',
      'Certiport IT Specialist exam preparation',
      'Hands-on lab practice',
      'Job placement assistance'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '8-12 Weeks • 120 Hours',
    image: '/images/pages/training-classroom.jpg',
    etplApproved: true,
  },
  {
    slug: 'medical-administrative-assistant',
    name: 'Medical Administrative Assistant',
    tagline: 'Essential skills for healthcare office careers',
    description: 'The Medical Administrative Assistant program trains students for front-office positions in healthcare facilities. Curriculum includes medical terminology, insurance billing, electronic health records, appointment scheduling, and patient communication. Students learn HIPAA compliance, medical coding basics, and office software. Graduates are prepared for positions in hospitals, clinics, and medical offices.',
    summary: 'Prepare for medical office careers with training in billing, coding, and healthcare administration.',
    bullets: [
      '8-10 week program',
      'Medical terminology',
      'Insurance billing and coding',
      'Electronic health records (EHR)',
      'Appointment scheduling',
      'Patient communication',
      'HIPAA compliance',
      'Medical office software',
      'Customer service in healthcare',
      'Externship opportunities available'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '8-10 Weeks • 120 Hours',
    image: '/images/pages/admin-health-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'patient-care-technician',
    name: 'Patient Care Technician',
    tagline: 'Advanced patient care skills for hospital careers',
    description: 'The Patient Care Technician program combines CNA skills with additional training in EKG, phlebotomy, and vital signs monitoring. This comprehensive program prepares students for hospital-based patient care roles. Training includes hands-on practice in labs and clinical settings. Graduates can work in hospitals, long-term care facilities, and specialty clinics with expanded responsibilities.',
    summary: 'Combine CNA, EKG, and phlebotomy skills for advanced patient care positions.',
    bullets: [
      '8-12 week comprehensive program',
      'CNA skills and certification',
      'EKG technician training',
      'Phlebotomy basics',
      'Vital signs monitoring',
      'Patient mobility and transfers',
      'Medical terminology',
      'Clinical experience in hospitals',
      'Multiple certifications earned',
      'Higher pay than standard CNA'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '8-12 Weeks • 200+ Hours',
    image: '/images/pages/comp-pathway-healthcare.jpg',
    etplApproved: true,
  },
  {
    slug: 'dental-assistant',
    name: 'Dental Assistant',
    tagline: 'Start your dental career in weeks',
    description: 'The Dental Assistant program prepares students for chairside assisting positions in dental offices. Training covers dental terminology, instrument identification, infection control, patient care, X-ray safety, and office procedures. Students gain hands-on experience in simulated dental settings. Graduates are prepared for entry-level positions and can pursue additional certifications like Radiology and Expanded Functions.',
    summary: 'Become a Dental Assistant with hands-on training in chairside procedures and patient care.',
    bullets: [
      '8-12 week program',
      'Chairside assisting techniques',
      'Dental terminology and anatomy',
      'Infection control and sterilization',
      'Dental instruments and materials',
      'X-ray safety (Radiology certification available)',
      'Patient communication',
      'Dental office procedures',
      'Hands-on lab practice',
      'Externship in dental offices'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '8-12 Weeks • 150 Hours',
    image: '/images/pages/admin-health-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'pharmacy-technician',
    name: 'Pharmacy Technician',
    tagline: 'Prepare for national certification in pharmacy',
    description: 'The Pharmacy Technician program trains students to assist pharmacists in retail and hospital pharmacies. Curriculum includes pharmaceutical calculations, drug classifications, prescription processing, inventory management, and pharmacy law. Students learn to use pharmacy software and prepare medications under supervision. Graduates are prepared for the PTCB national certification exam.',
    summary: 'Become a certified Pharmacy Technician with training in prescription processing and pharmacy operations.',
    bullets: [
      '12-16 week comprehensive program',
      'Pharmaceutical calculations',
      'Drug classifications and interactions',
      'Prescription processing',
      'Pharmacy software systems',
      'Inventory and ordering',
      'Pharmacy law and ethics',
      'Sterile compounding basics',
      'PTCB exam preparation',
      'Externship in retail or hospital pharmacy'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '12-16 Weeks • 200 Hours',
    image: '/images/pages/comp-pathway-healthcare.jpg',
    etplApproved: true,
  },
  {
    slug: 'phlebotomy-technician',
    name: 'Phlebotomy Technician',
    tagline: 'Master blood collection techniques in weeks',
    description: 'The Phlebotomy Technician program trains students in venipuncture, capillary puncture, and specimen processing. This hands-on program includes extensive practice on training arms and live draws under supervision. Students learn infection control, patient interaction, and laboratory safety. Graduates are prepared for national certification and employment in hospitals, labs, and blood donation centers.',
    summary: 'Earn phlebotomy certification with hands-on training in blood collection and specimen processing.',
    bullets: [
      '4-8 week intensive program',
      '80-120 hours of training',
      'Venipuncture techniques',
      'Capillary puncture methods',
      'Specimen collection and processing',
      'Infection control and safety',
      'Patient interaction skills',
      'Hands-on practice with training equipment',
      'Clinical externship with live draws',
      'National certification exam preparation'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '4-8 Weeks • 80-120 Hours',
    image: '/images/pages/comp-highlights-team.jpg',
    etplApproved: true,
  },
  {
    slug: 'entrepreneurship-business',
    name: 'Entrepreneurship & Small Business',
    tagline: 'Turn your business idea into reality',
    description: 'The Entrepreneurship & Small Business program guides aspiring entrepreneurs through the process of starting and running a successful business. Training covers business planning, financial management, marketing strategies, legal structures, and operations. Students develop a complete business plan and learn to access funding, manage cash flow, and build a customer base. Ideal for those ready to be their own boss.',
    summary: 'Launch your own business with comprehensive training in planning, marketing, and operations.',
    bullets: [
      '8-12 week program',
      'Business plan development',
      'Financial management and budgeting',
      'Marketing and social media strategies',
      'Legal structures (LLC, sole proprietorship)',
      'Funding and financing options',
      'Customer acquisition and retention',
      'Operations and inventory management',
      'Mentorship from successful entrepreneurs',
      'Pitch competition and startup funding opportunities'
    ],
    funding: ['WIOA', 'WRG', 'Small Business Grants'],
    duration: '8-12 Weeks • 100 Hours',
    image: '/images/pages/admin-startup-hero.jpg',
    etplApproved: true,
  },
  {
    slug: 'hospitality-culinary',
    name: 'Hospitality & Culinary Arts',
    tagline: 'Launch your career in food service and hospitality',
    description: 'The Hospitality & Culinary Arts program prepares students for careers in restaurants, hotels, catering, and food service management. Training includes food preparation, kitchen safety, sanitation, customer service, and hospitality operations. Students learn culinary techniques, menu planning, and front-of-house service. Graduates earn food handler and ServSafe certifications and are prepared for positions from line cook to restaurant management.',
    summary: 'Master culinary skills and hospitality operations for careers in food service and restaurants.',
    bullets: [
      '12-16 week comprehensive program',
      'Culinary techniques and knife skills',
      'Food safety and sanitation',
      'Kitchen operations and equipment',
      'Menu planning and costing',
      'Customer service excellence',
      'Front-of-house operations',
      'ServSafe Manager certification',
      'Hands-on cooking labs',
      'Externship in restaurants or hotels'
    ],
    funding: ['WIOA', 'WRG', 'Pell Grant'],
    duration: '12-16 Weeks • 200 Hours',
    image: '/images/pages/admin-cafeteria-hero.jpg',
    etplApproved: true,
  },
];
