#!/usr/bin/env bash
# .devcontainer/setup-env.sh
#
# Populates .env.local from AWS SSM Parameter Store (/elevate/* path).
#
# Required env vars (set in your shell or pass inline):
#   AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY
#   AWS_DEFAULT_REGION   (default: us-east-1)
#
# Falls back to .env.example when AWS credentials are absent.
# No dependency on Gitpod, Ona, Codespaces, or any CI platform.

# No strict mode — errors must not kill the calling shell session
cd "$(dirname "$0")/.."

REGION="${AWS_DEFAULT_REGION:-us-east-1}"
SSM_PATH="/elevate/"
ENV_FILE=".env.local"

echo "Setting up environment..."

pull_from_ssm() {
  echo "  Pulling secrets from AWS SSM (region=${REGION} path=${SSM_PATH})"

  TMP=$(mktemp)
  NEXT_TOKEN=""

  while true; do
    if [ -n "$NEXT_TOKEN" ]; then
      RESULT=$(timeout 15 aws ssm get-parameters-by-path \
        --path "$SSM_PATH" \
        --with-decryption \
        --region "$REGION" \
        --next-token "$NEXT_TOKEN" \
        --output json 2>&1)
    else
      RESULT=$(timeout 15 aws ssm get-parameters-by-path \
        --path "$SSM_PATH" \
        --with-decryption \
        --region "$REGION" \
        --output json 2>&1)
    fi

    if [ $? -ne 0 ]; then
      echo "  SSM fetch failed or timed out: $RESULT"
      rm -f "$TMP"
      return 1
    fi

    # Strip /elevate/ prefix, write KEY=VALUE lines
    echo "$RESULT" | python3 -c "
import json, sys
d = json.load(sys.stdin)
for p in d.get('Parameters', []):
    name = p['Name'].split('/')[-1]
    value = p['Value']
    value = value.replace('\n', '\\\\n')
    if any(c in value for c in ' \t#\"'):
        value = '\"' + value.replace('\"', '\\\\\"') + '\"'
    print(f'{name}={value}')
" >> "$TMP"

    NEXT_TOKEN=$(echo "$RESULT" | python3 -c "
import json, sys
print(json.load(sys.stdin).get('NextToken', ''))
" 2>/dev/null || echo "")

    [ -z "$NEXT_TOKEN" ] && break
  done

  COUNT=$(grep -c "=" "$TMP" 2>/dev/null || echo 0)

  if [ "$COUNT" -eq 0 ]; then
    echo "  SSM returned 0 parameters — check credentials and IAM permissions"
    rm -f "$TMP"
    return 1
  fi

  {
    echo "# Generated by .devcontainer/setup-env.sh — do not edit manually."
    echo "# Regenerate: bash .devcontainer/setup-env.sh"
    echo ""
    echo "# Dev-local overrides (differ from production ECS values)"
    echo "NODE_ENV=development"
    echo "NEXTAUTH_URL=http://localhost:3000"
    echo "NEXT_PUBLIC_SITE_URL=http://localhost:3000"
    echo "NEXT_PUBLIC_ADMIN_URL=http://localhost:3001"
    echo "SUPABASE_PROJECT_REF=cuxzzpsyufcewtmicszk"
    echo "NEXT_TELEMETRY_DISABLED=1"
    echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium"
    echo "CHROMIUM_PATH=/usr/bin/chromium"
    echo ""
    echo "# Secrets from AWS SSM /elevate/*"
    cat "$TMP"
  } > "$ENV_FILE"

  rm -f "$TMP"
  echo "  Wrote $COUNT secrets to $ENV_FILE"
}

use_fallback() {
  if [ -f "$ENV_FILE" ]; then
    echo "  $ENV_FILE already exists — skipping (no AWS credentials to refresh)"
  elif [ -f .env.example ]; then
    cp .env.example "$ENV_FILE"
    echo "  No AWS credentials — copied .env.example to $ENV_FILE"
    echo "  Set AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY and re-run to pull real secrets."
  else
    echo "  No AWS credentials and no .env.example — create $ENV_FILE manually"
    exit 1
  fi
}

AWS_KEY="${AWS_ACCESS_KEY_ID:-}"
AWS_SECRET="${AWS_SECRET_ACCESS_KEY:-}"

if command -v aws &>/dev/null && [ -n "$AWS_KEY" ] && [ -n "$AWS_SECRET" ]; then
  pull_from_ssm || use_fallback
else
  echo "  No AWS credentials found (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY not set)"
  use_fallback
fi

# Symlink .env.local into apps/admin so both apps share the same secrets
if [ ! -f apps/admin/.env.local ] && [ ! -L apps/admin/.env.local ]; then
  ln -s "$(pwd)/.env.local" apps/admin/.env.local
  echo "  Symlinked .env.local -> apps/admin/.env.local"
fi

echo ""
echo "  pnpm dev          -> http://localhost:3000  (LMS)"
echo "  pnpm dev:admin    -> http://localhost:3001  (Admin)"
