/**
 * Deep lesson-level content for every lesson in the HVAC Technician course.
 * Each lesson has: concept explanation, key terms, visual reference,
 * job application, and what to watch for.
 */

export interface LessonContent {
  lessonId: string;
  concept: string;
  keyTerms: { term: string; definition: string }[];
  /** Which diagram ID from the visual library supports this lesson */
  diagramRef?: string;
  /** Real-world job application */
  jobApplication: string;
  /** Common mistakes or things to watch for */
  watchFor: string[];
}

export const HVAC_LESSON_CONTENT: Record<string, LessonContent> = {};

function add(c: LessonContent) { HVAC_LESSON_CONTENT[c.lessonId] = c; }

// ═══════════════════════════════════════════
// MODULE 1 — Program Orientation
// ═══════════════════════════════════════════

add({
  lessonId: 'hvac-01-01',
  concept: 'This lesson introduces the full 16-module HVAC training program. You will learn the weekly schedule, what credentials you earn (EPA 608 Universal, OSHA 10, CPR/AED), how the classroom and lab time is structured, and what employers expect from graduates. The HVAC industry has a severe technician shortage — the Bureau of Labor Statistics projects 13% job growth through 2031, much faster than average. Starting wages for certified technicians range from $16-22/hr, with experienced techs earning $25-40/hr. This program prepares you for immediate employment as an apprentice technician.',
  keyTerms: [
    { term: 'EPA 608', definition: 'Federal certification required by the Clean Air Act to purchase or handle any refrigerant. Without it, you cannot legally work on AC or refrigeration systems.' },
    { term: 'OSHA 10', definition: '10-hour construction safety certification delivered through CareerSafe. DOL wallet card issued upon completion. Required by most HVAC employers.' },
    { term: 'ETPL', definition: 'Eligible Training Provider List — state-approved programs that qualify for WIOA workforce funding.' },
    { term: 'Apprentice', definition: 'Entry-level technician working under supervision of a licensed journeyman, building on-the-job hours toward licensure.' },
  ],
  jobApplication: 'Understanding the career pathway from day one helps you set realistic expectations. Employers want technicians who understand the licensing process and are committed to building hours toward journeyman status.',
  watchFor: [
    'Do not skip the documentation requirements — missing paperwork delays your funding',
    'Register at indianacareerconnect.com immediately if you have not already',
    'The 80% attendance requirement is enforced — your funding depends on it',
  ],
});

add({
  lessonId: 'hvac-01-02',
  concept: 'WIOA (Workforce Innovation and Opportunity Act) is the primary funding source for most students in this program. This lesson explains exactly what WIOA covers: tuition, tools, transportation, childcare, work clothing, and certification exam fees. You will learn the eligibility requirements, how to work with your WorkOne case manager, and what documentation you need. Other funding options include the Workforce Ready Grant (WRG) for Indiana residents, Job Ready Indy (JRI) for justice-involved individuals, and self-pay with flexible payment plans.',
  keyTerms: [
    { term: 'WIOA', definition: 'Workforce Innovation and Opportunity Act — federal funding for job training administered through local WorkOne offices.' },
    { term: 'WRG', definition: 'Workforce Ready Grant — Indiana state funding for high-demand certifications, no income requirements.' },
    { term: 'ITA', definition: 'Individual Training Account — the WIOA funding mechanism that pays your tuition directly to the training provider.' },
    { term: 'Case Manager', definition: 'Your assigned WorkOne representative who manages your funding, tracks your progress, and connects you with support services.' },
  ],
  jobApplication: 'Understanding your funding keeps you enrolled. Students who lose funding usually lose it because they missed documentation deadlines or attendance requirements — not because they were ineligible.',
  watchFor: [
    'Keep copies of every document you submit',
    'Respond to your case manager within 24 hours — they control your funding',
    'If you have a transportation or childcare emergency, tell your case manager BEFORE you miss class',
  ],
});

add({
  lessonId: 'hvac-01-03',
  concept: 'The HVAC industry offers four career levels: Apprentice (0-2 years, $16-22/hr), Journeyman (2-5 years, $22-32/hr), Master Technician (5-10 years, $32-45/hr), and Contractor/Business Owner ($50-100K+ annually). This lesson maps each level to the certifications, hours, and skills required. You will also learn about specialization paths: residential service, commercial HVAC, refrigeration, building automation, and energy management. The skilled trades are experiencing a generational workforce gap — millions of technicians are retiring and not enough new workers are entering the field.',
  keyTerms: [
    { term: 'Journeyman', definition: 'Licensed technician who has completed required OJT hours (typically 2,000+) and passed the state exam. Can work independently.' },
    { term: 'Master Technician', definition: 'Experienced technician with advanced certifications (NATE, manufacturer-specific) who can diagnose complex system problems.' },
    { term: 'NATE', definition: 'North American Technician Excellence — the leading third-party certification for HVAC technicians, recognized by all major manufacturers.' },
    { term: 'OJT', definition: 'On-the-Job Training — supervised field work hours that count toward licensure requirements.' },
  ],
  jobApplication: 'Knowing the career ladder helps you negotiate your first job. An employer offering $16/hr with a clear path to journeyman is often better than $18/hr with no advancement plan.',
  watchFor: [
    'Track your OJT hours from day one — you will need documentation for licensure',
    'Ask potential employers about their apprenticeship structure during interviews',
    'Specialization increases your earning potential — start thinking about which path interests you',
  ],
});

add({
  lessonId: 'hvac-01-04',
  concept: 'This quiz covers program structure, funding options, attendance requirements, documentation needs, and career pathways. You must score 70% or higher to proceed. The quiz tests whether you understand the practical requirements of staying enrolled and funded — not technical HVAC knowledge yet.',
  keyTerms: [],
  jobApplication: 'Employers value technicians who understand the business side of the trade, not just the technical side.',
  watchFor: [
    'Review the attendance and documentation requirements before taking this quiz',
    'Know the difference between WIOA, WRG, and JRI funding',
  ],
});

// ═══════════════════════════════════════════
// MODULE 2 — HVAC Fundamentals & Safety
// ═══════════════════════════════════════════

add({
  lessonId: 'hvac-02-01',
  concept: 'Every HVAC system has the same basic job: move heat from where you do not want it to where you do. In cooling mode, the system moves heat from inside the building to outside. In heating mode, it moves heat from a fuel source (gas, electricity, or outdoor air) into the building. This lesson covers the complete system: outdoor condenser unit, indoor air handler or furnace, evaporator coil, refrigerant lines (suction and liquid), ductwork (supply and return), thermostat, and electrical connections. You will learn how these components connect and why each one is necessary. The split-system air conditioner is the most common residential configuration — you will service this system more than any other in your career.',
  keyTerms: [
    { term: 'Split System', definition: 'An HVAC system with components split between outdoor (condenser) and indoor (air handler/furnace) units, connected by refrigerant lines.' },
    { term: 'Condenser', definition: 'The outdoor unit containing the compressor, condenser coil, and fan motor. Rejects heat to the outdoor air.' },
    { term: 'Evaporator', definition: 'The indoor coil where cold refrigerant absorbs heat from room air. Located above the furnace or inside the air handler.' },
    { term: 'Refrigerant Lines', definition: 'Two copper lines connecting indoor and outdoor units. The large insulated line is the suction line (cold vapor). The small line is the liquid line (warm liquid).' },
    { term: 'Air Handler', definition: 'The indoor unit containing the blower motor, evaporator coil, and air filter. Moves air through the duct system.' },
  ],
  diagramRef: 'hvac-system-overview',
  jobApplication: 'On every service call, you must quickly identify all system components and understand how they connect. A technician who cannot trace the refrigerant circuit or airflow path cannot diagnose problems.',
  watchFor: [
    'The suction line is ALWAYS the larger of the two refrigerant lines — it carries low-pressure vapor',
    'Never confuse the supply duct (conditioned air out) with the return duct (room air back)',
    'The thermostat controls the system with 24V signals — not line voltage',
  ],
});

add({
  lessonId: 'hvac-02-02',
  concept: 'This lesson covers every tool in your HVAC toolkit and how to use each one correctly. The digital multimeter measures voltage, resistance, continuity, and capacitance — you will use it on every single service call. The clamp-on ammeter measures current without disconnecting wires. The manifold gauge set connects to the system service ports to measure suction and discharge pressure — the blue gauge reads low-side pressure, the red gauge reads high-side pressure, and the yellow center hose connects to the refrigerant cylinder or vacuum pump. You will also learn to use thermometers (pipe clamp and digital), leak detectors (electronic and UV dye), vacuum pumps, recovery machines, refrigerant scales, tube cutters, flaring tools, swaging tools, and hand tools specific to HVAC work.',
  keyTerms: [
    { term: 'Multimeter', definition: 'Measures voltage (V), resistance (Ω), continuity, and capacitance (µF). The most-used diagnostic tool in HVAC.' },
    { term: 'Manifold Gauge Set', definition: 'Two pressure gauges (blue=low side, red=high side) with valves and hoses for measuring system pressures and charging refrigerant.' },
    { term: 'Clamp Meter', definition: 'Measures amperage by clamping around a wire without disconnecting it. Used to check motor amp draw against nameplate ratings.' },
    { term: 'Micron Gauge', definition: 'Measures deep vacuum levels during system evacuation. More accurate than compound gauges below atmospheric pressure.' },
    { term: 'Recovery Machine', definition: 'Removes refrigerant from a system into an approved recovery cylinder. Required before any system repair that opens the refrigerant circuit.' },
  ],
  diagramRef: 'manifold-gauge',
  jobApplication: 'A technician without proper tools cannot diagnose anything. Employers expect you to own a basic toolkit. Many WIOA programs cover tool costs — take advantage of this.',
  watchFor: [
    'Always zero your multimeter before measuring resistance',
    'Never connect the high-side gauge hose to the low-side port — check the line sizes',
    'A clamp meter must go around ONE wire only — clamping around both wires in a cable reads zero',
  ],
});

add({
  lessonId: 'hvac-02-03',
  concept: 'HVAC work involves serious hazards: high voltage (240V+), refrigerant exposure (frostbite, asphyxiation in confined spaces), working at heights (rooftops, ladders), hot surfaces (brazing, furnace heat exchangers), and rotating machinery (fan blades, blower motors). This lesson covers required PPE: safety glasses (always), work gloves (when handling sheet metal or hot surfaces), steel-toe boots, hearing protection (near compressors), and respiratory protection (when working with chemicals or in dusty environments). You will learn lockout/tagout (LOTO) procedures — the process of disconnecting and verifying zero energy before working on equipment. LOTO is not optional. Technicians die every year from equipment that was not properly de-energized.',
  keyTerms: [
    { term: 'LOTO', definition: 'Lockout/Tagout — the procedure of disconnecting power, locking the disconnect, and verifying 0 volts before working on equipment.' },
    { term: 'PPE', definition: 'Personal Protective Equipment — safety glasses, gloves, boots, hearing protection, and respiratory protection as required by the task.' },
    { term: 'Arc Flash', definition: 'An electrical explosion caused by a short circuit through air. Can cause severe burns and death. Proper PPE and de-energization prevent arc flash incidents.' },
    { term: 'Refrigerant Exposure', definition: 'Liquid refrigerant causes frostbite on contact with skin. In enclosed spaces, refrigerant vapor displaces oxygen and can cause asphyxiation.' },
  ],
  jobApplication: 'Safety violations get you fired immediately. No employer will tolerate a technician who skips LOTO or does not wear PPE. More importantly, safety keeps you alive.',
  watchFor: [
    'ALWAYS verify 0 volts with YOUR OWN multimeter after pulling the disconnect — never trust someone else',
    'Refrigerant is heavier than air — it sinks to the floor in enclosed spaces and displaces oxygen',
    'Never reach into a condenser unit without verifying the fan motor is de-energized',
  ],
});

add({
  lessonId: 'hvac-02-04',
  concept: 'In this lab, you will physically identify every major component on a residential split-system air conditioner. You will locate the compressor, condenser coil, fan motor, capacitor, contactor, and service valves on the outdoor unit. On the indoor unit, you will identify the evaporator coil, blower motor, air filter, control board, and thermostat connections. You will trace the refrigerant circuit from the compressor discharge through the condenser coil, liquid line, metering device, evaporator coil, and suction line back to the compressor. You will also trace the airflow path from the return grille through the filter, across the evaporator coil, through the supply ductwork, and out the supply registers.',
  keyTerms: [
    { term: 'Discharge Line', definition: 'The hot gas line from the compressor outlet to the condenser coil inlet. Hot to the touch during operation.' },
    { term: 'Liquid Line', definition: 'The smaller copper line carrying warm high-pressure liquid from the condenser to the metering device.' },
    { term: 'Suction Line', definition: 'The larger insulated copper line carrying cold low-pressure vapor from the evaporator back to the compressor.' },
  ],
  diagramRef: 'condenser-breakdown',
  jobApplication: 'Component identification is the foundation of every service call. If you cannot find the capacitor in 30 seconds, you cannot diagnose a no-cooling call efficiently.',
  watchFor: [
    'The capacitor stores electrical charge even when power is off — always discharge it before handling',
    'The contactor may be stuck closed (welded contacts) — check before assuming the system is off',
    'Label wires before disconnecting anything — take a photo with your phone first',
  ],
});

add({
  lessonId: 'hvac-02-05',
  concept: 'This quiz tests your understanding of HVAC system components, tool identification and usage, safety procedures, and PPE requirements. You must identify components by description, match tools to their diagnostic purpose, and demonstrate knowledge of LOTO procedures.',
  keyTerms: [],
  jobApplication: 'Employers test new hires on basic component identification and safety knowledge before allowing them on job sites.',
  watchFor: [
    'Know the difference between the suction line and liquid line',
    'Know which PPE is required for each type of task',
    'Understand LOTO — this will be on every safety quiz and every employer orientation',
  ],
});

// ═══════════════════════════════════════════
// MODULE 3 — Electrical Basics for HVAC
// ═══════════════════════════════════════════

add({
  lessonId: 'hvac-03-01',
  concept: 'Electricity is the language of HVAC systems. Every component — compressor, fan motor, blower, control board, thermostat — runs on electricity. This lesson teaches the three fundamental electrical properties: Voltage (V) is electrical pressure — the force that pushes electrons through a circuit. Current (I, measured in Amps) is the flow of electrons — how much electricity is moving. Resistance (R, measured in Ohms) is opposition to current flow. Ohm\'s Law ties them together: V = I × R. If you know any two values, you can calculate the third. Watt\'s Law adds power: P = V × I. A 240V compressor drawing 15 amps uses 3,600 watts (3.6 kW). You will use these calculations on every service call to determine if motors are drawing correct amperage, if circuits are properly sized, and if components have failed.',
  keyTerms: [
    { term: 'Voltage (V)', definition: 'Electrical pressure measured in volts. Residential HVAC uses 24V (control), 120V (blower), and 240V (compressor, heat strips).' },
    { term: 'Amperage (I)', definition: 'Electrical current measured in amps. Compare measured amps to the nameplate rating to determine if a motor is working correctly.' },
    { term: 'Resistance (Ω)', definition: 'Opposition to current flow measured in ohms. A good wire has near-zero ohms. An open circuit has infinite ohms.' },
    { term: 'Ohm\'s Law', definition: 'V = I × R. The fundamental relationship between voltage, current, and resistance.' },
    { term: 'RLA', definition: 'Rated Load Amps — the maximum continuous amperage a motor should draw under normal operating conditions. Listed on the nameplate.' },
    { term: 'LRA', definition: 'Locked Rotor Amps — the amperage a motor draws when it tries to start but cannot rotate. 5-8× higher than RLA. Indicates a seized compressor.' },
  ],
  diagramRef: 'control-circuit',
  jobApplication: 'When a compressor nameplate says RLA 14.0 and you measure 18.5 amps, you know something is wrong — dirty condenser coil, low voltage, or failing compressor. Without understanding amps, you cannot make this diagnosis.',
  watchFor: [
    'Always measure voltage BEFORE measuring resistance — never measure resistance on an energized circuit',
    'A motor drawing MORE than RLA is overloaded. A motor drawing LESS than RLA may have a mechanical problem.',
    'Line voltage below 207V on a 240V system causes motors to draw higher amps and overheat',
  ],
});

add({
  lessonId: 'hvac-03-02',
  concept: 'Wiring diagrams are the roadmaps of HVAC systems. There are two types: schematic diagrams (show the electrical logic — which components connect to which) and pictorial diagrams (show the physical location of components and wire routing). This lesson teaches you to read both. You will trace the 24V control circuit from the transformer through the thermostat to the contactor coil. You will trace the 240V power circuit from the disconnect through the contactor contacts to the compressor and fan motor. You will learn standard electrical symbols: switches, relays, transformers, motors, capacitors, and ground connections. Every manufacturer includes wiring diagrams on the equipment — usually on the inside of the access panel. Learning to read them is not optional.',
  keyTerms: [
    { term: 'Schematic Diagram', definition: 'Shows electrical connections logically — which components are in series or parallel. Used for troubleshooting circuit logic.' },
    { term: 'Pictorial Diagram', definition: 'Shows physical wire routing and component locations. Used for finding components and tracing wires on the actual equipment.' },
    { term: 'Series Circuit', definition: 'Components connected end-to-end. Current flows through each one. If any component opens, the entire circuit stops. Safety switches are wired in series.' },
    { term: 'Parallel Circuit', definition: 'Components connected across the same voltage source. Each has its own current path. The compressor and fan motor are wired in parallel.' },
  ],
  diagramRef: 'control-circuit',
  jobApplication: 'On a no-cooling call, you trace the 24V circuit: transformer → thermostat → safety switches → contactor coil. If you find 24V at the thermostat but 0V at the contactor, the problem is between those two points. Without reading the diagram, you are guessing.',
  watchFor: [
    'Always check the wiring diagram on the equipment — do not assume all systems are wired the same',
    'A broken wire in a series circuit stops everything downstream',
    'Color codes vary by manufacturer — trace wires, do not rely on color alone',
  ],
});

add({
  lessonId: 'hvac-03-03',
  concept: 'In this lab, you will use a digital multimeter to measure AC voltage (at the disconnect, contactor, and transformer), DC voltage (at the control board), resistance (across motor windings and capacitors), continuity (through switches and fuses), and capacitance (on run capacitors). You will use a clamp-on ammeter to measure motor amperage on the compressor and fan motor, comparing readings to nameplate values. You will practice safe measurement techniques: selecting the correct meter function, using the correct probe ports, and never measuring resistance on an energized circuit.',
  keyTerms: [
    { term: 'Continuity', definition: 'A complete electrical path. Your meter beeps when continuity exists (near-zero ohms). No beep = open circuit (broken wire, blown fuse, open switch).' },
    { term: 'Capacitance', definition: 'The ability to store electrical charge, measured in microfarads (µF). A capacitor must be within ±6% of its rated value to work properly.' },
    { term: 'Common (C) Terminal', definition: 'On a compressor, the terminal connected to both the start and run windings. Used as a reference point for winding resistance measurements.' },
  ],
  diagramRef: 'multimeter-diagram',
  jobApplication: 'Every service call requires meter readings. Measuring voltage confirms power. Measuring amps confirms motor health. Measuring capacitance confirms capacitor condition. These three measurements solve 80% of electrical problems.',
  watchFor: [
    'Set your meter to the correct function BEFORE connecting probes — wrong setting can damage the meter or shock you',
    'Discharge capacitors before measuring capacitance — stored charge gives false readings and can shock you',
    'When measuring amps, clamp around ONE conductor only — clamping around a cable with multiple wires reads the net current (often zero)',
  ],
});

add({
  lessonId: 'hvac-03-04',
  concept: 'Capacitors, contactors, and relays are the three most commonly replaced electrical components in HVAC. A run capacitor stores and releases energy to keep motors running efficiently — when it fails, the motor hums but does not start, or starts slowly and overheats. Capacitors are rated in microfarads (µF) and voltage. A dual run capacitor has three terminals: HERM (compressor), FAN (condenser fan), and C (common). A contactor is an electrically controlled switch — 24V from the thermostat energizes the coil, which magnetically pulls the contacts closed, sending 240V to the motors. Pitted or burned contacts cause voltage drop and overheating. A relay is a smaller version of a contactor, used for lower-current switching like fan relays and time-delay relays.',
  keyTerms: [
    { term: 'Run Capacitor', definition: 'Provides continuous phase shift to keep a motor running efficiently. Failure causes humming, slow starting, or motor overheating.' },
    { term: 'Start Capacitor', definition: 'Provides a brief high-torque boost during motor startup, then disconnects. Used on hard-start kits.' },
    { term: 'Dual Run Capacitor', definition: 'Single capacitor with two sections — one for the compressor (HERM) and one for the fan motor (FAN), sharing a common terminal (C).' },
    { term: 'Contactor', definition: 'Electrically controlled switch. 24V coil pulls contacts closed to pass 240V to motors. Most common failure: pitted/burned contacts.' },
  ],
  diagramRef: 'capacitor-diagram',
  jobApplication: 'Bad capacitors are the #1 cause of no-cooling calls in summer. A technician who can diagnose and replace a capacitor in 15 minutes is worth their weight in gold to an employer.',
  watchFor: [
    'Always replace a capacitor with the EXACT µF rating — wrong value damages the motor',
    'A bulging or leaking capacitor is failed — replace it even if it still reads in range',
    'Pitted contactor contacts cause a voltage drop that makes motors draw higher amps and overheat',
  ],
});

add({
  lessonId: 'hvac-03-05',
  concept: 'This quiz tests Ohm\'s Law calculations, meter usage, wiring diagram reading, capacitor diagnosis, contactor operation, and electrical safety. You must be able to calculate voltage, current, or resistance given the other two values, identify the correct meter function for each measurement, and trace a circuit on a wiring diagram.',
  keyTerms: [],
  jobApplication: 'Electrical knowledge separates a parts-changer from a real technician. Anyone can swap a capacitor — a technician understands WHY it failed and checks for the root cause.',
  watchFor: [
    'Know Ohm\'s Law cold: V=IR, I=V/R, R=V/I',
    'Know the difference between series and parallel circuits',
    'Know what RLA and LRA mean and how to use them diagnostically',
  ],
});



// MODULE 4
add({ lessonId: 'hvac-04-01', concept: 'A gas furnace burns natural gas or propane to heat air. The sequence: thermostat calls for heat, draft inducer starts, pressure switch closes, igniter glows at 1800F+, gas valve opens, burners ignite, flame sensor proves flame, heat exchanger warms, blower starts after delay, warm air flows through ducts. If any step fails, the control board shuts down. The heat exchanger separates combustion gases from breathable air. A crack allows carbon monoxide into the living space.', keyTerms: [{ term: 'Heat Exchanger', definition: 'Metal chambers transferring combustion heat to room air. A crack leaks CO.' }, { term: 'Flame Sensor', definition: 'Thin metal rod proving flame by conducting microamps. Dirty flame sensor is the number one no-heat call.' }], diagramRef: 'furnace-breakdown', jobApplication: 'Gas furnace calls are winter bread and butter. Diagnosing no-heat in 15 minutes keeps you busy all season.', watchFor: ['Read control board LED fault codes FIRST', 'Dirty flame sensor is the most common no-heat cause', 'Never bypass a safety switch'] });
add({ lessonId: 'hvac-04-02', concept: 'Electric heat uses resistance elements called heat strips. Nichrome wire generates heat when current flows through it. Strips are staged through a sequencer relay to prevent inrush current. A 15kW system might have three 5kW stages. Electric heat is 100 percent efficient but expensive. Heat strips serve as auxiliary and emergency heat in heat pump systems.', keyTerms: [{ term: 'Heat Strip', definition: 'Nichrome wire resistance element converting electricity to heat.' }, { term: 'Sequencer', definition: 'Time-delay relay staging heat strips on one at a time.' }], jobApplication: 'High winter electric bills often mean heat strips running constantly because the heat pump has a problem.', watchFor: ['Measure amp draw on each element', 'Emergency heat costs 2-3x more than heat pump operation'] });
add({ lessonId: 'hvac-04-03', concept: 'A heat pump is an AC that runs in reverse. A reversing valve switches refrigerant flow direction. In cooling mode the outdoor coil rejects heat. In heating mode the outdoor coil absorbs heat from outdoor air. The O wire energizes the reversing valve in cooling mode on Carrier and Honeywell systems. The B wire energizes it in heating mode on Rheem and Ruud systems. In heating mode the outdoor coil ices up and the defrost control periodically switches to cooling mode to melt ice.', keyTerms: [{ term: 'Reversing Valve', definition: 'A 4-way valve changing refrigerant flow direction between heating and cooling.' }, { term: 'Defrost Cycle', definition: 'Temporarily switches to cooling to melt outdoor coil ice.' }], diagramRef: 'heat-pump-system', jobApplication: 'Heat pumps are the fastest-growing residential HVAC segment.', watchFor: ['Know O vs B convention before diagnosing', 'Stuck reversing valve causes heating in cooling mode or vice versa'] });
add({ lessonId: 'hvac-04-04', concept: 'Combustion analysis verifies safe efficient furnace operation. A combustion analyzer measures CO, O2, CO2, and stack temperature in flue gases. Gas pressure is measured with a manometer. Natural gas should be 3.5 inches water column at the manifold. Incorrect pressure causes incomplete combustion and carbon monoxide production.', keyTerms: [{ term: 'Combustion Analyzer', definition: 'Measures CO, O2, CO2, stack temp in flue gases.' }, { term: 'Manifold Pressure', definition: 'Gas pressure at burners. Natural gas 3.5 in w.c.' }], diagramRef: 'furnace-breakdown', jobApplication: 'Combustion analysis is required during installation and annual maintenance.', watchFor: ['Any CO above 9 ppm in living space requires investigation', 'Never adjust gas pressure without a manometer'] });
add({ lessonId: 'hvac-04-05', concept: 'Complete furnace inspection lab covering visual heat exchanger inspection, flame sensor cleaning and microamp measurement, igniter resistance check, gas pressure measurement, burner flame inspection, blower amp draw, filter replacement, safety switch testing, control board fault codes, and thermostat verification. Document findings on a professional service report.', keyTerms: [{ term: 'Temperature Rise', definition: 'Supply minus return air temp across furnace. Must be within nameplate range.' }], diagramRef: 'furnace-breakdown', jobApplication: 'Furnace maintenance is major revenue for HVAC companies.', watchFor: ['Check temperature rise against nameplate range', 'Flame sensor below 1 microamp needs cleaning'] });
add({ lessonId: 'hvac-04-06', concept: 'Quiz covering gas furnace operation sequence, heat exchanger safety, electric heat, heat pump operation, combustion analysis, and inspection procedures.', keyTerms: [], jobApplication: 'Heating knowledge is tested on the journeyman exam.', watchFor: ['Know the complete furnace ignition sequence', 'Know what a cracked heat exchanger means'] });

// MODULE 5
add({ lessonId: 'hvac-05-01', concept: 'The refrigeration cycle has four stages. Compression: the compressor takes low-pressure vapor and compresses it into high-pressure high-temperature gas. Condensation: hot gas flows through the condenser coil where outdoor air removes heat and refrigerant condenses into warm liquid. Expansion: the metering device creates a pressure drop converting warm liquid into cold low-pressure mixture. Evaporation: cold refrigerant flows through the evaporator coil absorbing heat from indoor air and evaporating into vapor. HVAC systems move heat, they do not create cold.', keyTerms: [{ term: 'Superheat', definition: 'Temperature of vapor above its boiling point at the current pressure. Measured at suction line.' }, { term: 'Subcooling', definition: 'Temperature of liquid below its condensing point at the current pressure. Measured at liquid line.' }, { term: 'TXV', definition: 'Thermostatic Expansion Valve adjusting refrigerant flow based on evaporator superheat.' }], diagramRef: 'refrigeration-cycle', jobApplication: 'Every cooling diagnosis starts with the refrigeration cycle. Understanding what should happen at each stage lets you identify what is actually happening.', watchFor: ['High superheat means not enough refrigerant reaching evaporator', 'Low superheat means too much liquid risking compressor damage', 'Systems move heat not create cold'] });
add({ lessonId: 'hvac-05-02', concept: 'The pressure-temperature relationship is the foundation of refrigerant diagnostics. Every refrigerant has a specific saturation temperature at each pressure. For R-410A at 118 psig the saturation temp is about 40F. You use the PT chart to convert gauge readings to temperatures. Superheat equals actual suction line temp minus suction saturation temp. Subcooling equals liquid saturation temp minus actual liquid line temp. These two calculations tell you the condition of the charge.', keyTerms: [{ term: 'PT Chart', definition: 'Shows saturation temperature for each refrigerant at every pressure.' }, { term: 'R-410A', definition: 'Standard residential AC refrigerant operating at higher pressures than R-22.' }], diagramRef: 'pt-chart', jobApplication: 'You will calculate superheat and subcooling on every cooling diagnostic call.', watchFor: ['Use the PT chart for the CORRECT refrigerant', 'Superheat measured at suction line, subcooling at liquid line', 'Conditions affect normal readings'] });
add({ lessonId: 'hvac-05-03', concept: 'The compressor compresses low-pressure vapor into high-pressure gas. Residential systems use scroll compressors (two spiral scrolls, one orbiting) and reciprocating compressors (piston and cylinder). The motor has C, S, and R terminals. Diagnose by measuring winding resistance: C-S highest, C-R lower, S-R equals C-S plus C-R. Open winding means burned out. Grounded winding (low resistance to shell) means insulation breakdown and replacement.', keyTerms: [{ term: 'Scroll Compressor', definition: 'Two interlocking spirals compress refrigerant. Quieter and more efficient.' }, { term: 'C-S-R Terminals', definition: 'Common, Start, Run terminals for winding resistance diagnosis.' }], jobApplication: 'Before condemning a compressor always check the capacitor and contactor first. Those are much cheaper.', watchFor: ['Humming compressor usually means bad capacitor not bad compressor', 'Always check capacitor and contactor BEFORE condemning compressor', 'Grounded winding trips breaker immediately'] });
add({ lessonId: 'hvac-05-04', concept: 'The metering device controls refrigerant flow into the evaporator. TXV adjusts flow based on superheat using a sensing bulb on the suction line. Piston is a fixed orifice providing constant restriction. TXV systems are charged by subcooling target 10-15F. Piston systems are charged by superheat using the manufacturer charging chart. Using the wrong method gives incorrect results.', keyTerms: [{ term: 'TXV Sensing Bulb', definition: 'Temperature sensor clamped to suction line controlling TXV opening.' }, { term: 'Fixed Orifice', definition: 'Piston with precisely sized hole providing constant restriction.' }], diagramRef: 'refrigeration-cycle', jobApplication: 'Knowing which metering device determines your charging method. Wrong method gives wrong results.', watchFor: ['Check data plate for TXV or piston', 'Restricted TXV mimics low charge symptoms', 'Sensing bulb must be properly mounted and insulated'] });
add({ lessonId: 'hvac-05-05', concept: 'Lab: connect manifold gauges to a live system and calculate superheat and subcooling. Connect blue hose to suction port, red to liquid port. Read pressures, convert to saturation temps using PT chart, measure actual line temps, calculate superheat and subcooling. Practice on systems with correct charge, undercharge, and overcharge to see how numbers change.', keyTerms: [{ term: 'Target Superheat', definition: 'Manufacturer-specified superheat at current conditions.' }, { term: 'Target Subcooling', definition: 'Manufacturer-specified subcooling, typically 10-15F for TXV systems.' }], diagramRef: 'system-diagnostic-points', jobApplication: 'This is the single most important diagnostic skill in HVAC.', watchFor: ['Verify airflow BEFORE connecting gauges', 'Let system run 15+ minutes before readings', 'Cap service ports after disconnecting'] });
add({ lessonId: 'hvac-05-06', concept: 'Quiz testing refrigeration cycle stages, PT chart usage, superheat and subcooling calculations, compressor diagnosis, metering device operation, and gauge reading interpretation.', keyTerms: [], jobApplication: 'Refrigeration knowledge is core to EPA 608 and every job interview.', watchFor: ['Calculate superheat and subcooling from given readings', 'Know what high/low values indicate', 'Know TXV vs piston charging methods'] });

// MODULE 6
add({ lessonId: 'hvac-06-01', concept: 'CFCs and HCFCs contain chlorine that destroys the ozone layer. One chlorine atom can destroy 100,000 ozone molecules. The Montreal Protocol phased out CFC production (R-12 banned 1996) and is phasing out HCFCs (R-22 production ended 2020). HFCs like R-410A have zero ozone depletion potential but high global warming potential. The Kigali Amendment phases down HFCs. Understanding this history explains why refrigerant handling regulations exist.', keyTerms: [{ term: 'CFC', definition: 'Chlorofluorocarbon. Highest ozone depletion. R-12 is a CFC. Banned.' }, { term: 'HCFC', definition: 'Hydrochlorofluorocarbon. Lower ozone depletion. R-22 is an HCFC. Being phased out.' }, { term: 'HFC', definition: 'Hydrofluorocarbon. Zero ozone depletion but high GWP. R-410A is an HFC.' }, { term: 'ODP', definition: 'Ozone Depletion Potential. CFC highest, HCFC lower, HFC zero.' }], jobApplication: 'EPA 608 exam tests this extensively. Understanding why regulations exist helps you remember the rules.', watchFor: ['Know the CFC/HCFC/HFC hierarchy', 'R-22 can no longer be manufactured but existing stocks can be used', 'HFCs are next to be phased down under Kigali'] });
add({ lessonId: 'hvac-06-02', concept: 'Section 608 of the Clean Air Act makes it illegal to knowingly vent refrigerant. Fines up to $44,539 per day per violation. Technicians must be EPA 608 certified to purchase refrigerant. Recovery is required before any repair that opens the refrigerant circuit. Records must be kept for refrigerant purchases, usage, and disposal. The law applies to ALL refrigerants including HFCs.', keyTerms: [{ term: 'Section 608', definition: 'Clean Air Act provision regulating stationary refrigerant equipment.' }, { term: 'Venting Prohibition', definition: 'Knowingly releasing refrigerant is illegal. Fines up to $44,539 per day.' }], jobApplication: 'Violations result in personal fines, not just company fines. You are personally liable.', watchFor: ['Venting is illegal for ALL refrigerant types', 'Fines apply to individuals not just companies', 'Record keeping is required'] });
add({ lessonId: 'hvac-06-03', concept: 'Refrigerant safety: liquid refrigerant causes frostbite on skin contact. Refrigerant vapor is heavier than air and displaces oxygen in enclosed spaces causing asphyxiation. Decomposed refrigerant (from flame contact) produces phosgene gas which is toxic. Always use PPE when handling refrigerant. Never use an open flame leak detector on systems with refrigerant. Cylinders must be stored upright, away from heat, and secured to prevent falling.', keyTerms: [{ term: 'Phosgene', definition: 'Toxic gas produced when refrigerant contacts an open flame. Extremely dangerous.' }, { term: 'Asphyxiation', definition: 'Suffocation from oxygen displacement. Refrigerant vapor sinks and displaces breathable air.' }], jobApplication: 'Refrigerant safety is tested on every EPA 608 section. More importantly it keeps you alive.', watchFor: ['Refrigerant is heavier than air and sinks', 'Never use open flame leak detectors', 'Work in ventilated areas when handling refrigerant'] });
add({ lessonId: 'hvac-06-04', concept: 'Refrigerant classification: Group 1 (low toxicity, low flammability) includes R-410A, R-22, R-134a. Group 2 (low toxicity, mildly flammable) includes R-32. Group 3 (low toxicity, highly flammable) includes R-290 (propane). Safety group A means low toxicity, B means higher toxicity. Flammability class 1 means no flame propagation, 2L means mildly flammable, 3 means highly flammable. Cylinder colors identify refrigerants: R-410A is rose/pink, R-22 is green, R-134a is light blue.', keyTerms: [{ term: 'ASHRAE 34', definition: 'Standard classifying refrigerants by toxicity and flammability.' }, { term: 'A2L', definition: 'Low toxicity, mildly flammable. Includes newer low-GWP refrigerants like R-32.' }], jobApplication: 'Knowing refrigerant classifications prevents dangerous mixing and ensures proper handling.', watchFor: ['Never mix refrigerants', 'Cylinder color identifies the refrigerant type', 'A2L refrigerants require special handling procedures'] });
add({ lessonId: 'hvac-06-05', concept: 'Pressure-temperature fundamentals for EPA 608: every refrigerant has a unique PT relationship. At the same pressure different refrigerants have different saturation temperatures. This is why you must know which refrigerant is in the system before connecting gauges. R-410A operates at approximately 1.6 times the pressure of R-22 at the same temperature. Using R-22 gauges on an R-410A system can be dangerous because the pressures exceed the gauge range.', keyTerms: [{ term: 'Saturation', definition: 'The condition where liquid and vapor coexist at a given pressure and temperature.' }], diagramRef: 'pt-chart', jobApplication: 'PT relationships are tested extensively on the EPA 608 exam.', watchFor: ['R-410A pressures are much higher than R-22', 'Use gauges rated for the refrigerant in the system', 'Identify the refrigerant BEFORE connecting gauges'] });
add({ lessonId: 'hvac-06-06', concept: 'Recovery removes refrigerant from a system into an approved cylinder. Recycling cleans recovered refrigerant by removing oil and moisture for reuse. Reclamation processes refrigerant at a certified facility to ARI 700 purity standards. Recovery is required before any repair that opens the refrigerant circuit. Recovery equipment must be certified and tested annually. Recovery cylinders must never be filled above 80 percent capacity.', keyTerms: [{ term: 'Recovery', definition: 'Removing refrigerant from a system into an approved cylinder.' }, { term: 'Recycling', definition: 'Cleaning recovered refrigerant by removing oil and moisture.' }, { term: 'Reclamation', definition: 'Processing refrigerant to ARI 700 purity at a certified facility.' }], diagramRef: 'recovery-machine', jobApplication: 'You will recover refrigerant on almost every major repair. Proper technique prevents contamination and legal issues.', watchFor: ['Never fill recovery cylinders above 80 percent', 'Recovery equipment must be certified', 'Know the difference between recovery, recycling, and reclamation'] });
add({ lessonId: 'hvac-06-07', concept: 'Since January 2018 only EPA 608 certified technicians can purchase refrigerant including HFCs like R-410A. This applies to all container sizes. Sellers must verify certification before selling. Records of sales must be maintained. This regulation closed the loophole that previously allowed anyone to buy HFC refrigerants.', keyTerms: [{ term: 'Sales Restriction', definition: 'Only EPA 608 certified technicians can purchase any refrigerant since 2018.' }], jobApplication: 'Without your EPA 608 card you cannot buy refrigerant. Period.', watchFor: ['Applies to ALL refrigerants including HFCs', 'Applies to ALL container sizes', 'Keep your EPA 608 card with you at all times'] });
add({ lessonId: 'hvac-06-08', concept: 'EPA 608 Core practice exam covering ozone depletion, Clean Air Act, refrigerant safety, classifications, PT fundamentals, recovery/recycling/reclamation, and sales restrictions. 25 questions, must score 70 percent or higher.', keyTerms: [], jobApplication: 'The Core section must be passed to earn any EPA 608 certification level.', watchFor: ['Know CFC/HCFC/HFC differences', 'Know venting penalties', 'Know recovery/recycling/reclamation definitions'] });

// ESCO gap lessons — added to cover content tested on the actual exam
add({ lessonId: 'hvac-06-09', concept: 'ASHRAE Standard 15 is the Safety Standard for Refrigeration Systems. It governs equipment room requirements, refrigerant detector placement, ventilation rates, and emergency shutoffs. ASHRAE Standard 34 assigns safety group designations to refrigerants based on toxicity (A=lower, B=higher) and flammability (1=none, 2L=mildly flammable, 2=flammable, 3=highly flammable). Every refrigerant has a safety group — R-410A is A1, R-32 is A2L, R-290 (propane) is A3, R-123 is B1. Knowing these classifications tells you what PPE, ventilation, and equipment is required.', keyTerms: [{ term: 'ASHRAE 15', definition: 'Safety Standard for Refrigeration Systems. Covers equipment rooms, ventilation, and emergency shutoffs.' }, { term: 'ASHRAE 34', definition: 'Refrigerant designation and safety classification standard. Assigns A/B toxicity and 1/2L/2/3 flammability ratings.' }, { term: 'A2L', definition: 'Low toxicity, mildly flammable. Burning velocity ≤10 cm/s. Includes R-32, R-454B, R-466A.' }], jobApplication: 'When you see a new refrigerant on a system nameplate, the ASHRAE 34 safety group tells you immediately what precautions to take before you open anything.', watchFor: ['A2L refrigerants require A2L-rated equipment — you cannot retrofit', 'B-class refrigerants (R-123) require more ventilation and PPE', 'ASHRAE 15 compliance is required for commercial equipment rooms'] });

add({ lessonId: 'hvac-06-10', concept: 'DOT (Department of Transportation) regulates refrigerant cylinders. Every cylinder has a DOT specification stamped on the collar: the spec number, working pressure, water capacity, tare weight, and hydrostatic test date. Cylinders must be hydrostatically retested every 5 years — an expired test date means the cylinder cannot legally be refilled. Recovery cylinders are gray with yellow tops (DOT standard color). Never fill any cylinder above 80 percent of its water capacity. Disposable cylinders cannot be refilled — it is illegal and dangerous. Record keeping: technicians must keep records of refrigerant purchases and disposals for 3 years and make them available for EPA inspection.', keyTerms: [{ term: 'Hydrostatic Test Date', definition: 'Stamped on the cylinder collar. Must be within 5 years or the cylinder cannot be refilled.' }, { term: 'Tare Weight', definition: 'The empty weight of the cylinder. Used to calculate how much refrigerant is inside.' }, { term: 'Water Capacity', definition: 'The total volume of the cylinder. Never fill above 80% of this value.' }], jobApplication: 'Check the hydrostatic test date before every recovery job. An expired cylinder at a supply house is a red flag — do not use it.', watchFor: ['Gray body, yellow top = DOT recovery cylinder color standard', 'Never refill a disposable cylinder — it is a federal violation', 'Keep purchase records 3 years minimum'] });

add({ lessonId: 'hvac-06-11', concept: 'EPA 608 has four certification types. Type I covers small appliances (5 lbs or less). Type II covers high-pressure systems (R-410A, R-22, R-134a). Type III covers low-pressure systems (R-11, R-123 chillers). Universal certification covers all three types and is the most valuable for a working technician. Each type requires a separate exam section. To earn Universal you must pass all four sections (Core plus Types I, II, and III). Certification does not expire but you must keep your card. Since 2018 you must show your certification card to purchase any refrigerant.', keyTerms: [{ term: 'Universal Certification', definition: 'Passes all four EPA 608 sections. Allows work on any refrigerant system type.' }, { term: 'Type I', definition: 'Small appliances — factory-charged systems with 5 lbs or less.' }, { term: 'Type II', definition: 'High-pressure systems — residential and commercial AC, heat pumps.' }, { term: 'Type III', definition: 'Low-pressure systems — centrifugal chillers using R-11, R-123.' }], jobApplication: 'Get Universal. Type II alone limits your career. Universal opens every door — residential, commercial, industrial.', watchFor: ['Core section is required for ALL certification types', 'Certification does not expire but keep your card', 'You need your card to buy refrigerant — carry it always'] });

add({ lessonId: 'hvac-06-12', concept: 'A2L refrigerants are the future of the HVAC industry. The AIM Act (American Innovation and Manufacturing Act) is phasing down HFCs including R-410A. Replacements include R-454B (Opteon XL41, GWP 466), R-32 (GWP 675), and R-466A (GWP 733). All are A2L — mildly flammable. Equipment must be specifically designed and listed for A2L use. You cannot retrofit existing R-410A equipment. A2L systems require: leak detection systems, proper ventilation, elimination of ignition sources, and A2L-rated tools and equipment. The EPA 608 exam now includes A2L content.', keyTerms: [{ term: 'AIM Act', definition: 'American Innovation and Manufacturing Act. Phases down HFC production and use in the US.' }, { term: 'R-454B', definition: 'Primary A2L replacement for R-410A in new residential systems. Trade name Opteon XL41. GWP 466.' }, { term: 'GWP', definition: 'Global Warming Potential. Measured relative to CO2 (GWP=1). R-410A GWP=2,088. R-454B GWP=466.' }], jobApplication: 'New residential systems are already shipping with R-454B. If you are not trained on A2L handling you will not be able to service new equipment within 2-3 years.', watchFor: ['Never use R-410A tools on A2L systems without verifying A2L rating', 'A2L does not mean safe to ignore — it still requires proper ventilation', 'R-32 mini-splits are already common — you are likely to encounter them now'] });

// MODULE 7
add({ lessonId: 'hvac-07-01', concept: 'Type I covers factory-charged systems containing 5 lbs or less of refrigerant. This includes window AC units, PTACs, household refrigerators, freezers, dehumidifiers, water coolers, and vending machines. These systems are manufactured as sealed units and are not designed for field charging. The refrigerant circuit is typically brazed closed with no service ports.', keyTerms: [{ term: 'Small Appliance', definition: 'Factory-charged system with 5 lbs or less of refrigerant.' }, { term: 'PTAC', definition: 'Packaged Terminal Air Conditioner. Self-contained unit installed through a wall.' }], jobApplication: 'Many entry-level jobs involve servicing small appliances in hotels, restaurants, and residential settings.', watchFor: ['5 lbs is the cutoff for small appliances', 'Factory-charged means sealed at the factory', 'PTACs under 5 lbs are Type I'] });
add({ lessonId: 'hvac-07-02', concept: 'Type I recovery requirements: 90 percent recovery for operating systems, 80 percent for non-operating systems. Both self-contained and system-dependent recovery equipment can be used. System-dependent recovery uses the appliance own compressor or internal pressure to push refrigerant into the recovery vessel. If the compressor does not work you cannot achieve 90 percent which is why the non-operating requirement is lower at 80 percent.', keyTerms: [{ term: 'Self-Contained Recovery', definition: 'Uses its own compressor to pull refrigerant out of the system.' }, { term: 'System-Dependent Recovery', definition: 'Uses the appliance own compressor or pressure to push refrigerant out.' }], jobApplication: 'Proper recovery technique prevents EPA violations and environmental damage.', watchFor: ['90 percent for operating, 80 percent for non-operating', 'System-dependent relies on the appliance compressor working', 'Both methods are acceptable for small appliances'] });
add({ lessonId: 'hvac-07-03', concept: 'Self-contained recovery equipment has its own compressor and can recover refrigerant regardless of whether the appliance compressor works. It connects to the system through access valves or process tubes. The recovered refrigerant goes into an approved DOT recovery cylinder. Self-contained equipment must be certified by an EPA-approved testing organization.', keyTerms: [{ term: 'Process Tube', definition: 'A sealed copper tube on a small appliance that can be pierced for access to the refrigerant circuit.' }, { term: 'Access Valve', definition: 'A valve installed on the system to allow gauge and recovery equipment connection.' }], jobApplication: 'Self-contained recovery is the more reliable method since it does not depend on the appliance working.', watchFor: ['Equipment must be EPA-certified', 'Recovery cylinders must be DOT-approved', 'Never overfill cylinders past 80 percent'] });
add({ lessonId: 'hvac-07-04', concept: 'Small appliances are exempt from the mandatory leak repair requirements that apply to larger systems. However refrigerant must still be recovered before disposal. This exemption exists because the cost of leak repair on a small appliance often exceeds the cost of replacement. Scrap dealers and recyclers must also recover refrigerant before processing appliances.', keyTerms: [{ term: 'Leak Repair Exemption', definition: 'Small appliances are exempt from mandatory leak repair rules but recovery is still required before disposal.' }], jobApplication: 'Even though leak repair is not required you must still recover refrigerant before disposing of any appliance.', watchFor: ['Exemption is from leak REPAIR not from recovery', 'Scrap dealers must also recover refrigerant', 'Disposal without recovery is illegal'] });
add({ lessonId: 'hvac-07-05', concept: 'EPA 608 Type I practice exam covering small appliance definitions, recovery requirements, self-contained and system-dependent equipment, leak repair exemptions, and disposal requirements. 25 questions, must score 70 percent or higher.', keyTerms: [], jobApplication: 'Type I certification allows you to work on small appliances legally.', watchFor: ['Know the 5 lb cutoff', 'Know 90/80 percent recovery requirements', 'Know the leak repair exemption details'] });

// MODULE 8
add({ lessonId: 'hvac-08-01', concept: 'Type II covers high-pressure systems — the most common HVAC equipment including residential AC, commercial rooftop units, and heat pumps. These systems use refrigerants like R-410A, R-22, and R-134a that operate above atmospheric pressure on both the high and low sides. High-pressure systems have service ports for gauge connection and are designed for field service including charging, recovery, and component replacement.', keyTerms: [{ term: 'High-Pressure System', definition: 'System operating above atmospheric pressure on both sides. Includes most residential and commercial AC.' }], jobApplication: 'Type II is the most important certification for residential and commercial HVAC technicians.', watchFor: ['Most of your career will involve Type II systems', 'R-410A operates at significantly higher pressures than R-22', 'Always identify the refrigerant before connecting gauges'] });
add({ lessonId: 'hvac-08-02', concept: 'Type II recovery requirements depend on system charge size. Systems under 200 lbs: recover to 0 psig. Systems 200 lbs or more: recover to 10 inches Hg vacuum. These levels apply when using recovery equipment manufactured after November 15, 1993. Recovery must be completed before opening the system for repair. The only exception is de minimis releases during normal connection and disconnection of gauges and hoses.', keyTerms: [{ term: 'De Minimis Release', definition: 'The small unavoidable release when connecting or disconnecting hoses. This is the only legal release.' }], jobApplication: 'Know these recovery levels cold for the EPA 608 exam and for every service call.', watchFor: ['Under 200 lbs = 0 psig', 'Over 200 lbs = 10 inches Hg vacuum', 'De minimis is the ONLY legal release'] });
add({ lessonId: 'hvac-08-03', concept: 'Leak detection methods: electronic leak detectors sense refrigerant vapor and alarm when concentration exceeds the threshold. UV dye is injected into the system and glows under UV light at the leak location. Soap bubbles applied to suspected leak points will bubble when refrigerant escapes. Nitrogen pressure testing pressurizes the system with dry nitrogen to check for pressure drop over time. Standing pressure test leaves the system pressurized overnight and checks for pressure drop the next day.', keyTerms: [{ term: 'Electronic Leak Detector', definition: 'Senses refrigerant vapor concentration. Must be calibrated before each use.' }, { term: 'Standing Pressure Test', definition: 'System pressurized with nitrogen overnight. Pressure drop indicates a leak.' }], jobApplication: 'Finding leaks is one of the most time-consuming parts of HVAC service. Mastering multiple detection methods makes you more efficient.', watchFor: ['Calibrate electronic detectors before each use', 'Never pressurize with oxygen — explosion risk', 'Use dry nitrogen only for pressure testing'] });
add({ lessonId: 'hvac-08-04', concept: 'Evacuation removes moisture and non-condensable gases from the system after repair. Connect the vacuum pump through the manifold gauges. Pull vacuum to 500 microns or below. Close the valve and monitor with a micron gauge. The system should hold below 1000 microns for 10 minutes. If it rises above 1000 microns there is either a leak or residual moisture. Triple evacuation (vacuum, break with nitrogen, vacuum, break with nitrogen, final vacuum) is more effective at removing moisture than a single deep vacuum.', keyTerms: [{ term: 'Evacuation', definition: 'Using a vacuum pump to remove moisture and non-condensable gases from the refrigerant circuit.' }, { term: 'Triple Evacuation', definition: 'Pull vacuum, break with nitrogen, repeat three times. More effective at removing moisture.' }, { term: 'Micron Gauge', definition: 'Measures deep vacuum levels. System must hold below 500 microns.' }], diagramRef: 'vacuum-pump', jobApplication: 'Proper evacuation prevents acid formation that destroys compressors. Cutting corners here causes callbacks.', watchFor: ['500 microns or below is the target', 'Monitor for 10 minutes after closing the valve', 'Rising vacuum indicates a leak or moisture'] });
add({ lessonId: 'hvac-08-05', concept: 'Leak repair requirements for high-pressure comfort cooling systems: if the annual leak rate exceeds 10 percent the owner must repair the leak within 30 days. For commercial refrigeration the trigger is 20 percent. Leak rate is calculated as the amount of refrigerant added divided by the total system charge. If repair is not economically feasible the owner can develop a retrofit or retirement plan.', keyTerms: [{ term: 'Leak Rate', definition: 'Annual refrigerant loss as a percentage of total charge. Comfort cooling trigger is 10 percent.' }], jobApplication: 'Document all refrigerant added to a system. This data is needed to calculate leak rates and comply with regulations.', watchFor: ['10 percent for comfort cooling', '20 percent for commercial refrigeration', 'Document every ounce of refrigerant added'] });
add({ lessonId: 'hvac-08-06', concept: 'Recovery equipment lab: connect recovery machine to a system, recover refrigerant to required levels, weigh the recovered amount, properly handle the recovery cylinder. Practice connecting manifold gauges, operating the recovery machine, monitoring pressures during recovery, and verifying recovery is complete.', keyTerms: [], diagramRef: 'recovery-machine', jobApplication: 'You will use recovery equipment on every major repair. Speed and proper technique matter.', watchFor: ['Never overfill recovery cylinders past 80 percent', 'Verify recovery is complete before opening the system', 'Weigh and record the amount recovered'] });
add({ lessonId: 'hvac-08-07', concept: 'EPA 608 Type II practice exam covering high-pressure system identification, recovery requirements by charge size, leak detection methods, evacuation procedures, leak repair requirements, and recovery equipment operation. 25 questions, 70 percent to pass.', keyTerms: [], jobApplication: 'Type II is the certification you will use most in your career.', watchFor: ['Know recovery levels for under and over 200 lbs', 'Know leak repair trigger rates', 'Know evacuation target and verification procedure'] });

// MODULE 9
add({ lessonId: 'hvac-09-01', concept: 'Type III covers low-pressure systems primarily centrifugal chillers used in large commercial buildings. These systems use refrigerants like R-11, R-123, and R-245fa that boil at temperatures above typical conditions at atmospheric pressure. Because of this the systems operate below atmospheric pressure (in a vacuum) during normal operation. This means air leaks INTO the system rather than refrigerant leaking out.', keyTerms: [{ term: 'Low-Pressure System', definition: 'Operates below atmospheric pressure. Air leaks in rather than refrigerant leaking out.' }, { term: 'Centrifugal Chiller', definition: 'Large commercial cooling system using a centrifugal compressor and low-pressure refrigerant.' }], jobApplication: 'Type III is less common for residential technicians but required for Universal certification and commercial building work.', watchFor: ['Low-pressure systems operate in a vacuum', 'Air leaks IN not refrigerant leaks OUT', 'R-123 replaced R-11 in most chillers'] });
add({ lessonId: 'hvac-09-02', concept: 'Type III recovery requirements: systems under 200 lbs recover to 0 psig. Systems 200 lbs or more recover to 25 mm Hg absolute. These levels are different from Type II because low-pressure systems operate differently. Recovery from low-pressure systems is slower because the refrigerant is at or below atmospheric pressure and must be heated or pressurized to move it.', keyTerms: [{ term: '25 mm Hg Absolute', definition: 'Recovery target for low-pressure systems 200 lbs or more. Measured in absolute pressure.' }], jobApplication: 'Low-pressure recovery requires patience and proper technique.', watchFor: ['Under 200 lbs = 0 psig', 'Over 200 lbs = 25 mm Hg absolute', 'Recovery is slower than high-pressure systems'] });
add({ lessonId: 'hvac-09-03', concept: 'A purge unit removes air and non-condensable gases that leak into low-pressure systems. Since the system operates below atmospheric pressure air constantly tries to enter through any imperfection in seals, gaskets, or joints. The purge unit monitors the condenser and removes accumulated air. High purge unit run time indicates excessive air leaks that need to be found and repaired.', keyTerms: [{ term: 'Purge Unit', definition: 'Removes air and non-condensables that leak into low-pressure systems.' }], jobApplication: 'Monitoring purge unit run time is a key maintenance indicator for chiller health.', watchFor: ['High purge run time means excessive air leaks', 'Air in the system raises head pressure and reduces efficiency', 'Find and fix leaks rather than relying on the purge unit'] });
add({ lessonId: 'hvac-09-04', concept: 'Water is the enemy of low-pressure systems. Many chillers have water-cooled condensers and water-chilled evaporators with water flowing through tubes inside the refrigerant vessel. A tube leak allows water into the refrigerant circuit causing hydrolysis — water reacting with refrigerant to form acid. This acid destroys motor windings, bearings, and seals. Detecting water contamination early through oil analysis prevents catastrophic damage.', keyTerms: [{ term: 'Hydrolysis', definition: 'Water reacting with refrigerant to form hydrochloric or hydrofluoric acid.' }], jobApplication: 'Regular oil analysis on chillers catches water contamination before it destroys the compressor.', watchFor: ['Water in the system forms acid', 'Oil analysis detects contamination early', 'Tube leaks are the most common water entry point'] });
add({ lessonId: 'hvac-09-05', concept: 'Rupture discs are safety devices on low-pressure vessels that burst to relieve pressure if it exceeds safe limits. They prevent catastrophic vessel failure. Once a rupture disc bursts it must be replaced. Never plug or bypass a ruptured disc. The biggest risk when evacuating a chiller is freezing the water in the tubes if water has not been drained. Ice expansion can rupture the tubes causing an extremely expensive repair.', keyTerms: [{ term: 'Rupture Disc', definition: 'Safety device that bursts to relieve dangerous pressure. Must be replaced after activation.' }], jobApplication: 'Always drain water from chiller tubes before deep evacuation to prevent freeze damage.', watchFor: ['Never bypass a ruptured disc', 'Drain water before evacuating', 'Ice expansion ruptures tubes'] });
add({ lessonId: 'hvac-09-06', concept: 'EPA 608 Type III practice exam covering low-pressure system operation, recovery requirements, purge units, water contamination, rupture discs, and chiller-specific safety. 25 questions, 70 percent to pass.', keyTerms: [], jobApplication: 'Type III completes your Universal certification when combined with Core, Type I, and Type II.', watchFor: ['Know recovery levels for low-pressure systems', 'Know purge unit function', 'Know the water freezing risk during evacuation'] });

// MODULE 10
add({ lessonId: 'hvac-10-01', concept: 'Core section review covering ozone depletion science, Montreal Protocol timeline, Clean Air Act Section 608 requirements, venting prohibition and penalties, refrigerant safety hazards, pressure-temperature fundamentals, and recovery/recycling/reclamation definitions. This review consolidates everything from Module 6.', keyTerms: [], jobApplication: 'The Core section is the foundation. Every other section builds on Core knowledge.', watchFor: ['Review CFC/HCFC/HFC phase-out timeline', 'Know penalty amounts', 'Know all three R definitions'] });
add({ lessonId: 'hvac-10-02', concept: 'Side-by-side comparison of Type I, II, and III requirements. Recovery levels, leak repair triggers, equipment types, and system examples for each type. Understanding the differences between types is critical because the Universal exam tests all three and many questions require you to distinguish between them.', keyTerms: [], jobApplication: 'The Universal exam tests your ability to distinguish between types. Confusion between Type II and III recovery levels is the most common exam failure.', watchFor: ['Type II under 200 lbs = 0 psig, over 200 lbs = 10 in Hg vacuum', 'Type III under 200 lbs = 0 psig, over 200 lbs = 25 mm Hg absolute', 'Do not confuse inches Hg with mm Hg'] });
add({ lessonId: 'hvac-10-03', concept: 'Full-length Core practice exam simulating actual test conditions. 25 questions, timed, 70 percent to pass.', keyTerms: [], jobApplication: 'Practice under test conditions builds confidence and identifies weak areas.', watchFor: ['Time yourself', 'Review missed questions thoroughly'] });
add({ lessonId: 'hvac-10-04', concept: 'Full-length Type I practice exam. 25 questions covering small appliance definitions, recovery requirements, equipment types, and disposal rules.', keyTerms: [], jobApplication: 'Identify which Type I topics you need to review before the real exam.', watchFor: ['Focus on recovery percentages', 'Know system-dependent vs self-contained'] });
add({ lessonId: 'hvac-10-05', concept: 'Full-length Type II practice exam. 25 questions covering high-pressure systems, recovery levels, leak detection, evacuation, and leak repair requirements.', keyTerms: [], jobApplication: 'Type II has the most questions relevant to your daily work.', watchFor: ['Recovery levels by charge size', 'Evacuation target and verification', 'Leak repair trigger rates'] });
add({ lessonId: 'hvac-10-06', concept: 'Full-length Type III practice exam. 25 questions covering low-pressure systems, chillers, purge units, water contamination, and rupture discs.', keyTerms: [], jobApplication: 'Type III is often the section students struggle with most because they have less hands-on experience with chillers.', watchFor: ['Low-pressure systems operate below atmospheric', 'Purge units remove air that leaks IN', 'Water freezing risk during evacuation'] });
add({ lessonId: 'hvac-10-07', concept: 'Complete 100-question Universal practice exam combining all four sections. Simulates actual EPA 608 exam conditions. You must pass each section independently with 70 percent. This is your final preparation before the proctored exam in Module 16.', keyTerms: [], jobApplication: 'Treat this like the real exam. Your score here predicts your actual exam performance.', watchFor: ['Must pass EACH section independently', 'Review every missed question', 'Take the exam again if you score below 80 percent on any section'] });

// MODULE 11
add({ lessonId: 'hvac-11-01', concept: 'Three charging methods: Subcooling method for TXV systems — measure liquid line pressure, convert to saturation temp, measure actual liquid line temp, subcooling equals saturation minus actual. Target is typically 10-15F per manufacturer spec. Superheat method for piston systems — use the manufacturer charging chart based on outdoor temp and indoor wet bulb. Weigh-in method — evacuate completely then add exact nameplate charge by weight using a refrigerant scale. Each method has specific conditions where it is most accurate.', keyTerms: [{ term: 'Subcooling Method', definition: 'Charging method for TXV systems. Target typically 10-15F.' }, { term: 'Weigh-In Method', definition: 'Add exact nameplate charge by weight after complete evacuation.' }], diagramRef: 'system-diagnostic-points', jobApplication: 'Using the wrong charging method is one of the most common technician errors. It leads to overcharge or undercharge and callbacks.', watchFor: ['TXV = subcooling method', 'Piston = superheat method with charging chart', 'Weigh-in only works after complete evacuation'] });
add({ lessonId: 'hvac-11-02', concept: 'System diagnostics using gauge readings: both pressures high = overcharge or non-condensables. Both pressures low = undercharge. Low suction high discharge = airflow restriction. High suction low discharge = compressor weakness. Normal suction high discharge = dirty condenser. Low suction normal discharge = restricted metering device. Always verify airflow before interpreting pressures because airflow problems mimic charge problems.', keyTerms: [{ term: 'Non-Condensables', definition: 'Air or nitrogen in the system. Takes up condenser space raising head pressure.' }], diagramRef: 'system-diagnostic-points', jobApplication: 'Pattern recognition with gauge readings is the core diagnostic skill. The faster you can read the pattern the faster you solve the problem.', watchFor: ['Always verify airflow FIRST', 'Both pressures tell a story together', 'Non-condensables cause high head pressure with normal suction'] });
add({ lessonId: 'hvac-11-03', concept: 'Leak detection lab: practice using electronic leak detectors, UV dye systems, soap bubbles, and nitrogen pressure testing on systems with known leaks. Learn to systematically check common leak points: service valve cores, flare connections, braze joints, evaporator coil, condenser coil, and Schrader valves. Document leak location and repair method.', keyTerms: [], diagramRef: 'system-diagnostic-points', jobApplication: 'Finding leaks efficiently saves time and money. Systematic checking of common leak points is faster than random searching.', watchFor: ['Check service valve cores first — most common leak point', 'Electronic detectors must be calibrated before use', 'Document the leak location for the service report'] });
add({ lessonId: 'hvac-11-04', concept: 'Recovery and evacuation lab: recover refrigerant from a system using approved equipment, weigh and record the amount recovered, perform a nitrogen pressure test, evacuate to 500 microns, verify vacuum holds for 10 minutes, then recharge to manufacturer specification. Practice the complete sequence from start to finish.', keyTerms: [], diagramRef: 'vacuum-pump', jobApplication: 'This sequence — recover, repair, pressure test, evacuate, charge — is the standard procedure for every major refrigerant-side repair.', watchFor: ['Never skip the pressure test', 'Evacuation to 500 microns minimum', 'Verify vacuum holds before charging'] });
add({ lessonId: 'hvac-11-05', concept: 'Quiz covering charging methods, gauge reading interpretation, leak detection techniques, recovery procedures, and evacuation standards.', keyTerms: [], jobApplication: 'Refrigerant handling skills are tested on the journeyman exam and evaluated by every employer.', watchFor: ['Know which charging method for which metering device', 'Know gauge reading patterns and what they indicate', 'Know evacuation target and verification procedure'] });

// MODULE 12
add({ lessonId: 'hvac-12-01', concept: 'Ductwork design determines system performance. Supply ducts carry conditioned air to rooms. Return ducts bring air back. Total external static pressure (TESP) measures the resistance the blower must overcome. Maximum TESP for most residential systems is 0.50 inches water column. Undersized ducts cause high static pressure, noise, reduced airflow, and comfort complaints. Oversized ducts waste space and money. Duct leaks in unconditioned spaces (attics, crawlspaces) waste 20-30 percent of conditioned air.', keyTerms: [{ term: 'TESP', definition: 'Total External Static Pressure. Sum of supply and return static. Maximum 0.50 in w.c. for most residential.' }, { term: 'CFM', definition: 'Cubic Feet per Minute. Airflow volume. Typical residential is 400 CFM per ton of cooling.' }], diagramRef: 'duct-distribution', jobApplication: 'Many comfort complaints are duct problems not equipment problems. Measuring static pressure identifies duct issues.', watchFor: ['0.50 in w.c. maximum TESP', '400 CFM per ton is the standard airflow target', 'Duct leaks in attics waste enormous energy'] });
add({ lessonId: 'hvac-12-02', concept: 'Manual J calculates the heating and cooling load of a building based on insulation, windows, orientation, climate, and occupancy. The result determines the correct equipment size in tons (1 ton = 12,000 BTU/hr). Oversized equipment short-cycles causing poor humidity control and uneven temperatures. Undersized equipment runs continuously and cannot maintain comfort on extreme days. Manual D sizes the ductwork based on the Manual J load calculation. Manual S selects the specific equipment model.', keyTerms: [{ term: 'Manual J', definition: 'ACCA load calculation determining required heating and cooling capacity.' }, { term: 'Ton', definition: 'Unit of cooling capacity. 1 ton = 12,000 BTU per hour.' }, { term: 'Short Cycling', definition: 'System turning on and off too frequently. Caused by oversized equipment.' }], jobApplication: 'Understanding load calculations helps you identify improperly sized systems — a common cause of comfort complaints.', watchFor: ['Bigger is NOT better — oversized systems cause humidity problems', '1 ton = 12,000 BTU/hr', 'Manual J before Manual D before Manual S'] });
add({ lessonId: 'hvac-12-03', concept: 'Brazing joins copper tubing using a filler metal that melts above 840F. Silver-bearing brazing alloys (such as Silfos) are used for copper-to-copper joints. Always flow dry nitrogen through the tubing during brazing to prevent copper oxide formation inside. Copper oxide flakes contaminate the system and clog metering devices. Soldering uses lower temperatures (below 840F) and is used for water piping not refrigerant lines. Proper joint preparation: cut square, deburr inside and outside, clean with emery cloth, apply flux if required, heat the joint evenly, and let the filler metal flow by capillary action.', keyTerms: [{ term: 'Brazing', definition: 'Joining copper tubing with filler metal above 840F. Used for refrigerant lines.' }, { term: 'Nitrogen Purge', definition: 'Flowing dry nitrogen through tubing during brazing to prevent copper oxide formation.' }], jobApplication: 'A bad braze joint leaks refrigerant. A joint brazed without nitrogen purge contaminates the system. Both cause callbacks.', watchFor: ['ALWAYS purge with nitrogen during brazing', 'Heat the tube not the filler metal', 'Deburr inside the tube to prevent restrictions'] });
add({ lessonId: 'hvac-12-04', concept: 'Line set installation connects the outdoor and indoor units with copper refrigerant lines. The liquid line (smaller) carries warm high-pressure liquid. The suction line (larger) carries cold low-pressure vapor and must be insulated. Proper installation: measure and cut to length, deburr, make flare connections or braze joints, pressure test with nitrogen, evacuate to 500 microns, and charge. Line sets must be supported every 6-8 feet and protected from physical damage.', keyTerms: [{ term: 'Line Set', definition: 'Pre-insulated copper tubing pair connecting outdoor and indoor units.' }, { term: 'Flare Connection', definition: 'Mechanical joint using a flared tube end and flare nut. No heat required.' }], jobApplication: 'Clean line set installation prevents leaks and contamination. Sloppy work causes callbacks.', watchFor: ['Insulate the suction line completely', 'Support lines every 6-8 feet', 'Pressure test before evacuating'] });
add({ lessonId: 'hvac-12-05', concept: 'System commissioning verifies everything works correctly after installation. Checklist: verify refrigerant charge using superheat or subcooling method. Measure total external static pressure (must be under 0.50 in w.c.). Measure temperature split at supply and return (14-22F for cooling). Measure amp draw on compressor and blower (compare to nameplate). Test all safety controls. Verify thermostat operation in all modes. Document everything on the commissioning form.', keyTerms: [{ term: 'Commissioning', definition: 'Systematic verification that all system components are installed and operating correctly.' }], jobApplication: 'Proper commissioning prevents callbacks. A system that is not commissioned properly will have problems within the first season.', watchFor: ['Check TESP, temperature split, amp draw, and charge', 'Test ALL modes: cooling, heating, fan only', 'Document everything'] });
add({ lessonId: 'hvac-12-06', concept: 'Quiz covering ductwork design, Manual J basics, brazing and soldering, line set installation, and system commissioning procedures.', keyTerms: [], jobApplication: 'Installation skills are essential for new construction and equipment replacement jobs.', watchFor: ['Know TESP limits', 'Know why nitrogen purge is required during brazing', 'Know the commissioning checklist'] });

// MODULE 13
add({ lessonId: 'hvac-13-01', concept: 'Systematic troubleshooting follows a logical process instead of guessing. Step 1: Verify the complaint — what exactly is the customer experiencing? Step 2: Check the simple things first — thermostat settings, power, filter. Step 3: Gather data — measure temperatures, pressures, amp draw, voltage. Step 4: Analyze the data — compare measurements to normal values. Step 5: Identify the root cause — not just the symptom. Step 6: Repair and verify — fix the problem and confirm the system operates correctly. Step 7: Document — write the service report. Most callbacks happen because technicians skip steps 1, 5, or 7.', keyTerms: [{ term: 'Root Cause', definition: 'The underlying reason for the failure, not just the symptom. A frozen coil is a symptom. Low charge or dirty filter is the root cause.' }], diagramRef: 'troubleshooting-flowchart', jobApplication: 'Systematic troubleshooting is what separates a professional technician from a parts changer. Employers value technicians who find root causes.', watchFor: ['Always verify the complaint first', 'Check simple things before connecting gauges', 'Find the ROOT CAUSE not just the symptom'] });
add({ lessonId: 'hvac-13-02', concept: 'Common AC failures and their diagnostic patterns. No cooling at all: check power, contactor, capacitor, compressor. System runs but does not cool: check charge (superheat/subcooling), airflow (filter, blower), and metering device. Frozen evaporator: low airflow (dirty filter) or low charge (leak). Short cycling: oversized system, low charge tripping low-pressure switch, or thermostat location. High electric bills: dirty condenser, low charge causing long run times, or duct leaks. Water leaks: clogged condensate drain, frozen coil melting, or cracked drain pan.', keyTerms: [{ term: 'Short Cycling', definition: 'System turning on and off rapidly. Causes include oversized equipment, low charge, and thermostat issues.' }], diagramRef: 'troubleshooting-flowchart', jobApplication: 'Pattern recognition speeds up diagnosis. After enough service calls you will recognize common failure patterns immediately.', watchFor: ['No cooling = power, contactor, capacitor, compressor', 'Frozen coil = airflow or charge', 'Always check airflow before blaming the charge'] });
add({ lessonId: 'hvac-13-03', concept: 'Common heating failures. No heat from gas furnace: dirty flame sensor (most common), failed igniter, tripped safety switch, gas valve issue. Read the control board fault codes first. Furnace short cycling: dirty filter tripping limit switch, blocked return air, or failed blower motor. No heat from heat pump: stuck reversing valve, low charge, failed compressor, or defrost board failure. Aux heat running constantly: heat pump problem forcing backup heat. Strange smells: possible cracked heat exchanger leaking combustion gases.', keyTerms: [{ term: 'Fault Code', definition: 'LED flash pattern on the furnace control board indicating the specific failure. Always read codes first.' }], diagramRef: 'furnace-breakdown', jobApplication: 'Winter no-heat calls are urgent. Customers are cold and stressed. Fast accurate diagnosis builds your reputation.', watchFor: ['Read fault codes FIRST on every furnace call', 'Dirty flame sensor is the number one no-heat cause', 'Strange smells near a furnace = possible CO leak, test immediately'] });
add({ lessonId: 'hvac-13-04', concept: 'Troubleshooting scenarios lab: work through multiple simulated service calls with different failure modes. Diagnose no-cooling, no-heating, frozen coil, short cycling, and airflow problems using the systematic troubleshooting method. Practice connecting gauges, taking measurements, interpreting data, and identifying root causes.', keyTerms: [], diagramRef: 'troubleshooting-flowchart', jobApplication: 'Simulated scenarios build diagnostic confidence before you face real customers.', watchFor: ['Follow the systematic process every time', 'Document your findings at each step', 'Identify the root cause not just the failed component'] });
add({ lessonId: 'hvac-13-05', concept: 'Customer communication simulation: practice explaining diagnoses and repair options to customers in plain language. Technicians must translate technical findings into terms customers understand. Practice delivering bad news (expensive repairs, safety hazards) professionally. Learn to present repair options with costs and let the customer decide. Never pressure customers or use scare tactics.', keyTerms: [], jobApplication: 'Communication skills directly affect your income. Technicians who communicate well get better reviews, more referrals, and higher tips.', watchFor: ['Use plain language not technical jargon', 'Present options and let the customer decide', 'Never pressure or use scare tactics'] });
add({ lessonId: 'hvac-13-06', concept: 'Quiz covering systematic troubleshooting method, common AC and heating failure patterns, gauge reading interpretation, root cause analysis, and customer communication.', keyTerms: [], jobApplication: 'Troubleshooting is the most tested skill on journeyman exams and job interviews.', watchFor: ['Know the 7-step troubleshooting process', 'Know common failure patterns for AC and heating', 'Know how to interpret gauge readings'] });

// MODULE 14
add({ lessonId: 'hvac-14-01', concept: 'OSHA 10-Hour Construction Safety is delivered through CareerSafe, an authorized OSHA Education Center. You complete the coursework online through CareerSafe\'s platform and receive a DOL wallet card upon passing. The course covers the major hazards HVAC technicians face on job sites. The four leading causes of construction fatalities (the Fatal Four) are falls, struck-by objects, electrocution, and caught-in/between. Together these account for over 60 percent of construction deaths. Fall protection is required at 6 feet in construction. Proper ladder use, scaffolding safety, and personal fall arrest systems prevent fall injuries.', keyTerms: [{ term: 'Fatal Four', definition: 'Falls, struck-by, electrocution, caught-in/between. Over 60 percent of construction deaths.' }, { term: 'Fall Protection', definition: 'Required at 6 feet in construction. Includes guardrails, safety nets, and personal fall arrest systems.' }], jobApplication: 'OSHA 10 is required by most HVAC employers. The DOL wallet card proves you completed the training.', watchFor: ['6 feet is the fall protection trigger in construction', 'Know the Fatal Four', 'OSHA 10 card is required for most job sites'] });
add({ lessonId: 'hvac-14-02', concept: 'Electrical safety for HVAC technicians: lockout/tagout procedures, arc flash awareness, proper use of insulated tools, and working near energized equipment. OSHA requires de-energization and LOTO before working on electrical systems. If energized work is necessary (such as taking measurements) proper PPE including arc-rated clothing and face shields is required. Ground fault circuit interrupters (GFCIs) are required for all temporary power on construction sites.', keyTerms: [{ term: 'Arc Flash', definition: 'Electrical explosion through air causing severe burns. Proper PPE and de-energization prevent it.' }, { term: 'GFCI', definition: 'Ground Fault Circuit Interrupter. Trips in milliseconds if current leaks to ground. Required on construction sites.' }], jobApplication: 'Electrical accidents are the third leading cause of construction death. LOTO saves lives.', watchFor: ['Always LOTO before electrical work', 'Verify zero energy with YOUR meter', 'GFCIs required for all temporary power'] });
add({ lessonId: 'hvac-14-03', concept: 'Hazard communication (HazCom) and the Globally Harmonized System (GHS). Safety Data Sheets (SDS) have 16 standardized sections covering chemical identification, hazards, first aid, fire-fighting, handling, exposure controls, and disposal. GHS pictograms identify hazard types at a glance. HVAC technicians work with refrigerants, brazing fluxes, solvents, and cleaning chemicals that all have SDS requirements. Employers must maintain SDS for every chemical on site and train workers on their contents.', keyTerms: [{ term: 'SDS', definition: 'Safety Data Sheet. 16 sections covering chemical hazards, handling, and emergency procedures.' }, { term: 'GHS Pictogram', definition: 'Standardized symbols identifying chemical hazard types.' }], jobApplication: 'You must know how to find and read an SDS for any chemical you work with.', watchFor: ['16 sections in every SDS', 'Know where SDS are kept on your job site', 'GHS pictograms identify hazard types'] });
add({ lessonId: 'hvac-14-04', concept: 'Confined space entry, excavation safety, scaffolding, and ladder safety. Permit-required confined spaces have limited entry/exit and may contain hazardous atmospheres. HVAC technicians encounter confined spaces in mechanical rooms, boiler rooms, and some crawl spaces. Atmospheric testing is required before entry. Excavation safety applies when installing underground ductwork or piping. Scaffolding must be erected by competent persons and inspected before each use.', keyTerms: [{ term: 'Confined Space', definition: 'Space with limited entry/exit that may contain hazardous atmospheres. Requires permit and atmospheric testing.' }, { term: 'Competent Person', definition: 'OSHA-defined person capable of identifying hazards and authorized to take corrective action.' }], jobApplication: 'Confined space incidents are often fatal. Never enter without proper procedures and atmospheric testing.', watchFor: ['Test atmosphere before entering any confined space', 'Never enter alone', 'Scaffolding must be inspected before each use'] });
add({ lessonId: 'hvac-14-05', concept: 'Fire prevention and hot work permits. Brazing and soldering create fire hazards. Hot work permits are required when working near combustible materials. A fire watch must be maintained for 30 minutes after hot work is completed. Fire extinguisher types: Class A for ordinary combustibles, Class B for flammable liquids, Class C for electrical fires, Class D for combustible metals. Know the PASS technique: Pull pin, Aim at base, Squeeze handle, Sweep side to side.', keyTerms: [{ term: 'Hot Work Permit', definition: 'Required authorization for brazing, welding, or soldering near combustible materials.' }, { term: 'PASS', definition: 'Fire extinguisher technique: Pull, Aim, Squeeze, Sweep.' }], jobApplication: 'HVAC technicians braze copper tubing regularly. Fire prevention is part of every brazing job.', watchFor: ['Fire watch for 30 minutes after hot work', 'Know which extinguisher for which fire type', 'Class C for electrical fires'] });
add({ lessonId: 'hvac-14-06', concept: 'Personal protective equipment selection and use. Safety glasses for all HVAC work. Gloves appropriate to the task: leather for handling sheet metal, heat-resistant for brazing, chemical-resistant for refrigerant handling. Steel-toe boots on all job sites. Hearing protection near compressors and power tools. Respiratory protection when working with chemicals or in dusty environments. Hard hats on construction sites.', keyTerms: [{ term: 'PPE', definition: 'Personal Protective Equipment selected based on the specific hazards of each task.' }], jobApplication: 'PPE is not optional. Employers provide it but you must wear it. Violations result in discipline or termination.', watchFor: ['Match PPE to the specific hazard', 'Safety glasses are required for ALL HVAC work', 'Inspect PPE before each use'] });
add({ lessonId: 'hvac-14-07', concept: 'Rigging and material handling for HVAC equipment. Rooftop units, condensers, and air handlers are heavy. Proper lifting techniques prevent back injuries. Crane and rigging safety for rooftop installations. Forklift safety for warehouse and supply house work. Know equipment weight limits and never exceed them.', keyTerms: [{ term: 'Rigging', definition: 'Using ropes, chains, slings, and cranes to lift and move heavy equipment safely.' }], jobApplication: 'HVAC equipment is heavy. Improper lifting causes career-ending back injuries.', watchFor: ['Know the weight of equipment before lifting', 'Use mechanical assistance for anything over 50 lbs', 'Never stand under a suspended load'] });
add({ lessonId: 'hvac-14-08', concept: 'CareerSafe proctored OSHA 10 final assessment covering all safety topics: Fatal Four, fall protection, electrical safety, HazCom/GHS, confined spaces, fire prevention, PPE, and rigging. Must pass to receive the DOL wallet card.', keyTerms: [], jobApplication: 'The OSHA 10 card is a hiring requirement for most HVAC employers.', watchFor: ['Review all Fatal Four hazards', 'Know fall protection trigger heights', 'Know SDS section count and purpose'] });

// MODULE 15
add({ lessonId: 'hvac-15-01', concept: 'Adult CPR: check for responsiveness, call 911, check for breathing, begin compressions. 30 compressions at 100-120 per minute, 2 inches deep, allowing full chest recoil. 2 rescue breaths after every 30 compressions. Continue until AED arrives or EMS takes over. AED use: power on, attach pads, stand clear during analysis, deliver shock if advised, immediately resume CPR.', keyTerms: [{ term: 'CPR', definition: 'Cardiopulmonary Resuscitation. 30 compressions to 2 breaths at 100-120 per minute.' }, { term: 'AED', definition: 'Automated External Defibrillator. Analyzes heart rhythm and delivers shock if needed.' }], jobApplication: 'HVAC technicians work in extreme heat, at heights, and near electricity. Cardiac events, heat stroke, and electrical shock are real risks.', watchFor: ['100-120 compressions per minute', '2 inches deep with full recoil', 'Stand clear during AED analysis'] });
add({ lessonId: 'hvac-15-02', concept: 'First aid for HVAC-specific injuries: electrical shock (disconnect power first, never touch the victim while energized), burns from brazing and hot surfaces (cool with water, cover with sterile dressing), refrigerant frostbite (warm gradually, do not rub), heat exhaustion and heat stroke (move to shade, cool rapidly, call 911 for heat stroke), cuts from sheet metal (direct pressure, clean wound), and eye injuries from debris or chemicals (flush with water for 15 minutes).', keyTerms: [{ term: 'Heat Stroke', definition: 'Life-threatening emergency. Hot red dry skin, confusion. Call 911 and cool immediately.' }, { term: 'Heat Exhaustion', definition: 'Heavy sweating, weakness, nausea. Move to shade, hydrate, rest.' }], jobApplication: 'Knowing first aid for trade-specific injuries can save your life or a coworkers life.', watchFor: ['Disconnect power BEFORE touching an electrical shock victim', 'Heat stroke is a 911 emergency', 'Flush chemical eye exposure for 15 minutes'] });
add({ lessonId: 'hvac-15-03', concept: 'Resume building for HVAC careers. Your resume should highlight: EPA 608 Universal certification, OSHA 10-Hour card, CPR/AED certification, total training hours (480+), specific skills (brazing, electrical diagnosis, refrigerant handling), and any prior work experience. Use action verbs: diagnosed, repaired, installed, maintained. Keep it to one page. Include a skills section listing tools you can use and systems you can work on.', keyTerms: [], jobApplication: 'Your resume is your first impression. A well-organized resume with credentials listed prominently gets interviews.', watchFor: ['List all three credentials prominently', 'Include total training hours', 'One page maximum'] });
add({ lessonId: 'hvac-15-04', concept: 'Interview preparation for HVAC positions. Common questions: Why did you choose HVAC? What certifications do you have? Describe a time you solved a difficult problem. How do you handle working in extreme conditions? What is your understanding of the apprenticeship process? Bring copies of all certifications. Dress professionally. Ask questions about the company apprenticeship program, advancement opportunities, and training support.', keyTerms: [], jobApplication: 'Preparation is the difference between getting hired and getting passed over. Practice your answers out loud.', watchFor: ['Bring copies of all certifications', 'Ask about their apprenticeship program', 'Dress professionally even for trade jobs'] });
add({ lessonId: 'hvac-15-05', concept: 'Professional conduct and customer service. Arrive on time. Wear a clean uniform. Put on shoe covers before entering a home. Explain what you are doing and why. Present options with costs and let the customer decide. Clean up your work area completely. Follow up if you said you would. Your reputation is your career in this trade. One bad review can cost you dozens of future customers.', keyTerms: [], jobApplication: 'Technical skills get you hired. Professional conduct keeps you employed and builds your reputation.', watchFor: ['First impressions matter — clean uniform, on time', 'Explain in plain language', 'Clean up completely before leaving'] });

// MODULE 16
add({ lessonId: 'hvac-16-01', concept: 'EPA 608 Universal exam preparation. Review all four sections: Core (ozone, regulations, safety), Type I (small appliances, recovery requirements), Type II (high-pressure systems, evacuation, leak repair), Type III (low-pressure systems, chillers, purge units). Focus on areas where you scored lowest on practice exams. The real exam is 100 questions, 25 per section, 70 percent per section to pass.', keyTerms: [], jobApplication: 'This is the certification that allows you to work legally in HVAC. Take it seriously.', watchFor: ['Review your weakest sections', '70 percent per section independently', 'The exam is proctored and timed'] });
add({ lessonId: 'hvac-16-02', concept: 'Proctored EPA 608 Universal exam. 100 multiple-choice questions across 4 sections. You must pass each section independently with 70 percent. If you fail a section you can retake just that section. Universal certification is earned by passing all four sections. The certification never expires once earned.', keyTerms: [], jobApplication: 'After passing you receive your EPA 608 Universal card. Keep it with you at all times — you need it to purchase refrigerant.', watchFor: ['Read each question carefully', 'Eliminate obviously wrong answers first', 'If unsure go with your first instinct'] });
add({ lessonId: 'hvac-16-03', concept: 'Final competency assessment covering all 16 modules. Practical skills demonstration: connect manifold gauges, calculate superheat and subcooling, diagnose a simulated system failure, perform a furnace inspection, read a wiring diagram, and demonstrate proper safety procedures. Written assessment covering all major topics.', keyTerms: [], jobApplication: 'This assessment documents your competency for employers and workforce boards.', watchFor: ['Review all module content', 'Practice hands-on skills', 'Demonstrate safety procedures correctly'] });
add({ lessonId: 'hvac-16-04', concept: 'Career placement preparation. Review your resume with the career services team. Practice mock interviews. Research local HVAC employers. Understand the apprenticeship process: you will work under a licensed journeyman, building OJT hours toward your own license. Starting wages typically range from $16-22 per hour. With experience and additional certifications wages increase to $25-40 per hour.', keyTerms: [{ term: 'Apprenticeship', definition: 'Working under a licensed journeyman while building hours toward your own license.' }], jobApplication: 'The program ends but your career is just beginning. Use every resource available for job placement.', watchFor: ['Start applying before graduation', 'Use the career services team', 'Research employers before interviews'] });
add({ lessonId: 'hvac-16-05', concept: 'Program completion and graduation. Review of credentials earned: EPA 608 Universal, OSHA 10-Hour, CPR/AED. Review of training hours completed (480+). Distribution of completion certificates. Career services introduction and job placement support. Alumni network access for ongoing support and job leads.', keyTerms: [], jobApplication: 'You are now a credentialed HVAC technician. Your next step is OJT placement with a licensed company.', watchFor: ['Verify all credentials are in hand', 'Connect with career services', 'Keep your certifications current'] });
