/**
 * building-services Blueprint
 * 
 * © 2026 Elevate for Humanity
 * All Rights Reserved
 *
 * Version: 1.0.0
 */
/**
 * Building Services Technician Blueprint — Canonical Course
 * One curriculum for both standard and apprenticeship delivery
 */
import type { CredentialBlueprint } from './types';

export const buildingServicesBlueprint: CredentialBlueprint = {
  id: 'building-services-v1',
  version: '1.0.0',
  credentialSlug: 'building-services-technician',
  credentialTitle: 'Building Services Technician Certificate',
  credentialCode: 'IN-BST',
  state: 'Indiana',
  programSlug: 'building-services-technician',
  trackVariants: ['standard', 'apprenticeship'],
  status: 'active',
  skipLqs: false,

  features: {
    enrollmentTypes: ['standard', 'apprentice'],
    apprenticeship: {
      enabled: true,
      rtiHoursRequired: 400,
      ojlHoursRequired: 1600,
      competencyTracking: true,
      employerEvaluations: true,
      skillSignoffs: true,
      rapidsReporting: true,
    },
    certificationPrep: true,
    practiceExams: true,
    discussionBoards: true,
    studyGroups: true,
    careerPathways: true,
    mobileOffline: true,
  },

  generationRules: {
    allowRemediation: true,
    allowExpansionLessons: true,
    maxTotalLessons: 42,
    requiresFinalExam: true,
    requiresUniversalReview: false,
    generatorMode: 'fixed',
  },

  expectedModuleCount: 7,
  expectedLessonCount: 42,

  videoConfig: {
    videoGenerator: 'runway',
    template: 'elevate-slide',
    instructorName: 'Marcus Johnson',
    instructorTitle: 'Building Services Supervisor',
    topBarColor: '#0891b2',
    accentColor: '#06b6d4',
    backgroundColor: '#0f172a',
    ttsVoice: 'onyx',
    ttsSpeed: 0.9,
    slideCount: 5,
    segments: ['intro', 'concept', 'visual', 'application', 'wrapup'],
    generateDalleImage: true,
    dalleImageStyle: 'natural',
  },

  assessmentRules: [
    { assessmentType: 'module', scope: 'all', minQuestions: 5, maxQuestions: 10, passingThreshold: 0.7 },
    { assessmentType: 'final', scope: 'all', minQuestions: 50, maxQuestions: 100, passingThreshold: 0.8 },
  ],

  modules: [
    {
      slug: 'bst-orientation',
      title: 'Program Orientation & Safety Fundamentals',
      orderIndex: 1,
      domainKey: 'orientation',
      minLessons: 4,
      maxLessons: 5,
      quizRequired: true,
      practicalRequired: false,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: false,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: false,
        knowledgeCheckCount: 4,
        scenarioCount: 2,
        flashcardCount: 8,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 1,
      },
      competencies: [
        { competencyKey: 'safety_protocols', isCritical: true, minimumTouchpoints: 2 },
        { competencyKey: 'workplace_safety', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'bst-welcome', title: 'Welcome to Building Services Technology', order: 1, domainKey: 'orientation' },
        { slug: 'bst-safety-overview', title: 'Workplace Safety Fundamentals', order: 2, domainKey: 'orientation' },
        { slug: 'bst-equipment-intro', title: 'Introduction to Building Equipment', order: 3, domainKey: 'orientation' },
        { slug: 'bst-safety-checkpoint', title: 'Safety Fundamentals — Checkpoint', order: 4, domainKey: 'orientation' },
      ],
    },
    {
      slug: 'bst-hvac-basics',
      title: 'HVAC Systems Basics',
      orderIndex: 2,
      domainKey: 'hvac',
      minLessons: 6,
      maxLessons: 8,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: true,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: true,
        knowledgeCheckCount: 5,
        scenarioCount: 2,
        flashcardCount: 10,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 2,
      },
      competencies: [
        { competencyKey: 'hvac_basics', isCritical: true, minimumTouchpoints: 3 },
        { competencyKey: 'equipment_operation', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'bst-hvac-overview', title: 'HVAC System Overview', order: 1, domainKey: 'hvac' },
        { slug: 'bst-thermostats', title: 'Thermostats and Controls', order: 2, domainKey: 'hvac' },
        { slug: 'bst-air-quality', title: 'Indoor Air Quality', order: 3, domainKey: 'hvac' },
        { slug: 'bst-hvac-lab', title: 'HVAC Operation — Lab', order: 4, domainKey: 'hvac' },
        { slug: 'bst-hvac-checkpoint', title: 'HVAC Basics — Checkpoint', order: 5, domainKey: 'hvac' },
      ],
    },
    {
      slug: 'bst-electrical',
      title: 'Electrical Systems',
      orderIndex: 3,
      domainKey: 'electrical',
      minLessons: 5,
      maxLessons: 7,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: false,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: false,
        knowledgeCheckCount: 4,
        scenarioCount: 2,
        flashcardCount: 8,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 1,
      },
      competencies: [
        { competencyKey: 'electrical_safety', isCritical: true, minimumTouchpoints: 2 },
        { competencyKey: 'basic_electrical', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'bst-electrical-basics', title: 'Electrical Fundamentals', order: 1, domainKey: 'electrical' },
        { slug: 'bst-circuit-breakers', title: 'Circuit Breakers and Panels', order: 2, domainKey: 'electrical' },
        { slug: 'bst-electrical-lab', title: 'Electrical Basics — Lab', order: 3, domainKey: 'electrical' },
        { slug: 'bst-electrical-checkpoint', title: 'Electrical Systems — Checkpoint', order: 4, domainKey: 'electrical' },
      ],
    },
    {
      slug: 'bst-plumbing',
      title: 'Plumbing Systems',
      orderIndex: 4,
      domainKey: 'plumbing',
      minLessons: 5,
      maxLessons: 6,
      quizRequired: true,
      practicalRequired: true,
      isCritical: false,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: false,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: false,
        knowledgeCheckCount: 4,
        scenarioCount: 2,
        flashcardCount: 6,
        matchingCount: 1,
        caseStudyCount: 0,
        simulationCount: 1,
      },
      competencies: [
        { competencyKey: 'plumbing_basics', isCritical: false, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'bst-plumbing-overview', title: 'Plumbing System Overview', order: 1, domainKey: 'plumbing' },
        { slug: 'bst-leak-repair', title: 'Basic Leak Repair', order: 2, domainKey: 'plumbing' },
        { slug: 'bst-plumbing-lab', title: 'Plumbing Basics — Lab', order: 3, domainKey: 'plumbing' },
        { slug: 'bst-plumbing-checkpoint', title: 'Plumbing Systems — Checkpoint', order: 4, domainKey: 'plumbing' },
      ],
    },
    {
      slug: 'bst-preventive',
      title: 'Preventive Maintenance',
      orderIndex: 5,
      domainKey: 'maintenance',
      minLessons: 5,
      maxLessons: 7,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: false,
        includeDragDrop: true,
        includeMatching: false,
        includeCaseStudies: true,
        includeSimulations: true,
        includeDecisionTrees: true,
        knowledgeCheckCount: 4,
        scenarioCount: 2,
        flashcardCount: 8,
        matchingCount: 0,
        caseStudyCount: 1,
        simulationCount: 1,
      },
      competencies: [
        { competencyKey: 'preventive_maintenance', isCritical: true, minimumTouchpoints: 2 },
        { competencyKey: 'inspection', isCritical: true, minimumTouchpoints: 1 },
      ],
      lessons: [
        { slug: 'bst-pm-basics', title: 'Preventive Maintenance Fundamentals', order: 1, domainKey: 'maintenance' },
        { slug: 'bst-inspection', title: 'Building Inspection Procedures', order: 2, domainKey: 'maintenance' },
        { slug: 'bst-pm-schedule', title: 'Maintenance Scheduling', order: 3, domainKey: 'maintenance' },
        { slug: 'bst-pm-lab', title: 'Preventive Maintenance — Lab', order: 4, domainKey: 'maintenance' },
        { slug: 'bst-pm-checkpoint', title: 'Preventive Maintenance — Checkpoint', order: 5, domainKey: 'maintenance' },
      ],
    },
    {
      slug: 'bst-customer-service',
      title: 'Customer Service & Communication',
      orderIndex: 6,
      domainKey: 'soft-skills',
      minLessons: 4,
      maxLessons: 5,
      quizRequired: true,
      practicalRequired: false,
      isCritical: false,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: false,
        includeDragDrop: false,
        includeMatching: false,
        includeCaseStudies: true,
        includeSimulations: false,
        includeDecisionTrees: true,
        knowledgeCheckCount: 3,
        scenarioCount: 3,
        flashcardCount: 6,
        matchingCount: 0,
        caseStudyCount: 1,
        simulationCount: 0,
      },
      competencies: [
        { competencyKey: 'communication', isCritical: false, minimumTouchpoints: 2 },
        { competencyKey: 'customer_service', isCritical: false, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'bst-communication', title: 'Professional Communication', order: 1, domainKey: 'soft-skills' },
        { slug: 'bst-work-orders', title: 'Work Order Management', order: 2, domainKey: 'soft-skills' },
        { slug: 'bst-customer-scenarios', title: 'Customer Service Scenarios', order: 3, domainKey: 'soft-skills' },
        { slug: 'bst-soft-skills-checkpoint', title: 'Customer Service — Checkpoint', order: 4, domainKey: 'soft-skills' },
      ],
    },
    {
      slug: 'bst-final-exam',
      title: 'Final Examination',
      orderIndex: 7,
      domainKey: 'exam',
      minLessons: 1,
      maxLessons: 2,
      quizRequired: false,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: false,
        includeScenarios: false,
        includeFlashcards: false,
        includeClickToReveal: false,
        includeDragDrop: false,
        includeMatching: false,
        includeCaseStudies: false,
        includeSimulations: false,
        includeDecisionTrees: false,
        knowledgeCheckCount: 0,
        scenarioCount: 0,
        flashcardCount: 0,
        matchingCount: 0,
        caseStudyCount: 0,
        simulationCount: 0,
      },
      competencies: [],
      lessons: [
        { slug: 'bst-final-exam', title: 'Building Services Technician Final Exam', order: 1, domainKey: 'exam' },
      ],
    },
  ],
};
