/**
 * culinary Blueprint
 * 
 * © 2026 Elevate for Humanity
 * All Rights Reserved
 *
 * Version: 1.0.0
 */
/**
 * Youth Culinary Apprenticeship Blueprint — Canonical Course
 * One curriculum for both standard and apprenticeship delivery
 */
import type { CredentialBlueprint } from './types';

export const culinaryBlueprint: CredentialBlueprint = {
  id: 'culinary-youth-v1',
  version: '1.0.0',
  credentialSlug: 'culinary-arts-youth',
  credentialTitle: 'Culinary Arts Certificate',
  credentialCode: 'IN-CULINARY',
  state: 'Indiana',
  programSlug: 'culinary-youth',
  trackVariants: ['standard', 'apprenticeship'],
  status: 'active',
  skipLqs: false,

  features: {
    enrollmentTypes: ['standard', 'apprentice'],
    apprenticeship: {
      enabled: true,
      rtiHoursRequired: 300,
      ojlHoursRequired: 1700,
      competencyTracking: true,
      employerEvaluations: true,
      skillSignoffs: true,
      rapidsReporting: true,
    },
    certificationPrep: true,
    practiceExams: true,
    discussionBoards: true,
    studyGroups: true,
    careerPathways: true,
    mobileOffline: true,
  },

  generationRules: {
    allowRemediation: true,
    allowExpansionLessons: true,
    maxTotalLessons: 36,
    requiresFinalExam: true,
    requiresUniversalReview: false,
    generatorMode: 'fixed',
  },

  expectedModuleCount: 6,
  expectedLessonCount: 36,

  videoConfig: {
    videoGenerator: 'runway',
    template: 'elevate-slide',
    instructorName: 'Chef Angela Rodriguez',
    instructorTitle: 'Executive Chef & Culinary Instructor',
    topBarColor: '#ea580c',
    accentColor: '#fb923c',
    backgroundColor: '#1c1917',
    ttsVoice: 'shimmer',
    ttsSpeed: 0.95,
    slideCount: 5,
    segments: ['intro', 'concept', 'visual', 'application', 'wrapup'],
    generateDalleImage: true,
    dalleImageStyle: 'food-photography',
  },

  assessmentRules: [
    { assessmentType: 'module', scope: 'all', minQuestions: 5, maxQuestions: 10, passingThreshold: 0.7 },
    { assessmentType: 'final', scope: 'all', minQuestions: 40, maxQuestions: 80, passingThreshold: 0.75 },
  ],

  modules: [
    {
      slug: 'cul-orientation',
      title: 'Kitchen Foundations & Safety',
      orderIndex: 1,
      domainKey: 'orientation',
      minLessons: 5,
      maxLessons: 6,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: false,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: false,
        knowledgeCheckCount: 4,
        scenarioCount: 2,
        flashcardCount: 8,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 1,
      },
      competencies: [
        { competencyKey: 'kitchen_safety', isCritical: true, minimumTouchpoints: 2 },
        { competencyKey: 'food_safety', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'cul-welcome', title: 'Welcome to Culinary Arts', order: 1, domainKey: 'orientation' },
        { slug: 'cul-kitchen-safety', title: 'Kitchen Safety Fundamentals', order: 2, domainKey: 'orientation' },
        { slug: 'cul-food-handling', title: 'Safe Food Handling', order: 3, domainKey: 'orientation' },
        { slug: 'cul-kitchen-lab', title: 'Kitchen Safety — Lab', order: 4, domainKey: 'orientation' },
        { slug: 'cul-safety-checkpoint', title: 'Kitchen Foundations — Checkpoint', order: 5, domainKey: 'orientation' },
      ],
    },
    {
      slug: 'cul-knife-skills',
      title: 'Knife Skills & Preparation',
      orderIndex: 2,
      domainKey: 'technique',
      minLessons: 6,
      maxLessons: 8,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: false,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: true,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: false,
        knowledgeCheckCount: 5,
        scenarioCount: 0,
        flashcardCount: 10,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 2,
      },
      competencies: [
        { competencyKey: 'knife_skills', isCritical: true, minimumTouchpoints: 3 },
        { competencyKey: 'mise_en_place', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'cul-knife-types', title: 'Knife Types and Selection', order: 1, domainKey: 'technique' },
        { slug: 'cul-knife-cuts', title: 'Basic Knife Cuts', order: 2, domainKey: 'technique' },
        { slug: 'cul-advanced-cuts', title: 'Advanced Knife Cuts', order: 3, domainKey: 'technique' },
        { slug: 'cul-mise-en-place', title: 'Mise en Place', order: 4, domainKey: 'technique' },
        { slug: 'cul-knife-lab', title: 'Knife Skills — Lab', order: 5, domainKey: 'technique' },
        { slug: 'cul-knife-checkpoint', title: 'Knife Skills — Checkpoint', order: 6, domainKey: 'technique' },
      ],
    },
    {
      slug: 'cul-cooking-methods',
      title: 'Cooking Methods',
      orderIndex: 3,
      domainKey: 'cooking',
      minLessons: 6,
      maxLessons: 8,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: true,
        includeDragDrop: false,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: true,
        includeDecisionTrees: false,
        knowledgeCheckCount: 5,
        scenarioCount: 2,
        flashcardCount: 12,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 2,
      },
      competencies: [
        { competencyKey: 'cooking_methods', isCritical: true, minimumTouchpoints: 3 },
        { competencyKey: 'temperature_control', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'cul-dry-heat', title: 'Dry Heat Cooking Methods', order: 1, domainKey: 'cooking' },
        { slug: 'cul-moist-heat', title: 'Moist Heat Cooking Methods', order: 2, domainKey: 'cooking' },
        { slug: 'cul-temperatures', title: 'Temperature Control', order: 3, domainKey: 'cooking' },
        { slug: 'cul-seasoning', title: 'Seasoning and Flavoring', order: 4, domainKey: 'cooking' },
        { slug: 'cul-cooking-lab', title: 'Cooking Methods — Lab', order: 5, domainKey: 'cooking' },
        { slug: 'cul-cooking-checkpoint', title: 'Cooking Methods — Checkpoint', order: 6, domainKey: 'cooking' },
      ],
    },
    {
      slug: 'cul-stocks-sauces',
      title: 'Stocks, Sauces & Soups',
      orderIndex: 4,
      domainKey: 'foundations',
      minLessons: 5,
      maxLessons: 6,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: false,
        includeFlashcards: true,
        includeClickToReveal: false,
        includeDragDrop: true,
        includeMatching: true,
        includeCaseStudies: false,
        includeSimulations: false,
        includeDecisionTrees: false,
        knowledgeCheckCount: 4,
        scenarioCount: 0,
        flashcardCount: 8,
        matchingCount: 2,
        caseStudyCount: 0,
        simulationCount: 0,
      },
      competencies: [
        { competencyKey: 'stock_creation', isCritical: true, minimumTouchpoints: 2 },
        { competencyKey: 'sauce_mother', isCritical: true, minimumTouchpoints: 2 },
      ],
      lessons: [
        { slug: 'cul-stocks', title: 'Stocks and Broths', order: 1, domainKey: 'foundations' },
        { slug: 'cul-mother-sauces', title: 'Mother Sauces', order: 2, domainKey: 'foundations' },
        { slug: 'cul-small-sauces', title: 'Small Sauces', order: 3, domainKey: 'foundations' },
        { slug: 'cul-soups', title: 'Soup Types and Preparation', order: 4, domainKey: 'foundations' },
        { slug: 'cul-stocks-lab', title: 'Stocks and Sauces — Lab', order: 5, domainKey: 'foundations' },
      ],
    },
    {
      slug: 'cul-vegetables-grains',
      title: 'Vegetables, Grains & Legumes',
      orderIndex: 5,
      domainKey: 'ingredients',
      minLessons: 5,
      maxLessons: 6,
      quizRequired: true,
      practicalRequired: true,
      isCritical: false,
      interactionSpecs: {
        includeKnowledgeChecks: true,
        includeScenarios: true,
        includeFlashcards: true,
        includeClickToReveal: false,
        includeDragDrop: true,
        includeMatching: false,
        includeCaseStudies: true,
        includeSimulations: false,
        includeDecisionTrees: false,
        knowledgeCheckCount: 4,
        scenarioCount: 2,
        flashcardCount: 8,
        matchingCount: 0,
        caseStudyCount: 1,
        simulationCount: 0,
      },
      competencies: [
        { competencyKey: 'vegetable_prep', isCritical: false, minimumTouchpoints: 2 },
        { competencyKey: 'grain_cooking', isCritical: false, minimumTouchpoints: 1 },
      ],
      lessons: [
        { slug: 'cul-vegetable-basics', title: 'Vegetable Preparation', order: 1, domainKey: 'ingredients' },
        { slug: 'cul-seasonal', title: 'Seasonal Cooking', order: 2, domainKey: 'ingredients' },
        { slug: 'cul-grains', title: 'Grains and Legumes', order: 3, domainKey: 'ingredients' },
        { slug: 'cul-vegetables-lab', title: 'Vegetable Preparation — Lab', order: 4, domainKey: 'ingredients' },
        { slug: 'cul-vegetables-checkpoint', title: 'Vegetables and Grains — Checkpoint', order: 5, domainKey: 'ingredients' },
      ],
    },
    {
      slug: 'cul-final-exam',
      title: 'Final Examination',
      orderIndex: 6,
      domainKey: 'exam',
      minLessons: 1,
      maxLessons: 2,
      quizRequired: false,
      practicalRequired: true,
      isCritical: true,
      interactionSpecs: {
        includeKnowledgeChecks: false,
        includeScenarios: false,
        includeFlashcards: false,
        includeClickToReveal: false,
        includeDragDrop: false,
        includeMatching: false,
        includeCaseStudies: false,
        includeSimulations: false,
        includeDecisionTrees: false,
        knowledgeCheckCount: 0,
        scenarioCount: 0,
        flashcardCount: 0,
        matchingCount: 0,
        caseStudyCount: 0,
        simulationCount: 0,
      },
      competencies: [],
      lessons: [
        { slug: 'cul-final-exam', title: 'Culinary Arts Final Examination', order: 1, domainKey: 'exam' },
      ],
    },
  ],
};
