/**
 * lib/curriculum/blueprints/electrical.ts
 *
 * Electrical Apprenticeship / EL-TECH Certificate — NCCER aligned.
 * SOC: 47-2111.00
 */
import type { CredentialBlueprint } from './types';

export const electricalBlueprint: CredentialBlueprint = {
  id: 'electrical-v1',
  version: '1.0.0',
  credentialSlug: 'electrical-technician',
  credentialTitle: 'Electrical Technician Certificate — NCCER Level 1',
  credentialCode: 'NCCER-EL1',
  state: 'IN',
  programSlug: 'electrical',
  trackVariants: ['standard'],
  status: 'active',
  skipLqs: true,

  generationRules: {
    allowRemediation: true,
    allowExpansionLessons: false,
    maxTotalLessons: 49,
    requiresFinalExam: true,
    requiresUniversalReview: false,
    generatorMode: 'fixed',
  },

  expectedModuleCount: 7,
  expectedLessonCount: 49,

  videoConfig: {
    videoGenerator: 'runway',
    template: 'elevate-slide',
    instructorName: 'Darnell Hayes',
    instructorTitle: 'Journeyman Electrician & NCCER Instructor',
    instructorImagePath: '/images/instructors/darnell-hayes.jpg',
    topBarColor: '#eab308',
    accentColor: '#1e3a5f',
    backgroundColor: '#1e293b',
    ttsVoice: 'onyx',
    ttsSpeed: 0.9,
    slideCount: 5,
    segments: ['intro', 'concept', 'visual', 'application', 'wrapup'],
    generateDalleImage: true,
    dalleImageStyle: 'natural',
    width: 1920,
    height: 1080,
  },

  assessmentRules: [
    { assessmentType: 'module', scope: 'all', minQuestions: 5, maxQuestions: 10, passingThreshold: 0.75 },
    { assessmentType: 'final', scope: 'all', minQuestions: 40, maxQuestions: 60, passingThreshold: 0.75 },
  ],

  modules: [
    {
      slug: 'electrical-safety',
      title: 'Electrical Safety & OSHA Compliance',
      orderIndex: 1,
      domainKey: 'safety',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 6 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['electrical_safety', 'osha_29cfr', 'ppe'],
      lessons: [
        { slug: 'elec-osha-safety', title: 'OSHA Electrical Standards and NFPA 70E Overview', order: 1, domainKey: 'safety' },
        { slug: 'elec-arc-flash', title: 'Arc Flash Hazards, PPE, and Safe Work Practices', order: 2, domainKey: 'safety' },
        { slug: 'elec-lockout-tagout', title: 'Lockout/Tagout (LOTO) Procedures for Electrical Systems', order: 3, domainKey: 'safety' },
        { slug: 'elec-ladder-scaffold', title: 'Ladder Safety and Working at Heights', order: 4, domainKey: 'safety' },
        { slug: 'elec-first-aid-shock', title: 'First Aid for Electrical Shock and Burns', order: 5, domainKey: 'safety' },
        { slug: 'elec-fire-prevention', title: 'Fire Prevention and Electrical Hazard Recognition', order: 6, domainKey: 'safety' },
        { slug: 'elec-safety-checkpoint', title: 'Electrical Safety & OSHA — Checkpoint', order: 7, domainKey: 'safety' },
      ],
    },
    {
      slug: 'electrical-theory',
      title: 'Electrical Theory & Fundamentals',
      orderIndex: 2,
      domainKey: 'theory',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 6 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['dc_circuits', 'ac_circuits', 'ohms_law'],
      lessons: [
        { slug: 'elec-ohms-law', title: 'Ohm\'s Law, Voltage, Current, and Resistance', order: 1, domainKey: 'theory' },
        { slug: 'elec-dc-circuits', title: 'DC Circuits: Series, Parallel, and Series-Parallel', order: 2, domainKey: 'theory' },
        { slug: 'elec-ac-fundamentals', title: 'AC Fundamentals: Sine Wave, Frequency, and Phase', order: 3, domainKey: 'theory' },
        { slug: 'elec-inductance-capacitance', title: 'Inductance, Capacitance, and Impedance', order: 4, domainKey: 'theory' },
        { slug: 'elec-transformers', title: 'Transformer Principles and Applications', order: 5, domainKey: 'theory' },
        { slug: 'elec-electrical-math', title: 'Electrical Math: Power, Energy, and Calculations', order: 6, domainKey: 'theory' },
        { slug: 'elec-theory-checkpoint', title: 'Electrical Theory — Checkpoint', order: 7, domainKey: 'theory' },
      ],
    },
    {
      slug: 'electrical-nec-code',
      title: 'National Electrical Code (NEC)',
      orderIndex: 3,
      domainKey: 'code',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 6 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['nec_articles', 'code_compliance', 'permit_process'],
      lessons: [
        { slug: 'elec-nec-overview', title: 'NEC Structure, Purpose, and How to Use the Code Book', order: 1, domainKey: 'code' },
        { slug: 'elec-nec-residential', title: 'NEC Requirements for Residential Wiring (Articles 210–230)', order: 2, domainKey: 'code' },
        { slug: 'elec-nec-commercial', title: 'NEC Commercial and Industrial Requirements', order: 3, domainKey: 'code' },
        { slug: 'elec-nec-grounding', title: 'Grounding and Bonding Requirements (Article 250)', order: 4, domainKey: 'code' },
        { slug: 'elec-wire-sizing', title: 'Wire Sizing, Ampacity, and Conduit Fill Calculations', order: 5, domainKey: 'code' },
        { slug: 'elec-permits-inspections', title: 'Permits, Inspections, and Code Compliance Process', order: 6, domainKey: 'code' },
        { slug: 'elec-code-checkpoint', title: 'NEC Code — Checkpoint', order: 7, domainKey: 'code' },
      ],
    },
    {
      slug: 'electrical-wiring-methods',
      title: 'Wiring Methods & Installations',
      orderIndex: 4,
      domainKey: 'wiring',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: true, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 5 }, { lessonType: 'lab', requiredCount: 1 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['conduit_bending', 'cable_types', 'device_installation'],
      lessons: [
        { slug: 'elec-conduit-types', title: 'Conduit Types: EMT, Rigid, PVC, and Flexible', order: 1, domainKey: 'wiring' },
        { slug: 'elec-conduit-bending', title: 'Conduit Bending: 90°, Offsets, Saddles, and Back-to-Back', order: 2, domainKey: 'wiring' },
        { slug: 'elec-cable-wiring', title: 'Romex, MC Cable, and NM Wiring Methods', order: 3, domainKey: 'wiring' },
        { slug: 'elec-device-installation', title: 'Installing Outlets, Switches, and Fixtures', order: 4, domainKey: 'wiring' },
        { slug: 'elec-panel-wiring', title: 'Panelboard Layout, Breaker Installation, and Load Center Wiring', order: 5, domainKey: 'wiring' },
        { slug: 'elec-wiring-lab', title: 'Residential Wiring Installation — Lab', order: 6, domainKey: 'wiring' },
        { slug: 'elec-wiring-checkpoint', title: 'Wiring Methods & Installations — Checkpoint', order: 7, domainKey: 'wiring' },
      ],
    },
    {
      slug: 'electrical-motor-controls',
      title: 'Motor Controls & Industrial Electrical',
      orderIndex: 5,
      domainKey: 'motors',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: false,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 6 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['motor_theory', 'starters', 'plc_intro'],
      lessons: [
        { slug: 'elec-motor-theory', title: 'Electric Motor Theory: AC and DC Motors', order: 1, domainKey: 'motors' },
        { slug: 'elec-motor-starters', title: 'Motor Starters, Contactors, and Overload Protection', order: 2, domainKey: 'motors' },
        { slug: 'elec-motor-wiring', title: 'Motor Wiring Diagrams and Connection Terminals', order: 3, domainKey: 'motors' },
        { slug: 'elec-vfd', title: 'Variable Frequency Drives (VFD) Introduction', order: 4, domainKey: 'motors' },
        { slug: 'elec-plc-intro', title: 'Introduction to PLCs and Ladder Logic', order: 5, domainKey: 'motors' },
        { slug: 'elec-industrial-panels', title: 'Industrial Panel Reading and Maintenance', order: 6, domainKey: 'motors' },
        { slug: 'elec-motors-checkpoint', title: 'Motor Controls & Industrial Electrical — Checkpoint', order: 7, domainKey: 'motors' },
      ],
    },
    {
      slug: 'electrical-troubleshooting',
      title: 'Troubleshooting & Test Equipment',
      orderIndex: 6,
      domainKey: 'troubleshooting',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: true, isCritical: false,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 5 }, { lessonType: 'lab', requiredCount: 1 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['multimeter', 'clamp_meter', 'circuit_testing'],
      lessons: [
        { slug: 'elec-multimeter', title: 'Using a Multimeter: Voltage, Resistance, and Continuity Tests', order: 1, domainKey: 'troubleshooting' },
        { slug: 'elec-clamp-meter', title: 'Clamp Meters and Power Quality Analyzers', order: 2, domainKey: 'troubleshooting' },
        { slug: 'elec-circuit-tracing', title: 'Circuit Tracing and Fault Isolation Techniques', order: 3, domainKey: 'troubleshooting' },
        { slug: 'elec-breaker-faults', title: 'Diagnosing Breaker Faults, GFCI, and AFCI Trips', order: 4, domainKey: 'troubleshooting' },
        { slug: 'elec-motor-faults', title: 'Motor Fault Diagnosis: Overheating, Vibration, and Failure', order: 5, domainKey: 'troubleshooting' },
        { slug: 'elec-troubleshoot-lab', title: 'Electrical Fault Simulation and Diagnosis — Lab', order: 6, domainKey: 'troubleshooting' },
        { slug: 'elec-troubleshoot-checkpoint', title: 'Troubleshooting & Test Equipment — Checkpoint', order: 7, domainKey: 'troubleshooting' },
      ],
    },
    {
      slug: 'electrical-exam-prep',
      title: 'Journeyman Exam Prep & Career Readiness',
      orderIndex: 7,
      domainKey: 'exam_prep',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 4 }, { lessonType: 'checkpoint', requiredCount: 1 }, { lessonType: 'exam', requiredCount: 1 }],
      competencies: ['journeyman_exam', 'career_readiness'],
      lessons: [
        { slug: 'elec-journeyman-overview', title: 'Indiana Journeyman Electrician License Requirements', order: 1, domainKey: 'exam_prep' },
        { slug: 'elec-code-calculations', title: 'NEC Code Calculations Practice: Box Fill, Load, and Feeder', order: 2, domainKey: 'exam_prep' },
        { slug: 'elec-theory-review', title: 'Electrical Theory Review: Circuits, Transformers, and Motors', order: 3, domainKey: 'exam_prep' },
        { slug: 'elec-career-paths', title: 'Electrical Career Paths: Apprenticeship, Union, and Contractor', order: 4, domainKey: 'exam_prep' },
        { slug: 'elec-business-basics', title: 'Electrical Contractor Business Basics and Estimating', order: 5, domainKey: 'exam_prep' },
        { slug: 'elec-exam-prep-checkpoint', title: 'Journeyman Exam Prep — Checkpoint', order: 6, domainKey: 'exam_prep' },
        { slug: 'elec-final-exam', title: 'Electrical Technology Comprehensive Final Examination', order: 7, domainKey: 'exam_prep' },
      ],
    },
  ],
};
