/**
 * lib/curriculum/blueprints/medical-assistant.ts
 *
 * Medical Assistant Certificate — NCMA / CCMA aligned.
 * SOC: 31-9092.00
 */
import type { CredentialBlueprint } from './types';

export const medicalAssistantBlueprint: CredentialBlueprint = {
  id: 'medical-assistant-v1',
  version: '1.0.0',
  credentialSlug: 'medical-assistant',
  credentialTitle: 'Medical Assistant Certificate — CCMA Exam Prep',
  credentialCode: 'NHA-CCMA',
  state: 'IN',
  programSlug: 'medical-assistant',
  trackVariants: ['standard'],
  status: 'active',
  skipLqs: true,
  externalCourses: [
    {
      title: 'NHA Certified Clinical Medical Assistant (CCMA) Exam Prep',
      provider: 'National Healthcareer Association',
      url: 'https://www.nhanow.com/certifications/clinical-medical-assistant',
      required: true,
    },
    {
      title: 'NHA Certified EKG Technician (CET) Exam Prep',
      provider: 'National Healthcareer Association',
      url: 'https://www.nhanow.com/certifications/ekg-technician',
      required: false,
    },
  ],

  generationRules: {
    allowRemediation: true,
    allowExpansionLessons: false,
    maxTotalLessons: 49,
    requiresFinalExam: true,
    requiresUniversalReview: false,
    generatorMode: 'fixed',
  },

  expectedModuleCount: 7,
  expectedLessonCount: 49,

  videoConfig: {
    videoGenerator: 'runway',
    template: 'elevate-slide',
    instructorName: 'Diana Torres, CMA',
    instructorTitle: 'Certified Medical Assistant & Healthcare Educator',
    instructorImagePath: '/images/instructors/diana-torres.jpg',
    topBarColor: '#10b981',
    accentColor: '#0f172a',
    backgroundColor: '#f0fdf4',
    ttsVoice: 'nova',
    ttsSpeed: 0.9,
    slideCount: 5,
    segments: ['intro', 'concept', 'visual', 'application', 'wrapup'],
    generateDalleImage: true,
    dalleImageStyle: 'natural',
    width: 1920,
    height: 1080,
  },

  assessmentRules: [
    { assessmentType: 'module', scope: 'all', minQuestions: 5, maxQuestions: 10, passingThreshold: 0.75 },
    { assessmentType: 'final', scope: 'all', minQuestions: 40, maxQuestions: 60, passingThreshold: 0.75 },
  ],

  modules: [
    {
      slug: 'ma-foundations',
      title: 'Medical Assisting Foundations & Professionalism',
      orderIndex: 1,
      domainKey: 'foundations',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 6 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['professionalism', 'medical_law', 'communication'],
      lessons: [
        { slug: 'ma-role-scope', title: 'The Medical Assistant Role, Scope of Practice, and Settings', order: 1, domainKey: 'foundations' },
        { slug: 'ma-professionalism', title: 'Professionalism, Ethics, and Healthcare Team Dynamics', order: 2, domainKey: 'foundations' },
        { slug: 'ma-hipaa', title: 'HIPAA: Patient Privacy, Confidentiality, and Compliance', order: 3, domainKey: 'foundations' },
        { slug: 'ma-medical-law', title: 'Medical Law: Consent, Liability, and Malpractice', order: 4, domainKey: 'foundations' },
        { slug: 'ma-patient-communication', title: 'Patient Communication: Active Listening and Cultural Sensitivity', order: 5, domainKey: 'foundations' },
        { slug: 'ma-workplace-safety', title: 'Workplace Safety: OSHA, Biohazards, and Infection Control Overview', order: 6, domainKey: 'foundations' },
        { slug: 'ma-foundations-checkpoint', title: 'Foundations & Professionalism — Checkpoint', order: 7, domainKey: 'foundations' },
      ],
    },
    {
      slug: 'ma-anatomy-physiology',
      title: 'Anatomy, Physiology & Medical Terminology',
      orderIndex: 2,
      domainKey: 'anatomy',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 6 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['anatomy', 'medical_terms', 'body_systems'],
      lessons: [
        { slug: 'ma-medical-terms', title: 'Medical Terminology: Prefixes, Suffixes, and Root Words', order: 1, domainKey: 'anatomy' },
        { slug: 'ma-integumentary', title: 'Integumentary and Musculoskeletal Systems', order: 2, domainKey: 'anatomy' },
        { slug: 'ma-cardiovascular', title: 'Cardiovascular and Respiratory Systems', order: 3, domainKey: 'anatomy' },
        { slug: 'ma-digestive-urinary', title: 'Digestive and Urinary Systems', order: 4, domainKey: 'anatomy' },
        { slug: 'ma-endocrine-neurological', title: 'Endocrine and Neurological Systems', order: 5, domainKey: 'anatomy' },
        { slug: 'ma-reproductive', title: 'Reproductive System and Pediatric Considerations', order: 6, domainKey: 'anatomy' },
        { slug: 'ma-anatomy-checkpoint', title: 'Anatomy, Physiology & Terminology — Checkpoint', order: 7, domainKey: 'anatomy' },
      ],
    },
    {
      slug: 'ma-clinical-skills',
      title: 'Clinical Skills & Vital Signs',
      orderIndex: 3,
      domainKey: 'clinical',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: true, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 5 }, { lessonType: 'lab', requiredCount: 1 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['vital_signs', 'patient_assessment', 'sterile_technique'],
      lessons: [
        { slug: 'ma-vital-signs', title: 'Vital Signs: Temperature, Pulse, Respiration, and Blood Pressure', order: 1, domainKey: 'clinical' },
        { slug: 'ma-height-weight', title: 'Height, Weight, BMI, and Patient Intake Assessment', order: 2, domainKey: 'clinical' },
        { slug: 'ma-infection-control', title: 'Infection Control: Hand Hygiene, PPE, and Sterile Technique', order: 3, domainKey: 'clinical' },
        { slug: 'ma-medical-asepsis', title: 'Medical and Surgical Asepsis Principles', order: 4, domainKey: 'clinical' },
        { slug: 'ma-physical-exam', title: 'Assisting with Physical Examinations and Positioning', order: 5, domainKey: 'clinical' },
        { slug: 'ma-clinical-lab', title: 'Clinical Skills Practical — Lab', order: 6, domainKey: 'clinical' },
        { slug: 'ma-clinical-checkpoint', title: 'Clinical Skills & Vital Signs — Checkpoint', order: 7, domainKey: 'clinical' },
      ],
    },
    {
      slug: 'ma-phlebotomy-lab',
      title: 'Phlebotomy & Specimen Collection',
      orderIndex: 4,
      domainKey: 'phlebotomy',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: true, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 5 }, { lessonType: 'lab', requiredCount: 1 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['phlebotomy', 'specimen_collection', 'poctt'],
      lessons: [
        { slug: 'ma-venipuncture', title: 'Venipuncture Technique: Equipment, Sites, and Procedure', order: 1, domainKey: 'phlebotomy' },
        { slug: 'ma-capillary-puncture', title: 'Capillary Puncture and Fingerstick Techniques', order: 2, domainKey: 'phlebotomy' },
        { slug: 'ma-specimen-handling', title: 'Specimen Handling, Labeling, and Transport', order: 3, domainKey: 'phlebotomy' },
        { slug: 'ma-urinalysis', title: 'Urinalysis: Collection, Dipstick, and Microscopic Testing', order: 4, domainKey: 'phlebotomy' },
        { slug: 'ma-poctt', title: 'Point-of-Care Testing: Glucose Meters, Rapid Strep, and INR', order: 5, domainKey: 'phlebotomy' },
        { slug: 'ma-phlebotomy-lab', title: 'Phlebotomy Practical Skills — Lab', order: 6, domainKey: 'phlebotomy' },
        { slug: 'ma-phlebotomy-checkpoint', title: 'Phlebotomy & Specimen Collection — Checkpoint', order: 7, domainKey: 'phlebotomy' },
      ],
    },
    {
      slug: 'ma-pharmacology',
      title: 'Pharmacology & Medication Administration',
      orderIndex: 5,
      domainKey: 'pharmacology',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: true, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 5 }, { lessonType: 'lab', requiredCount: 1 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['pharmacology', 'injections', 'medication_math'],
      lessons: [
        { slug: 'ma-drug-classes', title: 'Drug Classifications, Actions, and Adverse Effects', order: 1, domainKey: 'pharmacology' },
        { slug: 'ma-medication-math', title: 'Medication Math: Dosage Calculations and Conversions', order: 2, domainKey: 'pharmacology' },
        { slug: 'ma-oral-medications', title: 'Oral and Topical Medication Administration', order: 3, domainKey: 'pharmacology' },
        { slug: 'ma-injections', title: 'Injections: Intradermal, Subcutaneous, and Intramuscular', order: 4, domainKey: 'pharmacology' },
        { slug: 'ma-immunizations', title: 'Immunization Schedules, Storage, and Administration', order: 5, domainKey: 'pharmacology' },
        { slug: 'ma-medications-lab', title: 'Medication Administration Skills — Lab', order: 6, domainKey: 'pharmacology' },
        { slug: 'ma-pharmacology-checkpoint', title: 'Pharmacology & Medications — Checkpoint', order: 7, domainKey: 'pharmacology' },
      ],
    },
    {
      slug: 'ma-administrative',
      title: 'Administrative & EHR Operations',
      orderIndex: 6,
      domainKey: 'administrative',
      minLessons: 6, maxLessons: 8, quizRequired: true, practicalRequired: false, isCritical: false,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 5 }, { lessonType: 'checkpoint', requiredCount: 1 }],
      competencies: ['ehr', 'scheduling', 'billing_coding'],
      lessons: [
        { slug: 'ma-ehr-systems', title: 'Electronic Health Records: Navigation, Documentation, and Privacy', order: 1, domainKey: 'administrative' },
        { slug: 'ma-scheduling', title: 'Patient Scheduling, Check-In, and Appointment Management', order: 2, domainKey: 'administrative' },
        { slug: 'ma-billing-coding', title: 'Medical Billing and Coding: ICD-10, CPT, and Insurance Basics', order: 3, domainKey: 'administrative' },
        { slug: 'ma-insurance', title: 'Health Insurance Types: HMO, PPO, Medicare, and Medicaid', order: 4, domainKey: 'administrative' },
        { slug: 'ma-medical-records', title: 'Medical Records Management and Release of Information', order: 5, domainKey: 'administrative' },
        { slug: 'ma-administrative-checkpoint', title: 'Administrative & EHR — Checkpoint', order: 6, domainKey: 'administrative' },
      ],
    },
    {
      slug: 'ma-ccma-exam-prep',
      title: 'CCMA Certification Exam Preparation',
      orderIndex: 7,
      domainKey: 'exam_prep',
      minLessons: 7, maxLessons: 9, quizRequired: true, practicalRequired: false, isCritical: true,
      requiredLessonTypes: [{ lessonType: 'lesson', requiredCount: 4 }, { lessonType: 'checkpoint', requiredCount: 1 }, { lessonType: 'exam', requiredCount: 1 }],
      competencies: ['ccma_exam', 'career_readiness'],
      lessons: [
        { slug: 'ma-ccma-overview', title: 'NHA CCMA Exam: Structure, Domains, and Registration', order: 1, domainKey: 'exam_prep' },
        { slug: 'ma-clinical-review', title: 'Clinical Domain Review: High-Frequency Exam Topics', order: 2, domainKey: 'exam_prep' },
        { slug: 'ma-administrative-review', title: 'Administrative Domain Review and Practice Questions', order: 3, domainKey: 'exam_prep' },
        { slug: 'ma-career-paths', title: 'Medical Assisting Career Paths, Specializations, and Advancement', order: 4, domainKey: 'exam_prep' },
        { slug: 'ma-job-search', title: 'Job Search, Resume, and Interview Preparation for MAs', order: 5, domainKey: 'exam_prep' },
        { slug: 'ma-exam-prep-checkpoint', title: 'CCMA Exam Prep — Checkpoint', order: 6, domainKey: 'exam_prep' },
        { slug: 'ma-final-exam', title: 'Medical Assistant Comprehensive Final Examination', order: 7, domainKey: 'exam_prep' },
      ],
    },
  ],
};
