#!/usr/bin/env tsx
/**
 * Final Readiness Check
 * Aggregates all validation checks and produces final report
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

interface CheckResult {
  name: string;
  passed: boolean;
  output: string;
}

const CHECKS = [
  { name: 'Environment Variables', script: 'tsx scripts/validate-env.ts' },
  { name: 'Documentation', script: 'tsx scripts/validate-docs.ts' },
  { name: 'Routes', script: 'tsx scripts/validate-routes.ts' },
  { name: 'Enrollment Flow', script: 'tsx scripts/validate-enrollment.ts' },
];

console.log('🚀 Running final readiness checks...\n');
console.log('='.repeat(60));
console.log();

const results: CheckResult[] = [];

for (const check of CHECKS) {
  console.log(`Running: ${check.name}...`);

  try {
    const output = execSync(check.script, {
      encoding: 'utf8',
      stdio: 'pipe',
    });

    results.push({
      name: check.name,
      passed: true,
      output: output.trim(),
    });

    console.log(`✅ ${check.name} PASSED\n`);
  } catch (error: any) {
    results.push({
      name: check.name,
      passed: false,
      output: error.stdout || error.message,
    });

    console.log(`❌ ${check.name} FAILED\n`);
  }
}

console.log('='.repeat(60));
console.log();

// Generate summary
const passed = results.filter((r) => r.passed).length;
const failed = results.filter((r) => !r.passed).length;
const total = results.length;

console.log('📊 SUMMARY\n');
console.log(`   Total checks: ${total}`);
console.log(`   Passed: ${passed}`);
console.log(`   Failed: ${failed}`);
console.log();

// Generate detailed report
const reportPath = path.join(process.cwd(), 'readiness-report.md');
const timestamp = new Date().toISOString();

let report = `# Platform Readiness Report

**Generated:** ${timestamp}  
**Platform:** Elevate for Humanity LMS  
**Version:** 2.0.0

---

## Summary

- **Total Checks:** ${total}
- **Passed:** ${passed}
- **Failed:** ${failed}
- **Status:** ${failed === 0 ? '✅ READY' : '❌ NOT READY'}

---

## Check Results

`;

for (const result of results) {
  report += `### ${result.passed ? '✅' : '❌'} ${result.name}\n\n`;
  report += '```\n';
  report += result.output;
  report += '\n```\n\n';
}

report += `---

## Verdict

`;

if (failed === 0) {
  report += `**✅ PLATFORM IS READY FOR ENROLLMENT**

All validation checks passed. The platform is ready to accept student enrollments.

### Next Steps:
1. Populate database with seed data (10-15 min)
2. Configure SMTP for email delivery (30-60 min)
3. Test enrollment flow end-to-end
4. Launch enrollment campaign

`;
} else {
  report += `**❌ PLATFORM IS NOT READY**

${failed} validation check(s) failed. Address the issues above before launching enrollment.

### Required Actions:
`;

  for (const result of results) {
    if (!result.passed) {
      report += `- Fix: ${result.name}\n`;
    }
  }

  report += `
After fixing issues, run:
\`\`\`bash
pnpm readiness
\`\`\`
`;
}

report += `
---

**Report generated by:** \`pnpm readiness\`  
**Timestamp:** ${timestamp}
`;

fs.writeFileSync(reportPath, report);

console.log(`📄 Detailed report saved to: readiness-report.md\n`);

// Final verdict
if (failed === 0) {
  console.log('🎉 FINAL VERDICT: READY FOR ENROLLMENT\n');
  process.exit(0);
} else {
  console.log('⚠️  FINAL VERDICT: NOT READY - Fix issues above\n');
  process.exit(1);
}
