#!/usr/bin/env tsx
/**
 * scripts/seed-course-from-blueprint.ts
 *
 * End-to-end course seeder. Reads a blueprint from the registry and writes
 * courses → course_modules → course_lessons via buildCanonicalCourseFromBlueprint.
 *
 * Every lesson row gets:
 *   - lesson_type (inferred from slug suffix)
 *   - activities JSONB (NHA-style activity menu)
 *   - video_config JSONB (locked video format from blueprint)
 *
 * Usage:
 *   pnpm tsx scripts/seed-course-from-blueprint.ts --blueprint hvac-epa608-v1 --program 4226f7f6-fbc1-44b5-83e8-b12ea149e4c7
 *   pnpm tsx scripts/seed-course-from-blueprint.ts --blueprint hvac-epa608-v1 --program 4226f7f6-fbc1-44b5-83e8-b12ea149e4c7 --mode replace
 *
 * Flags:
 *   --blueprint  Blueprint ID or program slug (required)
 *   --program    programs.id to link the course to (required)
 *   --mode       'missing-only' (default, safe to re-run) | 'replace' (wipes and rebuilds)
 *   --dry-run    Print what would be written without touching the DB
 */

import { config } from 'dotenv';
import path from 'path';

// Load .env.local
config({ path: path.resolve(process.cwd(), '.env.local') });

import { createClient } from '@supabase/supabase-js';
import {
  getBlueprintById,
  getBlueprintByProgramSlug,
  getAllBlueprints,
} from '../lib/curriculum/blueprints/index';
import { buildCanonicalCourseFromBlueprint } from '../lib/curriculum/builders/buildCanonicalCourseFromBlueprint';
import { validateBlueprintLessons } from '../lib/curriculum/lqs-validator';

// ── Parse args ────────────────────────────────────────────────────────

const args = process.argv.slice(2);

function getArg(flag: string): string | undefined {
  const idx = args.indexOf(flag);
  return idx !== -1 ? args[idx + 1] : undefined;
}

const blueprintArg = getArg('--blueprint');
const programId = getArg('--program');
const modeArg = getArg('--mode') ?? 'missing-only';
const dryRun = args.includes('--dry-run');
const listBlueprints = args.includes('--list');

if (!listBlueprints && (!blueprintArg || !programId)) {
  console.error(
    '\nUsage: pnpm tsx scripts/seed-course-from-blueprint.ts --blueprint <id> --program <programId> [--mode replace|missing-only] [--dry-run]',
  );
  console.error('       pnpm tsx scripts/seed-course-from-blueprint.ts --list\n');
  process.exit(1);
}

if (modeArg !== 'replace' && modeArg !== 'missing-only') {
  console.error('--mode must be "replace" or "missing-only"');
  process.exit(1);
}

// ── Resolve blueprint ─────────────────────────────────────────────────

// ── Run ───────────────────────────────────────────────────────────────

async function main() {
  if (listBlueprints) {
    console.log('\nAvailable blueprints:');
    const blueprints = await getAllBlueprints();
    blueprints.forEach((bp) => {
      console.log(`  ${bp.id.padEnd(30)} slug=${bp.programSlug}  modules=${bp.modules.length}`);
    });
    process.exit(0);
  }

  const byId = await getBlueprintById(blueprintArg!);
  const blueprint = byId ?? (await getBlueprintByProgramSlug(blueprintArg!));

  if (!blueprint) {
    console.error(`\nNo blueprint found for "${blueprintArg}"`);
    console.error('Run with --list to see available blueprints.\n');
    process.exit(1);
  }

  // ── Dry run ───────────────────────────────────────────────────────────

  if (dryRun) {
    console.log('\n── DRY RUN ──────────────────────────────────────────────');
    console.log(`Blueprint : ${blueprint.id} v${blueprint.version}`);
    console.log(`Program   : ${programId}`);
    console.log(`Mode      : ${modeArg}`);
    console.log(`Modules   : ${blueprint.modules.length}`);
    let totalLessons = 0;
    blueprint.modules.forEach((mod) => {
      const count = mod.lessons?.length ?? 0;
      totalLessons += count;
      console.log(
        `  [${mod.orderIndex}] ${mod.title} — ${count > 0 ? count + ' lessons' : `${mod.minLessons}–${mod.maxLessons} lessons (generated)`}`,
      );
    });
    console.log(
      `Lessons   : ${totalLessons > 0 ? totalLessons : 'generated by AI (no pre-defined lessons)'}`,
    );
    console.log(
      `VideoConfig: ${blueprint.videoConfig ? `${blueprint.videoConfig.template} / ${blueprint.videoConfig.instructorName}` : 'none'}`,
    );
    console.log('─────────────────────────────────────────────────────────\n');
    process.exit(0);
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );

  console.log(`\nSeeding course from blueprint: ${blueprint.id}`);
  console.log(`Program ID : ${programId}`);
  console.log(`Mode       : ${modeArg}`);
  console.log(`Modules    : ${blueprint.modules.length}`);
  console.log('');

  // ── LQS validation — hard gate before any DB writes ──────────────────
  const allLessons = blueprint.modules.flatMap((m) => m.lessons ?? []);
  if (allLessons.length > 0 && !blueprint.skipLqs) {
    console.log(`Running LQS validation on ${allLessons.length} lessons...`);
    const lqsResults = validateBlueprintLessons(allLessons);
    const failures = lqsResults.filter((r) => !r.passed);

    if (failures.length > 0) {
      console.error(
        `\n❌ LQS validation failed — ${failures.length} lesson(s) do not meet the quality standard.\n`,
      );
      for (const f of failures) {
        console.error(`  ${f.slug} (${f.wordCount} words, ${f.questionCount} questions)`);
        for (const v of f.violations) {
          console.error(`    [${v.category}] ${v.rule}`);
          console.error(`      ${v.detail}`);
        }
      }
      console.error('\nFix all violations before seeding. No DB writes were made.\n');
      process.exit(1);
    }
    console.log(`✅ LQS passed — all ${allLessons.length} lessons meet quality standard.\n`);
  } else if (blueprint.skipLqs) {
    console.log(`⚠️  LQS skipped — blueprint.skipLqs=true (non-cosmetology program).\n`);
  }
  // ─────────────────────────────────────────────────────────────────────

  const result = await buildCanonicalCourseFromBlueprint({
    blueprint,
    programId: programId!,
    courseSlug: blueprint.programSlug,
    mode: modeArg as 'replace' | 'missing-only',
  });

  const totalAttempted = result.lessonCount + result.contentFailures.length;

  console.log('\n── Seed result ──────────────────────────────────────────');
  console.log(`   Course ID    : ${result.courseId}`);
  console.log(`   Modules      : ${result.moduleCount}`);
  console.log(`   Inserted     : ${result.lessonCount} / ${totalAttempted} lessons`);
  console.log(`   Skipped      : ${result.skipped} (already exist)`);
  console.log(`   Content fail : ${result.contentFailures.length} (no row created)`);

  if (result.contentFailures.length > 0) {
    console.log(`\n❌ Content failures — these lessons were NOT inserted:\n`);
    result.contentFailures.forEach((f) => {
      console.log(`   ${f.slug} [${f.stepType}] "${f.title}"`);
      f.violations.forEach((v) => console.log(`     • ${v.field}: ${v.reason}`));
    });
    console.log('');
  }

  if (result.warnings.length > 0) {
    console.log(`\n⚠️  Warnings (${result.warnings.length}):`);
    result.warnings.forEach((w) => console.log(`   - ${w}`));
  }

  if (result.contentFailures.length > 0) {
    console.log(
      '❌ Seed completed with content failures. Fix the blueprint lesson refs above and re-run.\n',
    );
    process.exit(1);
  }

  console.log('✅ All lessons inserted with production content.\n');

  // ── Certification pathway ─────────────────────────────────────────────
  // Write program_certification_pathways row so auto_create_exam_authorization
  // trigger can fire when a learner completes all checkpoints.
  if (blueprint.certificationPathway) {
    const cp = blueprint.certificationPathway;
    const { error: pathwayError } = await supabase.from('program_certification_pathways').upsert(
      {
        program_id: programId,
        certification_body_id: cp.certificationBodyId,
        credential_name: cp.credentialName,
        credential_abbreviation: cp.credentialAbbrev,
        exam_fee_cents: cp.examFeeCents ?? 0,
        fee_payer: cp.feePayer ?? 'student',
        eligibility_review_required: cp.eligibilityReview ?? false,
        is_primary: cp.isPrimary ?? true,
        is_active: true,
        sort_order: 1,
      },
      { onConflict: 'program_id,certification_body_id', ignoreDuplicates: false },
    );

    if (pathwayError) {
      console.warn(`⚠️  Certification pathway upsert failed: ${pathwayError.message}`);
      console.warn(
        '   The course was seeded successfully but exam authorization will not auto-fire.',
      );
      console.warn('   Insert a row into program_certification_pathways manually to fix.\n');
    } else {
      console.log(
        `✅ Certification pathway seeded: ${cp.credentialName} (${cp.credentialAbbrev})\n`,
      );
    }
  } else {
    console.log('ℹ️  No certificationPathway defined in blueprint — skipping pathway seed.');
    console.log('   Add certificationPathway to the blueprint if exam authorization is needed.\n');
  }
}

main().catch((err) => {
  console.error('\n❌ Seed failed:', err.message);
  process.exit(1);
});
