-- Program Cleanup & Canonicalization
--
-- 108 programs exist in the DB. This migration:
--   1. Archives AI test artifacts (auto-generated slugs)
--   2. Archives exact duplicates (same program, different slug)
--   3. Activates programs that should be active
--   4. Normalizes slug aliases to canonical slugs
--   5. Ensures all canonical programs have correct status
--
-- SAFE: uses UPDATE SET status='archived' — no rows deleted.
-- Apply in Supabase Dashboard → SQL Editor.
-- Review the SELECT statements at the bottom to verify before applying.

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 1: Archive AI test artifacts
-- These were auto-generated by the AI course builder and are not real programs.
-- ─────────────────────────────────────────────────────────────────────────────

UPDATE public.programs
SET status = 'archived', is_active = false, published = false
WHERE slug IN (
  'ai-forklift-safety-certification-1774495387731',
  'ai-advanced-project-management-1774494313718',
  'pub-path-test-1773772605941',
  'gen-acceptance-test-elec-1773765247614'
);

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 2: Archive duplicate/legacy slugs
-- These are older versions of programs that now have canonical slugs.
-- The canonical version is kept; the duplicate is archived.
-- ─────────────────────────────────────────────────────────────────────────────

UPDATE public.programs
SET status = 'archived', is_active = false, published = false
WHERE slug IN (
  -- CNA duplicates (canonical: cna)
  'cna-training',
  'cna-cert',

  -- CPR duplicates (canonical: cpr-first-aid)
  'cpr-cert',

  -- HVAC duplicates (canonical: hvac-technician)
  'hvac-2024',

  -- Barber duplicates (canonical: barber-apprenticeship)
  'barber',
  'barber-2024',

  -- Cosmetology duplicates (canonical: cosmetology-apprenticeship)
  'cosmetology',

  -- Esthetician duplicates (canonical: esthetician-apprenticeship)
  -- Note: 'esthetician' (professional, 24wk, $5120) is KEPT as active — it is a
  -- distinct non-apprenticeship program. Only the apprenticeship slug variants are dupes.
  'hair-stylist-esthetician-apprenticeship',

  -- Nail tech duplicates (canonical: nail-technician-apprenticeship)
  'nail-technician',
  'nail-tech-apprenticeship',
  'hair-stylist-nail-tech-apprenticeship',

  -- Phlebotomy duplicates (canonical: phlebotomy)
  'phlebotomy-technician',

  -- Pharmacy duplicates (canonical: pharmacy-technician)
  -- nha-pharmacy-technician is the NHA-branded version; pharmacy-technician is canonical
  -- Keep both active but mark nha version as the LMS course variant

  -- Peer recovery duplicates (canonical: peer-recovery-specialist)
  'peer-support',
  'peer-recovery-specialist-jri',
  'certified-recovery-specialist',

  -- Tax prep duplicates (canonical: tax-preparation)
  'tax-prep',

  -- Health/safety duplicates (canonical: cpr-first-aid or emergency-health-safety)
  'health-safety',

  -- DSP duplicates (canonical: direct-support-professional)
  'dsp-training',

  -- Drug collector duplicates (canonical: drug-alcohol-specimen-collector)
  -- drug-collector slug → drug-alcohol-specimen-collector is canonical per DB

  -- Bookkeeping duplicates (canonical: bookkeeping)
  'bookkeeping-fundamentals',

  -- Entrepreneurship duplicates (canonical: entrepreneurship)
  'entrepreneurship-small-business',

  -- Forklift duplicates (canonical: forklift)
  'forklift-operator',

  -- IT duplicates (canonical: it-help-desk)
  'it-support',
  'it-support-specialist',

  -- Building services duplicates (canonical: building-services-technician)
  'building-services-technician-apprenticeship',

  -- Recovery coach duplicates
  'recovery-coach',

  -- EMS duplicates (keep emt-apprenticeship as canonical)
  'ems-apprenticeship'
);

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 3: Ensure canonical programs are active and published
-- ─────────────────────────────────────────────────────────────────────────────

UPDATE public.programs
SET status = 'active', is_active = true, published = true
WHERE slug IN (
  -- Core healthcare
  'cna',
  'qma',
  'medical-assistant',
  'peer-recovery-specialist',
  'direct-support-professional',
  'drug-alcohol-specimen-collector',
  'cpr-first-aid',
  'pharmacy-technician',
  'phlebotomy',
  'home-health-aide',
  'sanitation-infection-control',
  'dental-assistant',
  'chw-cert',
  -- NHA suite (active LMS courses)
  'nha-pharmacy-technician',
  'nha-ehr',
  'nha-patient-care-technician',
  'nha-medical-admin-assistant',
  'nha-medical-assistant',
  'nha-billing-coding',
  'nha-phlebotomy',
  'nha-ekg-technician',
  -- Skilled trades
  'hvac-technician',
  'electrical',
  'plumbing',
  'cdl-training',
  'welding',
  'building-services-technician',
  'building-maintenance-wrg',
  'solar-panel-installation',
  'manufacturing-technician',
  'diesel-mechanic',
  'automotive-technician',
  'construction-trades-certification',
  -- Apprenticeships
  'barber-apprenticeship',
  'cosmetology-apprenticeship',
  'esthetician-apprenticeship',
  'nail-technician-apprenticeship',
  'culinary-apprenticeship',
  'youth-culinary-apprenticeship',
  'emt-apprenticeship',
  -- Business & finance
  'finance-bookkeeping-accounting',
  'bookkeeping',
  'tax-preparation',
  'entrepreneurship',
  'business-startup',
  'business-administration',
  'real-estate-agent',
  'insurance-agent',
  'administrative-assistant',
  'customer-service-representative',
  'office-administration',
  -- Technology
  'it-help-desk',
  'software-development',
  'web-development',
  'data-analytics',
  'cybersecurity-analyst',
  'network-administration',
  'network-support-technician',
  'project-management',
  'cad-drafting',
  'graphic-design',
  -- Special programs
  'jri',
  'jri-introduction',
  'jri-badge-1-mindsets',
  'jri-badge-2-self-management',
  'jri-badge-3-learning-strategies',
  'jri-badge-4-social-skills',
  'jri-badge-5-workplace-skills',
  'jri-badge-6-launch-a-career',
  'reentry-specialist',
  'life-coach-certification-wioa',
  'nrf-riseup',
  -- Hospitality
  'start-hospitality',
  'guest-service-gold',
  'servsuccess',
  'servsafe-food-handler',
  'servsafe-manager',
  -- Professional
  'esthetician',
  'nail-technician-apprenticeship',
  'forklift',
  'pharmacy-technician'
);

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 4: Ensure courses table has rows for all canonical programs
-- Links programs → courses so the LMS engine can serve them.
-- Uses INSERT ... ON CONFLICT DO NOTHING to be safe.
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO public.courses (id, title, slug, program_id, status, created_at)
SELECT
  gen_random_uuid(),
  p.title,
  p.slug || '-course',
  p.id,
  'published',
  now()
FROM public.programs p
WHERE p.status = 'active'
  AND p.is_active = true
  AND NOT EXISTS (
    SELECT 1 FROM public.courses c WHERE c.program_id = p.id
  )
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 5: Add short_description to programs that are missing it
-- ─────────────────────────────────────────────────────────────────────────────

-- Ensure column exists (safe if already present)
ALTER TABLE public.programs
  ADD COLUMN IF NOT EXISTS short_description text,
  ADD COLUMN IF NOT EXISTS display_order integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS category text;

-- Set categories for canonical programs
UPDATE public.programs SET category = 'healthcare' WHERE slug IN (
  'cna','qma','medical-assistant','peer-recovery-specialist','direct-support-professional',
  'drug-alcohol-specimen-collector','cpr-first-aid','pharmacy-technician','phlebotomy',
  'home-health-aide','sanitation-infection-control','dental-assistant','chw-cert',
  'nha-pharmacy-technician','nha-ehr','nha-patient-care-technician','nha-medical-admin-assistant',
  'nha-medical-assistant','nha-billing-coding','nha-phlebotomy','nha-ekg-technician'
);

UPDATE public.programs SET category = 'trades' WHERE slug IN (
  'hvac-technician','electrical','plumbing','cdl-training','welding',
  'building-services-technician','building-maintenance-wrg','solar-panel-installation',
  'manufacturing-technician','diesel-mechanic','automotive-technician',
  'construction-trades-certification','forklift'
);

UPDATE public.programs SET category = 'apprenticeship' WHERE slug IN (
  'barber-apprenticeship','cosmetology-apprenticeship','esthetician-apprenticeship',
  'nail-technician-apprenticeship','culinary-apprenticeship','youth-culinary-apprenticeship',
  'emt-apprenticeship'
);

UPDATE public.programs SET category = 'business' WHERE slug IN (
  'finance-bookkeeping-accounting','bookkeeping','tax-preparation','entrepreneurship',
  'business-startup','business-administration','real-estate-agent','insurance-agent',
  'administrative-assistant','customer-service-representative','office-administration',
  'project-management'
);

UPDATE public.programs SET category = 'technology' WHERE slug IN (
  'it-help-desk','software-development','web-development','data-analytics',
  'cybersecurity-analyst','network-administration','network-support-technician',
  'cad-drafting','graphic-design'
);

UPDATE public.programs SET category = 'special' WHERE slug IN (
  'jri','jri-introduction','jri-badge-1-mindsets','jri-badge-2-self-management',
  'jri-badge-3-learning-strategies','jri-badge-4-social-skills',
  'jri-badge-5-workplace-skills','jri-badge-6-launch-a-career',
  'reentry-specialist','life-coach-certification-wioa','nrf-riseup'
);

UPDATE public.programs SET category = 'hospitality' WHERE slug IN (
  'start-hospitality','guest-service-gold','servsuccess','servsafe-food-handler','servsafe-manager'
);

UPDATE public.programs SET category = 'beauty' WHERE slug IN (
  'esthetician','nail-technician-apprenticeship','cosmetology-apprenticeship',
  'barber-apprenticeship','esthetician-apprenticeship'
);

-- ─────────────────────────────────────────────────────────────────────────────
-- VERIFICATION QUERIES — run these after applying to confirm results
-- ─────────────────────────────────────────────────────────────────────────────

-- Count by status:
-- SELECT status, count(*) FROM public.programs GROUP BY status ORDER BY status;

-- Active programs with no course row:
-- SELECT p.slug, p.title FROM public.programs p
-- WHERE p.status = 'active' AND NOT EXISTS (SELECT 1 FROM public.courses c WHERE c.program_id = p.id)
-- ORDER BY p.slug;

-- Archived programs:
-- SELECT slug, title FROM public.programs WHERE status = 'archived' ORDER BY slug;

-- Programs by category:
-- SELECT category, count(*) FROM public.programs WHERE status = 'active' GROUP BY category ORDER BY category;
