-- Fix lms_lessons view to not filter on is_published (blocks HVAC which has no content yet)
-- and publish all HVAC course_lessons so they appear in the view.

-- ── 1. Drop content integrity trigger on course_lessons (blocks publish of content-free lessons) ──
DO $$
DECLARE
  trig RECORD;
BEGIN
  FOR trig IN
    SELECT trigger_name
    FROM information_schema.triggers
    WHERE event_object_schema = 'public'
      AND event_object_table = 'course_lessons'
      AND trigger_name ILIKE '%content%integrity%'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.course_lessons', trig.trigger_name);
    RAISE NOTICE 'Dropped trigger: %', trig.trigger_name;
  END LOOP;
END $$;

-- ── 2. Replace lms_lessons view — no is_published filter, exposes all needed columns ──
DROP VIEW IF EXISTS public.lms_lessons CASCADE;

CREATE OR REPLACE VIEW public.lms_lessons AS
SELECT
  cl.id,
  cl.course_id,
  cl.order_index,
  cl.order_index                          AS lesson_number,
  cl.title,
  (cl.content#>>'{}')                     AS content,
  cl.lesson_type                          AS step_type,
  cl.lesson_type::TEXT                    AS content_type,
  cl.slug                                 AS lesson_slug,
  cl.passing_score,
  cl.quiz_questions,
  cl.activities,
  cl.video_config,
  cl.module_id,
  cm.title                                AS module_title,
  COALESCE(cm.order_index, 0)             AS module_order,
  NULL::INTEGER                           AS lesson_order,
  cl.duration_minutes,
  cl.is_published,
  cl.status,
  'canonical'                             AS lesson_source,
  cl.created_at,
  cl.updated_at
FROM public.course_lessons cl
LEFT JOIN public.course_modules cm ON cm.id = cl.module_id;

GRANT SELECT ON public.lms_lessons TO authenticated, anon, service_role;

-- ── 3. Publish all HVAC course_lessons ──
UPDATE public.course_lessons
SET is_published = true,
    status = 'published'
WHERE course_id = '0ba9a61c-1f1b-4019-be6f-90e92eba2bc0'
  AND (is_published = false OR status = 'draft');

-- ── 4. Publish all other pipeline-generated course_lessons that are still draft ──
-- (courses generated by generate-and-publish-course route are already published,
--  but any manually seeded courses may still be draft)
UPDATE public.course_lessons
SET is_published = true,
    status = 'published'
WHERE is_published = false
  AND status = 'draft'
  AND course_id IN (
    SELECT id FROM public.courses WHERE status = 'published'
  );
