-- PRS competency_exam_profiles seed
-- 30 competency keys derived from scripts/prs-lesson-payloads.ts.
-- Every key used in competency_keys[] across all 39 PRS lessons is covered.
-- Apply manually via Supabase Dashboard SQL Editor.
--
-- Verification query (run after applying):
--   SELECT competency_key FROM competency_exam_profiles
--   WHERE program_slug = 'peer-recovery-specialist-jri'
--   ORDER BY competency_key;
-- Expected: 30 rows.

INSERT INTO competency_exam_profiles (
  competency_key, competency_name, program_slug,
  must_assess, exam_domain, exam_subdomain,
  required_phrases, requires_distinction,
  distinction_side_a, distinction_side_b, distinction_label,
  distractor_phrases, distractor_explanation,
  cognitive_operation, response_depth
) VALUES

-- ── Domain: Foundations of Peer Recovery Support ──────────────────────────────

('prs_role_definition',
 'PRS Role Definition and Scope of Practice',
 'peer-recovery-specialist-jri',
 true, 'foundations', 'role_and_scope',
 ARRAY['lived experience', 'scope of practice', 'not clinical', 'peer support'],
 true,
 ARRAY['peer specialist', 'lived experience', 'non-clinical support'],
 ARRAY['therapist', 'counselor', 'case manager', 'clinical diagnosis'],
 'PRS role vs. clinical role',
 ARRAY['therapist', 'prescriber', 'supervisor'],
 'PRS is not a clinical role; confusing it with clinical functions is a scope violation.',
 'distinguish', 'applied'),

('recovery_oriented_principles',
 'Recovery-Oriented Systems of Care Principles',
 'peer-recovery-specialist-jri',
 true, 'foundations', 'rosc',
 ARRAY['person-centered', 'self-determination', 'strengths-based', 'SAMHSA dimensions'],
 false, '{}', '{}', NULL,
 ARRAY['compliance-based', 'deficit-focused', 'clinician-directed'],
 'Recovery-oriented care centers the person, not the provider.',
 'apply', 'conceptual'),

('peer_support_history',
 'History and Evolution of Peer Support',
 'peer-recovery-specialist-jri',
 true, 'foundations', 'history',
 ARRAY['consumer-survivor movement', 'mutual aid', 'Medicaid billable', 'professionalization'],
 false, '{}', '{}', NULL,
 ARRAY['government mandate', 'clinical invention', 'insurance requirement'],
 'Peer support grew from grassroots advocacy, not top-down policy.',
 'recall', 'conceptual'),

('professional_boundaries_intro',
 'Professional Boundaries and Role Clarity',
 'peer-recovery-specialist-jri',
 true, 'foundations', 'boundaries',
 ARRAY['professional boundary', 'dual relationship', 'scope of practice', 'over-involvement'],
 true,
 ARRAY['professional boundary', 'role clarity', 'safe relationship'],
 ARRAY['friendship', 'personal relationship', 'over-identification'],
 'Professional vs. personal relationship',
 ARRAY['personal friend', 'sponsor', 'family member'],
 'Boundaries protect both parties; confusing professional and personal roles harms the relationship.',
 'distinguish', 'applied'),

-- ── Domain: Ethics and Professional Conduct ───────────────────────────────────

('prs_code_of_ethics',
 'PRS Code of Ethics',
 'peer-recovery-specialist-jri',
 true, 'ethics', 'code_of_ethics',
 ARRAY['integrity', 'competence', 'respect', 'mandatory reporting', 'exploitation'],
 false, '{}', '{}', NULL,
 ARRAY['personal preference', 'agency policy only', 'supervisor discretion'],
 'The code of ethics is a professional standard, not optional guidance.',
 'apply', 'applied'),

('confidentiality_hipaa',
 'Confidentiality, HIPAA, and 42 CFR Part 2',
 'peer-recovery-specialist-jri',
 true, 'ethics', 'confidentiality',
 ARRAY['HIPAA', 'PHI', '42 CFR Part 2', 'covered entity', 'exceptions to confidentiality'],
 true,
 ARRAY['HIPAA', 'general health information', 'covered entity'],
 ARRAY['42 CFR Part 2', 'substance use disorder records', 'stricter standard'],
 'HIPAA vs. 42 CFR Part 2',
 ARRAY['family member access', 'employer access', 'automatic disclosure'],
 '42 CFR Part 2 is stricter than HIPAA and applies specifically to SUD records.',
 'distinguish', 'analytical'),

('dual_relationships',
 'Dual Relationships and Conflict of Interest',
 'peer-recovery-specialist-jri',
 true, 'ethics', 'dual_relationships',
 ARRAY['dual relationship', 'conflict of interest', 'transfer of care', 'exploitation'],
 false, '{}', '{}', NULL,
 ARRAY['normal friendship', 'community overlap', 'acceptable boundary'],
 'Any second role with a client outside the professional context requires disclosure and often transfer.',
 'apply', 'applied'),

('ethical_decision_making',
 'Ethical Decision-Making Process',
 'peer-recovery-specialist-jri',
 true, 'ethics', 'decision_making',
 ARRAY['ethical dilemma', 'consult supervisor', 'document reasoning', 'five-step process'],
 false, '{}', '{}', NULL,
 ARRAY['act alone', 'ignore the dilemma', 'personal judgment only'],
 'Ethical dilemmas require a structured process and supervisor consultation, not solo judgment.',
 'apply', 'analytical'),

('ethics_professional_conduct',
 'Ethics and Professional Conduct in Practice',
 'peer-recovery-specialist-jri',
 true, 'ethics', 'professional_conduct',
 ARRAY['professional conduct', 'informed consent', 'participant rights', 'grievance'],
 false, '{}', '{}', NULL,
 ARRAY['personal preference', 'informal agreement', 'verbal only'],
 'Professional conduct requires documented consent and knowledge of participant rights.',
 'apply', 'applied'),

('mandatory_reporting',
 'Mandatory Reporting Obligations',
 'peer-recovery-specialist-jri',
 true, 'ethics', 'mandatory_reporting',
 ARRAY['mandatory reporting', 'duty to warn', 'imminent danger', 'supervisor notification'],
 true,
 ARRAY['mandatory reporting', 'safety override', 'imminent danger'],
 ARRAY['confidentiality', 'client preference', 'voluntary disclosure'],
 'Mandatory reporting vs. confidentiality',
 ARRAY['optional reporting', 'client consent required', 'agency discretion'],
 'Mandatory reporting obligations override confidentiality when safety is at risk.',
 'distinguish', 'applied'),

-- ── Domain: Recovery Models and Wellness ──────────────────────────────────────

('recovery_models',
 'Recovery Models: Abstinence, Harm Reduction, MAT, Wellness',
 'peer-recovery-specialist-jri',
 true, 'recovery_wellness', 'models',
 ARRAY['abstinence-based', 'harm reduction', 'MAT', 'evidence-based', 'ROSC'],
 true,
 ARRAY['harm reduction', 'MAT', 'evidence-based treatment'],
 ARRAY['moral failure', 'trading addiction', 'not real recovery'],
 'Evidence-based recovery vs. stigmatizing framing',
 ARRAY['only one right path', 'abstinence only', 'MAT is not recovery'],
 'Multiple evidence-based recovery models exist; no single path is universally correct.',
 'distinguish', 'conceptual'),

('stages_of_change',
 'Stages of Change (Transtheoretical Model)',
 'peer-recovery-specialist-jri',
 true, 'recovery_wellness', 'behavior_change',
 ARRAY['precontemplation', 'contemplation', 'preparation', 'action', 'maintenance', 'relapse'],
 false, '{}', '{}', NULL,
 ARRAY['push toward action', 'confront denial', 'force readiness'],
 'Meeting clients at their current stage is more effective than pushing toward action they are not ready for.',
 'apply', 'applied'),

('wellness_self_care',
 'Wellness and Self-Care as Professional Obligations',
 'peer-recovery-specialist-jri',
 true, 'recovery_wellness', 'wellness',
 ARRAY['eight dimensions of wellness', 'burnout', 'vicarious trauma', 'self-care', 'professional sustainability'],
 false, '{}', '{}', NULL,
 ARRAY['optional', 'personal choice only', 'not work-related'],
 'Self-care is a professional obligation for peer specialists, not optional.',
 'apply', 'conceptual'),

('relapse_prevention',
 'Relapse Prevention and Recovery Support',
 'peer-recovery-specialist-jri',
 true, 'recovery_wellness', 'relapse',
 ARRAY['trigger', 'warning signs', 'coping strategies', 'relapse prevention plan', 'shame'],
 true,
 ARRAY['relapse as part of recovery', 'non-judgmental response', 're-engagement'],
 ARRAY['moral failure', 'treatment failure', 'end of recovery'],
 'Relapse as process vs. relapse as failure',
 ARRAY['lecture about consequences', 'terminate services', 'express disappointment'],
 'Relapse is common and does not end recovery; how the peer specialist responds matters more than the relapse itself.',
 'distinguish', 'applied'),

('professional_sustainability',
 'Professional Sustainability and Burnout Prevention',
 'peer-recovery-specialist-jri',
 true, 'recovery_wellness', 'sustainability',
 ARRAY['burnout', 'vicarious trauma', 'warning signs', 'supervision', 'self-monitoring'],
 false, '{}', '{}', NULL,
 ARRAY['push through', 'ignore warning signs', 'personal weakness'],
 'Burnout and vicarious trauma are occupational hazards requiring proactive management.',
 'apply', 'conceptual'),

-- ── Domain: Peer Support Skills ───────────────────────────────────────────────

('active_listening_empathy',
 'Active Listening and Empathy',
 'peer-recovery-specialist-jri',
 true, 'peer_skills', 'listening',
 ARRAY['reflective listening', 'open questions', 'summarizing', 'non-verbal communication', 'empathy'],
 false, '{}', '{}', NULL,
 ARRAY['advice-giving', 'problem-solving first', 'waiting to talk'],
 'Active listening requires full attention and intentional response before offering solutions.',
 'apply', 'applied'),

('motivational_interviewing',
 'Motivational Interviewing (OARS)',
 'peer-recovery-specialist-jri',
 true, 'peer_skills', 'mi',
 ARRAY['OARS', 'ambivalence', 'rolling with resistance', 'change talk', 'collaborative'],
 true,
 ARRAY['collaborative', 'elicit change talk', 'reduce ambivalence'],
 ARRAY['confrontational', 'coercive', 'directive'],
 'MI spirit vs. confrontational approach',
 ARRAY['argue with resistance', 'push toward action', 'confront denial'],
 'MI is collaborative and non-confrontational; confrontation increases resistance.',
 'distinguish', 'applied'),

('self_disclosure',
 'Strategic Self-Disclosure',
 'peer-recovery-specialist-jri',
 true, 'peer_skills', 'self_disclosure',
 ARRAY['strategic self-disclosure', 'purpose', 'over-disclosure', 'client-centered', 'boundaries'],
 true,
 ARRAY['serves the client', 'intentional', 'builds hope'],
 ARRAY['over-disclosure', 'shifts focus to peer specialist', 'graphic detail'],
 'Therapeutic vs. over-disclosure',
 ARRAY['share everything', 'full story always', 'no filter needed'],
 'Self-disclosure must serve the client''s recovery, not the peer specialist''s need to be understood.',
 'distinguish', 'applied'),

('rapport_trust_building',
 'Rapport and Trust Building',
 'peer-recovery-specialist-jri',
 true, 'peer_skills', 'rapport',
 ARRAY['rapport', 'consistency', 'authenticity', 'trauma-informed', 'therapeutic alliance'],
 false, '{}', '{}', NULL,
 ARRAY['intensity over consistency', 'quick fix', 'technique-driven'],
 'Trust is built through consistent follow-through, not intensity or technique.',
 'apply', 'applied'),

('peer_support_skills',
 'Core Peer Support Skills Integration',
 'peer-recovery-specialist-jri',
 true, 'peer_skills', 'integration',
 ARRAY['peer support skills', 'active listening', 'motivational interviewing', 'self-disclosure', 'rapport'],
 false, '{}', '{}', NULL,
 ARRAY['clinical skills', 'therapy techniques', 'assessment tools'],
 'Peer support skills are distinct from clinical skills and grounded in lived experience.',
 'apply', 'analytical'),

('trauma_informed_practice',
 'Trauma-Informed Practice',
 'peer-recovery-specialist-jri',
 true, 'peer_skills', 'trauma',
 ARRAY['trauma-informed', 'safety', 'trustworthiness', 'empowerment', 'trauma history'],
 false, '{}', '{}', NULL,
 ARRAY['trauma-blind', 'ignore history', 'push through discomfort'],
 'Trauma-informed practice recognizes how trauma affects engagement and adjusts accordingly.',
 'apply', 'conceptual'),

-- ── Domain: Advocacy and Empowerment ─────────────────────────────────────────

('advocacy_empowerment',
 'Advocacy and Empowerment',
 'peer-recovery-specialist-jri',
 true, 'advocacy', 'empowerment',
 ARRAY['self-advocacy', 'systems advocacy', 'capacity building', 'empowerment', 'autonomy'],
 true,
 ARRAY['doing with', 'capacity building', 'empowerment'],
 ARRAY['doing for', 'dependency', 'taking over'],
 'Empowerment vs. dependency',
 ARRAY['do it for them', 'solve the problem', 'take control'],
 'Advocacy builds client capacity; doing things for clients creates dependency.',
 'distinguish', 'applied'),

('participant_rights',
 'Participant Rights in Behavioral Health',
 'peer-recovery-specialist-jri',
 true, 'advocacy', 'rights',
 ARRAY['informed consent', 'right to refuse', 'grievance procedure', 'HIPAA rights', 'participant rights'],
 false, '{}', '{}', NULL,
 ARRAY['provider discretion', 'automatic compliance', 'rights waived at intake'],
 'Participants retain rights throughout treatment; peer specialists help them exercise those rights.',
 'apply', 'applied'),

-- ── Domain: Resource Navigation ───────────────────────────────────────────────

('resource_navigation',
 'Resource Navigation and Linkage',
 'peer-recovery-specialist-jri',
 true, 'resource_navigation', 'navigation',
 ARRAY['resource mapping', 'warm handoff', 'referral', 'follow-up', 'linkage'],
 true,
 ARRAY['warm handoff', 'personal introduction', 'follow-up confirmation'],
 ARRAY['cold referral', 'give a number', 'no follow-up'],
 'Warm handoff vs. cold referral',
 ARRAY['assume they will call', 'referral is enough', 'no documentation needed'],
 'Cold referrals fail at high rates; warm handoffs with follow-up are the standard.',
 'distinguish', 'applied'),

('community_connections',
 'Community Resource Knowledge and Mapping',
 'peer-recovery-specialist-jri',
 true, 'resource_navigation', 'community',
 ARRAY['community assets', 'resource directory', 'eligibility', 'verify before referring', '211'],
 false, '{}', '{}', NULL,
 ARRAY['assume resources are current', 'refer without checking eligibility', 'no directory needed'],
 'Resource knowledge must be current and verified; outdated referrals harm clients.',
 'apply', 'conceptual'),

-- ── Domain: Crisis Support and Safety ────────────────────────────────────────

('crisis_support_safety',
 'Crisis Support and Safety Planning',
 'peer-recovery-specialist-jri',
 true, 'crisis', 'crisis_support',
 ARRAY['crisis support', 'de-escalation', 'safety planning', 'scope of practice', 'supervisor notification'],
 true,
 ARRAY['peer crisis support', 'de-escalation', 'stay present', 'call for help'],
 ARRAY['clinical crisis intervention', 'risk assessment', 'diagnose'],
 'PRS crisis support vs. clinical crisis intervention',
 ARRAY['conduct risk assessment', 'manage crisis alone', 'clinical intervention'],
 'PRS provides crisis support within scope; clinical crisis intervention is outside PRS role.',
 'distinguish', 'applied'),

-- ── Domain: Documentation and Professional Development ───────────────────────

('documentation_skills',
 'Documentation Skills and Case Notes',
 'peer-recovery-specialist-jri',
 true, 'documentation', 'case_notes',
 ARRAY['case notes', 'documentation', 'objective', 'subjective', 'SOAP', 'timely'],
 false, '{}', '{}', NULL,
 ARRAY['informal notes', 'memory only', 'skip documentation'],
 'Documentation is a professional and legal obligation; informal or absent notes create liability.',
 'apply', 'applied'),

('professional_identity',
 'Professional Identity and Career Development',
 'peer-recovery-specialist-jri',
 true, 'documentation', 'professional_identity',
 ARRAY['professional identity', 'CPRS credential', 'career pathway', 'continuing education'],
 false, '{}', '{}', NULL,
 ARRAY['informal helper', 'no credential needed', 'static role'],
 'PRS is a credentialed profession with defined career pathways and continuing education requirements.',
 'recall', 'conceptual'),

('professional_development',
 'Professional Development and Continuing Education',
 'peer-recovery-specialist-jri',
 true, 'documentation', 'development',
 ARRAY['continuing education', 'supervision', 'professional growth', 'CPRS renewal'],
 false, '{}', '{}', NULL,
 ARRAY['one-time training', 'no renewal needed', 'self-directed only'],
 'CPRS certification requires ongoing continuing education and supervision.',
 'apply', 'conceptual'),

('certification_prep',
 'CPRS Certification Exam Preparation',
 'peer-recovery-specialist-jri',
 true, 'documentation', 'certification',
 ARRAY['CPRS exam', 'certification readiness', 'exam domains', 'practice exam', 'application process'],
 false, '{}', '{}', NULL,
 ARRAY['no preparation needed', 'pass automatically', 'exam is optional'],
 'CPRS certification requires deliberate preparation across all exam domains.',
 'apply', 'applied')

ON CONFLICT (competency_key) DO UPDATE SET
  competency_name        = EXCLUDED.competency_name,
  program_slug           = EXCLUDED.program_slug,
  must_assess            = EXCLUDED.must_assess,
  exam_domain            = EXCLUDED.exam_domain,
  exam_subdomain         = EXCLUDED.exam_subdomain,
  required_phrases       = EXCLUDED.required_phrases,
  requires_distinction   = EXCLUDED.requires_distinction,
  distinction_side_a     = EXCLUDED.distinction_side_a,
  distinction_side_b     = EXCLUDED.distinction_side_b,
  distinction_label      = EXCLUDED.distinction_label,
  distractor_phrases     = EXCLUDED.distractor_phrases,
  distractor_explanation = EXCLUDED.distractor_explanation,
  cognitive_operation    = EXCLUDED.cognitive_operation,
  response_depth         = EXCLUDED.response_depth,
  updated_at             = now();
